### ISSUE TITLE
Tap action not working

### ISSUE THREAD

**Issue by Drealine** [UI-Lovelace-Minimalist/UI#1000]
**Describe the bug**
When set "navigate" value into ulm_card_tap_action, it create an error in dev google mod.

**To Reproduce**

Set this 
ulm_card_tap_action: "navigate"

Error : 
button-card.js:425 Uncaught ButtonCardJSTemplateError: TypeError: Cannot read properties of undefined (reading 'entity_id') in 'var action = variables.ulm_card_tap_action;

Relative to this code, it seems that it try to found entity_id in action_card.yaml ?

```
if (action == 'adaptive'){
          return {
            'option': variables.ulm_input_select_option,
            'entity_id': variables.ulm_input_select
          };
        }
        if(entity.entity_id.startsWith("media_player.")){
          return {
            'entity_id': entity.entity_id
          };
        }
```

**Comment by basbruss** [comment]
Should be fixed in the latest release
