### ISSUE TITLE
Problems since upgrading to v1.1.4

### ISSUE THREAD

**Issue by schumijo** [UI-Lovelace-Minimalist/UI#1005]
**Describe the bug**
Unavailable notification is hidden and card width match name size since upgrading to v1.1.4

**Screenshots**
v1.1.3
![Capture1](https://user-images.githubusercontent.com/40740060/190983129-c5ae8680-fc56-4ad4-9f35-62324db060af.PNG)

v1.1.4
![Capture2](https://user-images.githubusercontent.com/40740060/190982236-e9f9d365-4d47-41ab-8307-dbbe3777b606.PNG)

**Additional context**
Will try to work on PR but not enough time

**Comment by schumijo** [comment]
Hi @basbruss 
Card size seems to be related to your commit in #994 
Before doing any change, what was the purpose of this change ?

**Comment by basbruss** [comment]
Hi @schumijo 

@AndyVRD suggested adding an overflow to the text to prevent it from being cut off in the middle of the card.
But seeing your issue it also stretches the card when the text is longer than the appropriate width of the card.
