### ISSUE TITLE
Wearable battery state for custom person info card

### ISSUE THREAD

**Issue by XilefTech** [UI-Lovelace-Minimalist/UI#1006]
**Is your enhancement request related to a problem? Please describe.**
I really like the style of the [custom card person info](https://github.com/UI-Lovelace-Minimalist/UI/tree/main/custom_cards/custom_card_person_info) but one thing I find kinda annoying is that it can only display the battery power of one device. I personally have a galaxy watch besides my phone, that also has the homeassistant wearOS app installed, capable of reporting back battery and charging status. It would be really awesome to be able to see that information on the person-card aswell

**Describe the solution you'd like**
It would be really nice if you had the option to set two battery entities for each person. I think it would be easiest to label them with `mdi:cellphone` and `mdi:watch` so you can easily differentiate between the two battery states

**Comment by basbruss** [comment]
Hi someone just shared his code for something similar in the discussion section #1017

**Comment by XilefTech** [comment]
thank you very much
