### ISSUE TITLE
custom_card_tpx01_aircondition gives failed to call service script

### ISSUE THREAD

**Issue by nautiqu3** [UI-Lovelace-Minimalist/UI#101]
When using the custom_card_tpx01_aircondition and try to adjust the ac up or down on the card you get this:
![image](https://user-images.githubusercontent.com/6637988/146560885-03caffd9-5695-4556-9cf2-20bcaa465df0.png)

It does however work with the popup. 
![image](https://user-images.githubusercontent.com/6637988/146560960-1abeede8-1df9-43c6-bdb8-fa18a0df5422.png)

**Comment by mlittle408** [comment]
I just came across this as well. Don't they include their scripts with custom components?

**Comment by CM000n** [comment]
No, the scripts were created by tpx01 himself to cover his use cases. They have nothing to do with the actual UI. Unfortunately, the template for the card was then transferred without any attention being paid to it.

**Comment by mlittle408** [comment]
Ok. give me a few minutes and I'll whip together a script that will work.

**Comment by CM000n** [comment]
Thx. I don't think we should start delivering scripts now. It would be better to rebuild the template so that it is directly usable without additional scripts. For example by using `climate.set_temperature` or similar.

**Comment by mlittle408** [comment]
Ok. I can do that.

**Comment by CM000n** [comment]
Feel free :-) Any contribution is welcome

**Comment by nautiqu3** [comment]
> Ok. I can do that.

Sweet! Looking forward to it! :)

**Comment by mlittle408** [comment]
I have fixed the custom_card_tpx01_aircondition to increment and decrement the temp without the use of scripts. I also made some changes to the "off" button so it will toggle through the hvac_modes. What was never included in the original button was the ability to handle the heat_cool mode. I am still working on that now. If you would like to try out what I have so far, just let me know and I can sent it to you. Or just tell me where I can paste the code. I am also going to make a collapsible version that will hide the raise/lower buttons when the thermostat is off. I may even do one with a slider to raise / lower the temp.

**Comment by mlittle408** [comment]
One more thing. At the moment the Celsius / Fahrenheit is hardcoded in the template, I am still working on that as well.

**Comment by CM000n** [comment]
Just make a pull request so that we can have a look at it together :-)

**Comment by mlittle408** [comment]
> Just make a pull request so that we can have a look at it together :-)

I have no idea how to do that. I cloned the dev repository and added my files but, from there, I am lost.

**Comment by httpedo13** [comment]
Because you don't have the script "increment_climate_tempersture" and "defrease_climatw_temperature" and @tpx01 don't add these in the repository.

Check my card if you only have a thermostat.

**Comment by TPX01** [comment]
> Because you don't have the script "increment_climate_tempersture" and "defrease_climatw_temperature" and @TPX01 don't add these in the repository.
> 
> Check my card if you only have a thermostat.

`increment_climate_temperature:
    sequence:
    - service: climate.set_temperature
      data_template:
        entity_id: "{{ entity_id }}"
        temperature: >
          {{ (state_attr(entity_id, 'temperature') | float) + (state_attr(entity_id, 'target_temp_step') | float) | float }}
decrease_climate_temperature:
    sequence:
    - service: climate.set_temperature
      data_template:
        entity_id: "{{ entity_id }}"
        temperature: >
          {{ (state_attr(entity_id, 'temperature') | float) - (state_attr(entity_id, 'target_temp_step') | float) | float }}`

**Comment by CM000n** [comment]
Thank you very much @TPX01. I think we should just modify the card to call the `climate.set_temperature` service directly instead of the script. That is not a problem. Let's see what @mlittle408  came up with in his PR. ☺️ https://github.com/UI-Lovelace-Minimalist/UI/pull/122

**Comment by nautiqu3** [comment]
> > Because you don't have the script "increment_climate_tempersture" and "defrease_climatw_temperature" and @TPX01 don't add these in the repository.
> > Check my card if you only have a thermostat.
> 
> ```
> increment_climate_temperature:
>     sequence:
>     - service: climate.set_temperature
>       data_template:
>         entity_id: "{{ entity_id }}"
>         temperature: >
>           {{ (state_attr(entity_id, 'temperature') | float) + (state_attr(entity_id, 'target_temp_step') | float) | float }}
> decrease_climate_temperature:
>     sequence:
>     - service: climate.set_temperature
>       data_template:
>         entity_id: "{{ entity_id }}"
>         temperature: >
>           {{ (state_attr(entity_id, 'temperature') | float) - (state_attr(entity_id, 'target_temp_step') | float) | float }}
> ```
> 
> Does this help? 😉😁
> 
> Just add these to the `scripts` section in your configuration and you're good to go!

Yeah, that's easy. 
But the problem is if someone has more than one AC. Then you have to create more custom cards and scripts.
