### ISSUE TITLE
Popup change back from color to temperature

### ISSUE THREAD

**Issue by lk-dll** [UI-Lovelace-Minimalist/UI#1014]
**Describe the bug**
On RGB light devices, when change color in popup, I'm not able to choose back a white temperature. Tested only on zigbee, wifi need confirmation. Zigbee tested in deconz and z2m. It affects both the mobile app and the web.

**To Reproduce**
1. Open color light popup
2. Turn on the light
3. Choose some color in color tab
4. Change to temperature tab and choose some

**Expected behavior**
When I choose some color and I want to choose back some temperature of white.

**Additional context**
I updated Minimalist after long period and in previous version 0.x it worked.

**Comment by schumijo** [comment]
See #982

**Comment by lk-dll** [comment]
Definitely related to and duplicated. So closing
