### ISSUE TITLE
Graph card error

### ISSUE THREAD

**Issue by ericlamoureux285** [UI-Lovelace-Minimalist/UI#1015]
I add the graph card to see the outdoor temperature. But the graph don't show up, I only get a error.

Here is the code:
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        template: card_graph
        variables:
          ulm_card_graph_color: "var(--google-blue)"
          ulm_card_graph_name: Temperature
          ulm_card_graph_entity: sensor.thermostat_outdoor_temperature
          ulm_card_graph_type: fill
          ulm_card_graph_hours: 24

Here is what I get:
![Screenshot_20220922-153603](https://user-images.githubusercontent.com/78269461/191836172-6fefdfb0-32d5-4cb7-b1dd-0854b4fdcfdf.jpg)

Anybody know if is only on my side?

**Comment by basbruss** [comment]
You also need to specify the entity outside the variables, like  as with the light card for example

**Comment by ericlamoureux285** [comment]
@basbruss damm thanks I knew it was a simple mistake, I just couldn't figure it out! Thanks!!

**Comment by aazimh** [comment]
Just wanted to thank you guys for helping me solve this - it's been bugging me for literally months and I never thought to come here and check. Thank you!
