### ISSUE TITLE
Override subicon in room card

### ISSUE THREAD

**Issue by prjcarr** [UI-Lovelace-Minimalist/UI#1019]
I am trying to override an icon in the room card. I have a climate device but it is using the thermostat icon, and I would like to use mdi: thermometer instead. I have tried the following but it doesnt work:

> cards:

      - type: 'custom:button-card'
        template:
        - card_room
        - red_no_state
        name: Lounge Room
        entity: light.lounge_room_lights
        icon: mdi:sofa
        tap_action:
          action: navigate
          navigation_path: '/ui-lovelace-minimalist/lounge-room'
        variables:
          label_use_temperature: false
          label_use_brightness: true
          entity_1:
            entity_id: light.lounge_room_lights
            templates:
              - yellow_on
            tap_action:
              action: toggle
          entity_2:
            entity_id: climate.device_03
            templates:
              - green_off
            icon: mdi:thermometer
            tap_action:
              action: more-info

**Comment by tamet83** [comment]
I'm also interested in it, don't like some of the system default icon :)

**Comment by basbruss** [comment]
@prjcarr The current variables do not allow you to change the icons for the small buttons.
You can always change the icon assigned to the entity globally in home-assistant.

**Comment by prjcarr** [comment]
> You can always change the icon assigned to the entity globally in home-assistant.

Thankyou. This did exactly what I was after.

**Comment by tamet83** [comment]
Actually it didn't work for me. I created a group light:
![image](https://user-images.githubusercontent.com/7949570/192471395-08bf4a4a-57bb-4509-882e-dcd5bd87dd63.png)

But I still continue to see the old icon:
![image](https://user-images.githubusercontent.com/7949570/192471515-03169883-04e0-4370-af22-da471c4952e6.png)

**Comment by basbruss** [comment]
@tamet83 You are referring to another card than the OP.
The card used by OP: https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_room/

The card you refer to is built differently as it is a custom card: https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_esh_room/
The icons in that card are hardcoded and not set based on an entity attribute or variable

**Comment by tamet83** [comment]
> @tamet83 You are referring to another card than the OP. The card used by OP: https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_room/
> 
> The card you refer to is built differently as it is a custom card: https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_esh_room/ The icons in that card are hardcoded and not set based on an entity attribute or variable

Yes sorry, I misunderstood the card type. My bad
