### ISSUE TITLE
Custom Card "Room" - Change sub icon

### ISSUE THREAD

**Issue by tamet83** [UI-Lovelace-Minimalist/UI#1023]
Hi,

is it possible add the option to change the secondary icon to a custom one? I'm referring to this one:

![image](https://user-images.githubusercontent.com/7949570/192474666-299ada9a-968b-4ced-85e2-2e3b2693559f.png)

I could edit the card template manually, but my changes are overwritten each time.

**Comment by kdober** [comment]
I'm setting my dashboard and I got the same request. I think I manage to add it.
There is a pull request with the card modification
https://github.com/UI-Lovelace-Minimalist/UI/pull/1078
