### ISSUE TITLE
Thermostat popup does not handle mixed case preset modes

### ISSUE THREAD

**Issue by jkfranks9** [UI-Lovelace-Minimalist/UI#1033]
**Describe the bug**
When using the (undocumented) variable `ulm_card_thermostat_preset_mode` along with `ulm_card_thermostat_enable_popup`, the popup code in the `popup_thermostat_temperature template` does not account for mixed case preset modes. My ecobee thermostat uses modes "Away", "Home" and "Sleep" in the `preset_modes` attribute.

**To Reproduce**

1. Click and hold on the thermostat name in the card
2. Observe the popup has no preset mode buttons

**Expected behavior**
Thermostat popup should have buttons for the defined preset modes.

**Screenshots**
![image](https://user-images.githubusercontent.com/27896353/193308072-4b3f7a1d-43da-4f98-9df3-4dc1b0fd4fa7.png)

**Additional context**

**Comment by basbruss** [comment]
Hi @jkfranks9 

It should be able to handle your preset modes. It is working with my Tado-climate entity. Are you on release `v1.1.5-hotfix`?
Does the dev-console(f12) in chrome show some errors when you open the popup?

Also the variable is documented but only on the related popup page as it only applies to the popup 😉 
<img width="654" alt="image" src="https://user-images.githubusercontent.com/68892092/193318101-2908d35b-c6b8-4b0b-b74e-d9926353aa5c.png">

**Comment by jkfranks9** [comment]
Hi, thanks for the quick response. I've been dealing with power outages and other stuff, but I can confirm that I'm on `v1.1.5-hotfix`, and I do not see any error messages in chrome (or firefox).

I'll try to do some more troubleshooting as soon as I get a chance.

**Comment by jkfranks9** [comment]
I did a quick hack, replacing all instances of "away", "home" and "sleep" (full words only) with the leading character uppercase, and it worked as expected (the correct buttons appeared). 

I then tried to lowercase the actual preset mode attributes, but ran into problems. And since I detest javascript I didn't pursue that :) ... but to me that seems the obvious approach.

**Comment by basbruss** [comment]
Okay, so the list provided by your climate entity is not fully lowercase? Can you show us a screenshot of the attributes of your climate entity on the dev-tools page? Than I can add some logic to the JavaScript code.

**Comment by jkfranks9** [comment]
Yes, mixed case:

![image](https://user-images.githubusercontent.com/27896353/193598409-90a4b567-0efd-43f4-b2e8-cce875209039.png)
