### ISSUE TITLE
Mdi:icon State Chip ignores device class when displaying state

### ISSUE THREAD

**Issue by mark1foley** [UI-Lovelace-Minimalist/UI#1040]
I am trying to use the Mdi:icon State Chip to show the state of window and door sensors.  The chip works fine except that it only displays the state as 'on' or 'off' rather than displaying the appropriate device class state, i.e. 'Open' or 'Closed' for an entity with a device class of 'Window' or 'Door'.

Is there a way to get the chip to display the state for the device class?

**Comment by wilbiev** [comment]
Cleaning up issue list
