### ISSUE TITLE
Person card disappear when state is other than home (since version 1.1.5)

### ISSUE THREAD

**Issue by freddanastrom** [UI-Lovelace-Minimalist/UI#1043]
**Describe the bug**
Entire person card disappear when person state is other than home

**To Reproduce**
1. Add person card
2. Person state is changed to not_home
3. Person card disappears

**Expected behavior**
Person card should still be visible and show that person isn´t home.

**Screenshots**
Both persons home
![both_home](https://user-images.githubusercontent.com/31804858/195038990-d7b3c270-6ef3-4d16-9a86-fce7e483db5f.jpg)

I'm not home, entire card dissappears
![im_not_home](https://user-images.githubusercontent.com/31804858/195039305-e967a64b-8a7f-473d-9d24-d4f89103d0f0.jpg)

**Additional context**
Replacing the code in file ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_person.yaml with version 1.1.4 solves the issue

**Comment by basbruss** [comment]
Hi @freddanastrom 

Can you give us some more info to debug it better?
How have you set up the card config? What variables have you defined?
And what error does the chrome dev-console show when the card does not show up?

**Comment by freddanastrom** [comment]
Hi @basbruss

This is my card configuration:

```
- type: 'custom:button-card'
  template: card_person
  entity: person.fredrik
  variables:
    ulm_card_person_entity: person.fredrik
    ulm_address: input_select.fredrik_location
```

When my person state is changed from home to not_home the console is flooded with this:

```
button-card.js?hacstag=146194325342:425 ButtonCardJSTemplateError: TypeError: Cannot read properties of undefined (reading 'includes') in 'if (states[variables.ulm_card_person_entity].state == 'home') {
      return '<ha-icon icon="mdi:h...'
    at Je.eval (eval at _evalTemplate (button-card.js?hacstag=146194325342:425:9295), <anonymous>:9:50)
    at Je._evalTemplate (button-card.js?hacstag=146194325342:425:9379)
    at Je._getTemplateOrValue (button-card.js?hacstag=146194325342:425:9964)
    at button-card.js?hacstag=146194325342:433:400
    at Array.forEach (<anonymous>)
    at Je._buildCustomFields (button-card.js?hacstag=146194325342:433:292)
    at Je._gridHtml (button-card.js?hacstag=146194325342:517:25)
    at Je._buttonContent (button-card.js?hacstag=146194325342:499:433)
    at Je._cardHtml (button-card.js?hacstag=146194325342:479:18)
    at Je.render (button-card.js?hacstag=146194325342:425:6916)
```

Let me know if you need anything else for further investigation.

**Comment by freddanastrom** [comment]
So, after some own investigation i realized the issue actually starts with my zones.

I use HACS integration "Icloud3" for presence detection and that integration has created two zones for our phones.
Compared to my manually created zones, those two zones are passive and does not have the "persons" attribute at all.
I guess the missing persons attribute in the zone is what´s causing my errors.
They also have state "zoning" instead of an number, this is probably not relevant, but i haven't noticed it until now and I don't know what it means..

If the missing person attribute is normal for zones, maybe it should be fixed in the person card?
But if the persons attribute always should exist in zones, the problem is actually in the Icloud3 integration..



My home zone for example:
```
zone.home
state: 2

--attributes--
latitude: ***
longitude: ***
radius: 100
passive: false
persons:
  - person.fredrik
  - person.***
editable: true
icon: mdi:home
friendly_name: Hemma
```

Icloud3 integration zone
```
zone.fredriks_iphone_stationary
state: zoning

--attributes--
name: fredriks_iphone_stationary
latitude: ***
longitude: ***
icon: mdi:alpha-f-box
friendly_name: fredriks_iphone_stationary
passive: true
radius: 1
```

**Comment by freddanastrom** [comment]
Sorry for spamming this issue with comments..

Whether the problem is related to Minimalist or Icloud3.
According to HA documentation passive zones are only to be used for automations and be hidden in the frontend.

> https://www.home-assistant.io/integrations/zone/#passive
> passive boolean (optional, default: false)
> To only use the zone for automation and hide it from the frontend and not use the zone for device tracker name

So, the zone loop in the person card should probably exclude all passive zones?

**Comment by basbruss** [comment]
> Sorry for spamming this issue with comments..

No need to be sorry. It's useful information to build upon. 
As I see it we can definitely update the logic of Minimalist to filter out passive zones.
The weird thing is that the [code](https://github.com/UI-Lovelace-Minimalist/UI/blob/main/custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_person.yaml#:~:text=if%20(states%5Bst%5D%3F.attributes%3F.persons.includes(variables.ulm_card_person_entity))) already should evaluate if a person attribute is existing with help of optional chaining.



> So, the zone loop in the person card should probably exclude all passive zones?

This should be easily done by adding a second condition to the above-linked code line.
```java
if (states[st]?.attributes?.persons.includes(variables.ulm_card_person_entity && !states[st]?.attributes?.passive)) `
```

**Comment by freddanastrom** [comment]
I did some more testing and since that line of code still wants to fetch the persons attribute it ends up with the same error.
Either I had to wrap it in another if statement
```
if (!states[st]?.attributes?.passive))
    if (states[st]?.attributes?.persons.includes(variables.ulm_card_person_entity))
```

Or also make the persons attribute optional
```
if (states[st]?.attributes?.persons?.includes(variables.ulm_card_person_entity && !states[st]?.attributes?.passive))
```

Both seems to work, but I ended up using the last option and created pull request #1046
(first time for me to make changes on other projects than my own private ones, so i hope i did it correct)
