### ISSUE TITLE
Sporadic "custom element doesn't exist: grid-layout" errors

### ISSUE THREAD

**Issue by mneuhaus** [UI-Lovelace-Minimalist/UI#1047]
Ok, i'm really fully lost at this point.
i'm trying to set up lovelace minimalist and in theory i've got it running but, sometimes it doesn't work when i try to open it with a browser and get the error: "custom element doesn't exist: grid-layout".
If i reload the page a few seconds later it works and i get the same error if i try to open the dashboard on the android app or if i try to cast that dashboard to a google hub.
I've installed everything through HACS.
I even tried a complete fresh home assistant installation and went through the install guide from scratch, ended up in the exact same behavior.

Any idea what else i could try or how i could debug this?

![YaMMsfkk27wfouNeELhKPhWj](https://user-images.githubusercontent.com/316605/195159925-4a86da31-bc82-407d-88b2-47193bf027aa.png)
![image](https://user-images.githubusercontent.com/316605/195160047-04d5d36d-94b2-439a-aad9-c29fa9966f1d.png)
![SthJ6T3veB42gHr4KwpClLpr](https://user-images.githubusercontent.com/316605/195160768-c925b836-a07b-4d65-b075-16480cadb285.png)

**Comment by mneuhaus** [comment]
Some more information from various tests i did:

- limiting network speed to slow 3G and CPU to x6 slowdown in Chrome Developer tools does not produce this issue
- using the local IP address in the android app instead of Nabu Casa works most of the time, using the Nabu Casa URI always shows that error
- using a fresh chrome inkognito window produces the problem, which persists when doing a normal reload, but if i do a force reload with shift it works, doing a regular reload again produces that exact same problem

This issue really perplexes me, it really smells like some kind of race condition of parallel loading/initialising modules, that in a certain "order" produce this error.

**Comment by basbruss** [comment]
@mneuhaus The problem as you describe it is most likely related to the cloud service nabu casa uses. Their cache can be different than on your local system. Sadly I dont have a direct solution for it.

**Comment by mneuhaus** [comment]
that may be **one** factor, yes, **but** it also happens sporadically using the local network as well

**Comment by mneuhaus** [comment]
I tried to look into the code itself a little bit as well, as far as i understand, there is already stuff in the core, that "should" work around race conditions of custom cards already by showing that "Custom element doesn't exist: " content, but replace it when that tag/module is loaded:

https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/create-element/create-element-base.ts#L103-L119

**Comment by klaaspieter** [comment]
Pretty much the same as @focalfury. I just set it all up and seeing the exact same.

**Comment by ayourk** [comment]
My solution was to add all of the different resources to `Settings` -> `Dashboards` --> 3 dots stacked on top of each other in top right corner -> `Resources` and then proceed to add in all of the FrontEnd HACS resources to here.  For example, for the `button-card` Frontend, add `/hacsfiles/button-card/button-card.js` to the list of JavaScript modules.

**Comment by fjeddy** [comment]
If you are using the "Include custom card resources it's depending on." option, then that is where the problem lies, with how they are including all the cards (I'm guessing).

Simply disable that option and install all the resources manually and the problem completely vanishes.

PS: It has nothing to do with cloud or remote access, this happens locally as well as remotely.

**Comment by JHBoricua** [comment]
@fjeddy That's not it. I installed all resources manually and didn't check on the option you mentioned and I'm still getting the same error msg as the OP on a fresh HA install.

**Comment by JHBoricua** [comment]
The list of lovelace resources shown on the prerequisites/installation pages at https://ui-lovelace-minimalist.github.io/UI/setup/download/ is incomplete:
![image](https://user-images.githubusercontent.com/20731661/206966748-59aff1ea-17ba-4659-8f79-8b088658ea5c.png)

You'll also need  these three lovelace resources:

simple-weather-card
layout-card
state-switch

**Comment by BlueskyFR** [comment]
Which versions does this affect?

**Comment by mmaas70** [comment]
> The list of lovelace resources shown on the prerequisites/installation pages at https://ui-lovelace-minimalist.github.io/UI/setup/download/ is incomplete: ![image](https://user-images.githubusercontent.com/20731661/206966748-59aff1ea-17ba-4659-8f79-8b088658ea5c.png)
> 
> You'll also need these three lovelace resources:
> 
> simple-weather-card layout-card state-switch

This fixed the problem for me.

**Comment by ascandroli** [comment]
as @mmaas70 installing these 3 manually fixed the issue for me. Starting from scratch, I used the "Include custom card resources it's depending on." option but then I needed to manually install `layout-card`, `state-switch` and `simple-weather-card` to make it work.

**Comment by dreamonhigh** [comment]
`as @mmaas70, manually installing these 3 fixed the issue for me. Starting from scratch, I used the "Include custom card resources it's depending on." option but then I needed to manually install layout-card, state-switch and simple-weather-card to make it work.`

having same issue.
how can I install it manually ?

**Comment by curtisbarnard** [comment]
@dreamonhigh Go into HACS > Frontend > Explore & Download Repositories and then search for them. Click Download to install.

**Comment by TheS1ngularity** [comment]
> layout-card

This solved the issue for me, particularly the layout-card one. 
Thanks!
