### ISSUE TITLE
UI lovelace minimalist dashboard loading slow

### ISSUE THREAD

**Issue by koen241** [UI-Lovelace-Minimalist/UI#1049]
Hi all, when I open my HA app it takes a brief moment to load the dashboard. Especially if I go to another UI lovelace minimalist dashboard page that has many cards, it loads from top to bottom, but not so fast. It is so slow that it is quiet annoying. Once the page is loaded and I go back to a previous loaded dashboard page in the same session, it is immediately there. Closing the app requires it to load again.

I was wondering if other people are also experiencing this? I recently upgraded from a RP2 to Odroid N2+, so I hoped that with the faster server loading would be faster, but it is not...

I experience this on all devices and browsers.

This is how it looks like:
![ezgif-5-2dc7bc113d](https://user-images.githubusercontent.com/93862966/195630156-fd469cf1-05f9-4b06-9d0a-3c3bf330dc46.gif)

**Comment by parowa92** [comment]
Same, fresh install at intel nuci5.

**Comment by xairoo** [comment]
I removed this theme because of that, it's really annoying and takes too much time.

@koen241 why do have you closed this issue? How do you fixed it, if...?

**Comment by pafnow** [comment]
Same problem here, was working fine and started to be really slow since few days.

Standard Dashboard of HA are ok.
