### ISSUE TITLE
Battery state 'colors' not working

### ISSUE THREAD

**Issue by schorrie** [UI-Lovelace-Minimalist/UI#1051]
I have a ui lovelace minimalist dashboard but my icons don't change color. 
Battery level of my phone is now 28 but the icon isn't changing.
Don't know what's wrong

          - type: 'custom:button-card'
            template: card_battery
            variables:
              ulm_card_battery_percent: battery_percent
              ulm_card_battery_battery_level_danger: 35
              ulm_card_battery_battery_level_warning: 80
              ulm_card_battery_color_battery_level_danger: "var(--google-red)"
              ulm_card_battery_color_battery_level_warning: "var(--google-yellow)"
              ulm_card_battery_color_battery_level_ok: "var(--google-green)"
            entity: sensor.ne2213_battery_level

**Comment by basbruss** [comment]
Hi @schorrie 

I've tested the card with how you have set the variables. The colors do change in my setup.
Any chance the theme is not correctly set?
Can you provide a screenshot?

**Comment by schorrie** [comment]
Hi BassBruss

Thx for your comment
When viewing the theme,after reading your comment, my theme view wasn't right
I had to set the minimalist theme in my profile section

Thx for the hint ,I'm relative new to home assistant
