### ISSUE TITLE
How to change icon in custom_card_bar_card?

### ISSUE THREAD

**Issue by sc4920** [UI-Lovelace-Minimalist/UI#1052]
How to change icon in custom_card_bar_card?

**Comment by shogun160** [comment]
For now there is no option to change the icon. You'd need to change the code and make a PR. 
What you can do is change the icon of the entity globally which would also change the icon in the bar card.

**Comment by sc4920** [comment]
Change the icon of the entity globally is working!
Thanks!

**Comment by sc4920** [comment]
Another question
How to change the color of the progress bar according to the sensor state?
