### ISSUE TITLE
Triggers_update on template not work

### ISSUE THREAD

**Issue by Drealine** [UI-Lovelace-Minimalist/UI#106]
**Describe the bug**
Using triggers_update on card template with variables not work.

**To Reproduce**

Using a variable and try to refresh, the card not show the new value using template.
To work, I need to set triggers_update at the top level of configuration like this : 

![image](https://user-images.githubusercontent.com/61891683/146670998-75f2d0c9-1661-4911-80a3-8dd7650c2ae2.png)

Others card on Minimalist not work also.

**Comment by CM000n** [comment]
Yes, this is already known and has been fixed for the integrated Card with the last release. 
Please use `triggers_update: "all"`.
