### ISSUE TITLE
card_thermostat popup gives error

### ISSUE THREAD

**Issue by wokkeltje13** [UI-Lovelace-Minimalist/UI#1069]
Version 1.1.6
The popop is no longer working anymore for the thermostat card. Revert back to 1.1.5-hotfix does not solve the issue

My config:
  - type: "custom:button-card"
    template: card_thermostat
    entity: climate.bureau
    variables:
      ulm_card_thermostat_enable_collapse: true
      ulm_card_thermostat_enable_controls: true
      ulm_card_thermostat_enable_hvac_modes: true
      ulm_card_thermostat_enable_popup: true
      ulm_card_thermostat_enable_background_color: true
      ulm_card_thermostat_enable_display_temperature: true

The error:
ButtonCardJSTemplateError: TypeError: entity.attributes.hvac_modes.toLowerCase is not a function in 'var areas = []; if (variables.ulm_card_thermostat_preset_mode){ if (entity.attribute...'

Attributes of climate.bureau:
hvac_modes: fan_only, dry, cool, heat, heat_cool, off
min_temp: 7
max_temp: 35
target_temp_step: 1
fan_modes: Auto, Silence, 1, 2, 3, 4, 5
preset_modes: none, away, eco, boost
swing_modes: Off, Vertical, Horizontal, 3D
friendly_name: Bureau
supported_features: 57
current_temperature: 22
temperature: 18
fan_mode: Auto
hvac_action: heating
preset_mode: none
swing_mode: Off

Anyone has an idea what I am missing? a couple of days ago this was working correct.

**Comment by basbruss** [comment]
Hotfix to address this issue is just released 😄
