### ISSUE TITLE
PR  #1037 [Chip Mdi Icon State]  enhancement didn't get merged

### ISSUE THREAD

**Issue by shogun160** [UI-Lovelace-Minimalist/UI#1073]
It look like PR #1037 didn't get merged.
I double checked the repo and it looks like the changes didn't get merged in v1.1.6. Probably because I messed some things up with PR #1055.
@basbruss / @schumijo:  Should I reopen or make a new PR or can you merge the change again for the next version?

**Comment by basbruss** [comment]
@shogun160 I have added it manually, will be available on HACS it the next release.
