### ISSUE TITLE
Border around cards after update to core 2022.11.0

### ISSUE THREAD

**Issue by koen241** [UI-Lovelace-Minimalist/UI#1074]
**Describe the bug**
Since the update of HA core from 2022.10.5 to 2022.11.0 these weird borders have shown up in my lovelace. The borders are there for every theme that I select in my profile. Both in the HA app and in browser.

**Screenshots**
![Schermafbeelding 2022-11-03 110604](https://user-images.githubusercontent.com/93862966/199693878-96284052-b1e9-4f12-a17b-a9192c63c90a.png)

**Additional context**
Anybody with the same problem? Or an idea of where this might come from?

**Comment by basbruss** [comment]
@koen241 Update to version v1.1.6
Fix is already in place 😉  see commit https://github.com/UI-Lovelace-Minimalist/UI/commit/b1033fd4e13b1d27943b14f4cc9838059605e4e8
Please make also sure to refresh/delete all caches and maybe restart HA an additional time.

**Comment by koen241** [comment]
Thanks, that did the trick. Didn't think about checking the Minimalist update!
