### ISSUE TITLE
After last update: "button-card template is missing" on all cards.

### ISSUE THREAD

**Issue by TizianoVecellio** [UI-Lovelace-Minimalist/UI#1075]
After the most recent update, none of my cards are rendering and displaying the "button-card template is missing" error message.

![image](https://user-images.githubusercontent.com/20685337/199717153-2af23edc-1dba-4f9b-8e9c-b2c51b94b061.png)

**Comment by Marck** [comment]
I would suggest checking if the button_card_templates variable is pointing to correct folders
