### ISSUE TITLE
Theme: opacity on wrong state?

### ISSUE THREAD

**Issue by Klex1404** [UI-Lovelace-Minimalist/UI#109]
Could it be that the "Set opacity-bg to 0.1 in light themes" chanhe is applied to the wrong state condition?
Now for a card in an off condition it becomes white and in an on condition it becomes transparent.
I would expect it the otherway around?
Thanks!

**Comment by CM000n** [comment]
Damn! You're absolutely right.  I must have had a problem with the cache when testing. I will publish a hotfix for this
