### ISSUE TITLE
PermissionError on installation

### ISSUE THREAD

**Issue by SteadyStatus21** [UI-Lovelace-Minimalist/UI#1090]
**Describe the bug**
After installation, the logs show that the UI was never activated. Opening the logs, it shows that there was a permission denied. 

**To Reproduce**
Install. Reboot. Get warning. 

**Expected behavior**
No errors after installation. 
**Screenshots**
![image](https://user-images.githubusercontent.com/73841304/201168209-cad17929-c543-4c6f-8133-e0bd3b2b4879.png)

**Additional context**
```
This error originated from a custom integration.

Logger: custom_components.ui_lovelace_minimalist.base
Source: custom_components/ui_lovelace_minimalist/base.py:515
Integration: UI Lovelace Minimalist (documentation, issues)
First occurred: 12:35:51 PM (1 occurrences)
Last logged: 12:35:51 PM

[Errno 13] Permission denied: '/home/homeassistant/homeassistant/custom_components/ui_lovelace_minimalist/__ui_minimalist__'
```

**Comment by basbruss** [comment]
@SteadyStatus21 This could be related to #998

**Comment by SteadyStatus21** [comment]
Ah, it was! Thank you @basbruss! I just had to update the plugin.
