### ISSUE TITLE
custom_card_esh_welcome visual bug

### ISSUE THREAD

**Issue by Marck** [UI-Lovelace-Minimalist/UI#1092]
On my dashboard and at the newest version of the card and HASS there are more overlay lines then there where before
This behavior was not there before on older versions of minimalist. This occurs on v 1.15-hotfix

![Screenshot 2022-11-14 at 08 29 46](https://user-images.githubusercontent.com/18088281/201600448-06839730-8bd3-4cd4-9314-8acee538c8ef.png)

**Comment by basbruss** [comment]
Please update to v1.1.6 or higher HA-core introduced some design elements conflicting with the minimalist design

**Comment by Marck** [comment]
I am on release 1.1.6-hotfix of minimalist. I removed the integration and re-downloaded it through hacs (just in case). Maybe a beta version where this is fixed? 

I also made sure to have the latest version of the esh_welcome card but sadly still have the same issue

**Comment by Marck** [comment]
That fixes the issue, thanks!
