### ISSUE TITLE
custom_card_esh_welcome displays the wrong language when there is more then one translation file present in the Minimalist folder

### ISSUE THREAD

**Issue by Marck** [UI-Lovelace-Minimalist/UI#1094]
The custom_card_esh_welcome displays only morning, evening, afternoon greetings from the TR language yaml (I think it's turkish) and doesn't change while it should change.

Is there a missing settings or something? I could not find anything in the docs

**Comment by Marck** [comment]
For reference
<img width="509" alt="image" src="https://user-images.githubusercontent.com/18088281/202790150-554d150f-a998-4088-9386-6835d2fb6b83.png">

**Comment by xm4rcell0x** [comment]
Have you changed your language settings in "Integrations"? 
There's an option to select your language. 
![image](https://user-images.githubusercontent.com/17478462/206937393-38638422-736c-430e-81d2-7877caf344de.jpeg)

**Comment by Marck** [comment]
Yes, It's at GB but that doesn't change a thing sadly
<img width="389" alt="image" src="https://user-images.githubusercontent.com/18088281/207016847-8610790e-defb-4798-9fb0-8518228824b3.png">

**Comment by Marck** [comment]
Closing this for I have a workaround
