### ISSUE TITLE
Git conflict markers

### ISSUE THREAD

**Issue by albinmedoc** [UI-Lovelace-Minimalist/UI#1099]
**Describe the bug**
There is conflict markers on the page. It makes it hard to use that card. 

**To Reproduce**

1. Go to '[custom_card_homeassistant_updates](https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_homeassistant_updates/?h=update#requirement-collapse-function)'
2. See conflict markers

**Expected behavior**
No conflict markers

**Screenshots**
<img width="974" src="https://user-images.githubusercontent.com/7331299/203636198-d5dcd1f3-bacd-4b75-b029-99a2b8424f79.png">
<img width="332" src="https://user-images.githubusercontent.com/7331299/203636211-c4ec2522-f3ed-43fb-be44-f74a7c06f2c3.png">

**Additional context**
Section "Template sensor code" should be code snippet
<img width="938" src="https://user-images.githubusercontent.com/7331299/203636586-44c5c86d-4240-4299-97bb-9daa4e4887f5.png">

**Comment by wilbiev** [comment]
Cleaning up issue list
