### ISSUE TITLE
Chips template icon not colored on desktop browsers

### ISSUE THREAD

**Issue by Klex1404** [UI-Lovelace-Minimalist/UI#110]
In desktop browsers (chrome/edge etc) the icon on the chips template are not colored.
I believe this can be solved by changing the label style:
font-weight: bold
to
font-weight: 500

**Comment by CM000n** [comment]
Nice finding!
There is also a bug report open on Chromium (which is the underlying browser engine for chrome and edge):
https://bugs.chromium.org/p/chromium/issues/detail?id=1266022
But maybe reducing the font-weight is a good aproach till they fixed it.

**Comment by Klex1404** [comment]
Thanks for the witch action Simon.
Also many thanks for picking up this repo and improving this magnificent theme!
