### ISSUE TITLE
Battery Level Info Card change size

### ISSUE THREAD

**Issue by NeoFax75** [UI-Lovelace-Minimalist/UI#1101]
**Is your feature request related to a problem? Please describe.**
It is very hard to read this battery level on a phone or 1080p+ screen

**Describe the solution you'd like**
Ability to add a ulm_* style variable that allows the creator to set the circle and font size.  It would also be nice to change the color of the circular gauge based on battery level like the battery card.

**Describe alternatives you've considered**
Card mod

**Comment by wilbiev** [comment]
Cleaning up issue list
