### ISSUE TITLE
Light popup temperature slider has no handle. 

### ISSUE THREAD

**Issue by Budget-Seat** [UI-Lovelace-Minimalist/UI#1108]
**Describe the bug**
When i open the light popup there is no handle/ indicator for the temperature slider. It works but does not display where it is set right now. Sometimes the handle also disapears on the brightness slider but it is not so problematic as you can see in the screenshot

**To Reproduce**
Open popup and use temperature slider

**Expected behavior**
Show handle just like brightness slider.
With handle on brightness. 
<img width="950" alt="Screenshot 2022-12-01 at 10 56 01" src="https://user-images.githubusercontent.com/59611615/205023459-0fbeca60-9078-4ea4-8e8c-a4023b80d68d.png">

Without handle on brightness.
<img width="990" alt="Screenshot 2022-12-01 at 10 55 32" src="https://user-images.githubusercontent.com/59611615/205023721-f78eabd3-0200-4c18-b45f-bf49e09f332e.png">

**Comment by xm4rcell0x** [comment]
Second this. It's so uncomfortable to change color temperature.

**Comment by wilbiev** [comment]
Cleaning up issue list
