### ISSUE TITLE
Media Player with controls don't work with Plex

### ISSUE THREAD

**Issue by Simonv92** [UI-Lovelace-Minimalist/UI#1109]
**Describe the bug**
I was able to control Plex with previous release of the UI. After some update I'm unable to control play, pause, ecc of my media player.
I've modified the config to the latest release using Media Player Card (with controls) but it doesnt't work

Here is my config:
`          - type: 'custom:button-card'
            template: 
              - card_media_player_with_controls
            variables:
              ulm_card_media_player_with_controls_name: "Livingroom Shield"
              ulm_card_media_player_with_controls_entity: media_player.plex_plex_for_windows_desktop_simone`

What I'm doing wrong?
Thank you!
Simone

**Comment by wilbiev** [comment]
Cleaning up issue list
