### ISSUE TITLE
Person Card - Not Displaying ETA Information

### ISSUE THREAD

**Issue by Boh1** [UI-Lovelace-Minimalist/UI#1110]
I have an issue where the Minimalist Person Card is not displaying the ETA information, and only shows the text "undefined".

I'm sourcing the ETA information from a sensor exposed by the Google Maps Travel Time integration in HA . The relevant part of my  my card config looks this:

`  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        template: card_person
        variables:
          ulm_card_person_entity: person.john
          ulm_card_person_use_entity_picture: true
          ulm_card_person_zone1: zone.work
          ulm_card_person_zone2: zone.home
          ulm_card_person_eta: sensor.time_to_work_john
          
          ...`

The sensor displays just fine in other Lovelace dashboards, just not in Minimalist. (Version 1.1.6)

My configuration _appears_ to match what's in the Wiki for this card, but am I missing something else?

**Comment by basbruss** [comment]
> My configuration _appears_ to match what's in the Wiki for this card, but am I missing something else?

@Boh1 Not entirely.  You are missing the entity line that is need to load in far more attributes than the entity in the variables can do.
```yaml
- type: 'custom:button-card'
  template: card_person
  entity: person.john
```
