### ISSUE TITLE
Right-side popups not working correctly on Adaptive Dash

### ISSUE THREAD

**Issue by DanyL28** [UI-Lovelace-Minimalist/UI#1111]
Hello there!
I configured my Adative Dashboard according to the [documentation](https://ui-lovelace-minimalist.github.io/UI/setup/adaptive_dash/). I'm not sure I made any mistake, but I would like to search for some help here. I've installed the `state-switch` and the `layout-card`, set up the `input_select` and the corresponding `options` as well as the cards, and the correct configuration under `popup.yaml`. What happens is that the popup effectively appears, but it only appears during the `transition: slide-down`. After the transition stops, the popup disappears. I've tried set the `transition` to `none`, and it works fine, but not with the transition activated. Any ideas or suggestions as to why this happens?

**Comment by basbruss** [comment]
Please verify if you are using `state-switch` version `1.9.3`. As this behavior is directly the cause we recommend 1.9.3 or lower

**Comment by DanyL28** [comment]
Thanks for your help. I didn't notice that on the documentation!

**Comment by DanyL28** [comment]
Thanks a lot for your help! I didn't notice it on the documentation. Cheers!
