### ISSUE TITLE
Improve documentation for custom_card_imswel_person

### ISSUE THREAD

**Issue by rst-ack** [UI-Lovelace-Minimalist/UI#1112]
**Is your enhancement request related to a problem? Please describe.**
The documentation for [custom_card_imswel_person](https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_imswel_person/) is seemingly missing details or examples for the `ulm_card_imswel_person_findmy_script`, `ulm_card_imswel_person_gps_tracker`, and `ulm_card_imswel_person_wifi_tracker` variables.

**Describe the solution you'd like**
The examples in the variables table show example entities to use for the variables, however, in particular for the `ulm_card_imswel_person_findmy_script` variable, I think it would be helpful to provide a link (in the Explanation column) to somewhere that can guide the user on creating a script to make the phone ring. Being able to do this might be assumed knowledge to use ULM, but if this is the case I feel it might be worth calling it out.

**Comment by wilbiev** [comment]
Cleaning up issue list
