### ISSUE TITLE
Popup_light doesn't change color temperature

### ISSUE THREAD

**Issue by xm4rcell0x** [UI-Lovelace-Minimalist/UI#1119]
**Describe the bug**
When i open the popup_light of an rgbw bulb (in my case an Ledvance Smart+ RGBW zigbee) and i change the color, after that i cannot go back to the white light. 
That's an issue that i can reproduce with android and apple devices
With other light cards, such as mushroom's one i can change color and temperature with no problem (obviusly without a popup)

**To Reproduce**

1. Hold tap on a RGBW light to open the popup_light
2. First change the color to an rgb one
3. Try to change color temperature

**Expected behavior**
I expect to change color temperature after an rgb color change with popup_light

**Additional context**

[video](https://drive.google.com/drive/folders/18ZN_ahu3Ilbbu9YNYcpTf8t16X5lrucQ)

**Comment by V4n1X** [comment]
Can confirm this bug.

**Comment by derbohmann** [comment]
Can confirm this bug as well. Also exists in Firefox for MacOS. So no mobile specific issue.

**Comment by Pixelpaule** [comment]
Can confirm this bug too.

**Comment by Sim0cYz** [comment]
I confirm this problem too

**Comment by xm4rcell0x** [comment]
i don't know who can fix this bug, but maybe can merge this issue with the #1108 ?

**Comment by MaximeGrison** [comment]
Confirm it too

**Comment by Sanch0ous** [comment]
Can confirm it too

**Comment by xm4rcell0x** [comment]
Some dev can fix this issue please? 🙏

**Comment by basbruss** [comment]
https://github.com/AnthonMS/my-cards/issues/33

**Comment by jonrupell** [comment]
I have the same issue. Hoping this gets fixed soon. Looks like its been a problem for a while now.

**Comment by xm4rcell0x** [comment]
Any news?

**Comment by JayReturns** [comment]
> Any news?

After it broke I got back to using the default home assistant popups which got quite an update a couple of months ago. They're actually pretty nice now. The Minimalist popup works for my color temperature now yet it still doesn't show a slider for me. The default ones work so great for me that i completely forgot about this issue.

I'm using HA 2023.8.3 with Minimalist v1.3.6

**Comment by wilbiev** [comment]
Clean-up old issues from the list. Let me know when this issue needs to be re-opened.
