### ISSUE TITLE
Improve card_person documentation 

### ISSUE THREAD

**Issue by xm4rcell0x** [UI-Lovelace-Minimalist/UI#1120]
**Is your enhancement request related to a problem? Please describe.**
Not related to a problem, i'd like to update the minimalist's wiki with [this feature](https://github.com/UI-Lovelace-Minimalist/UI/discussions/1017) for the card_person. I think it's a bit tricky to find for every person who want to accomplish this result.

**Comment by wilbiev** [comment]
Clean-up old issues from the list. Let me know when this issue needs to be re-opened.
