### ISSUE TITLE
Generic Card Swap variables don't work with Sensor Template

### ISSUE THREAD

**Issue by 33espressooo** [UI-Lovelace-Minimalist/UI#1121]
**Describe the bug**
Generic Card Swap name and icon variables don't work with the new template sensors defined in HA documentation but is fine with the legacy platform template sensors. 

TEMPLATE SENSOR - doesn't obey variables for name or icon
template:
  - sensor:
      - name: "some_sensor"
      - 
LEGACY PLATFORM TEMPLATE - variables work as expected
sensor:
  - platform: template
    sensors:
      some_sensor

**Expected behavior**
ulm_card_generic_swap_name and ulm_card_generic_swap_icon ignored and uses sensor name and an "eye" icon instead of the ones defined in the variables

**Comment by wilbiev** [comment]
Clean-up old issues from the list. Let me know when this issue needs to be re-opened.
