### ISSUE TITLE
Speedtest Custom Card Custom Translations Wiki Update

### ISSUE THREAD

**Issue by anthonymonti2** [UI-Lovelace-Minimalist/UI#1125]
I was trying to add the custom card speedtest to my dashboard and no matter how well I followed the setup on the [wiki](https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_irmajavi_speedtest/) the card would report that it could not find "ulm_custom_card_irmajavi_speedtest_language_variables". From looking at the authors commits they added an extra file that isn't mentioned in the wiki.

The documentation for the Speedtest custom card is out of date and need the following edits to make it work. The author of the code added custom translations for the button text. To make the custom card work a new folder, with the name "languages", is needed inside the custom card folder. Then inside the folder a yaml file the with the translations are needed.

My file structure is the following

custom_card_irmajavi_speedtest
|--- custom_card_irmajavi_speedtest.yaml
|--- languages
       |--- en.yaml

All of this was figured out from the authors commit at [22046cceab7ca51091e050fe468a29d444c55ce7](https://github.com/UI-Lovelace-Minimalist/UI/commit/22046cceab7ca51091e050fe468a29d444c55ce7)

**Comment by wilbiev** [comment]
See https://github.com/UI-Lovelace-Minimalist/UI/tree/main/custom_cards/custom_card_irmajavi_speedtest for full version including language files
