### ISSUE TITLE
Emoji won't work on chip_icon_label despite documentation showing emoji

### ISSUE THREAD

**Issue by rogersmj** [UI-Lovelace-Minimalist/UI#1126]
**Describe the bug**
See https://ui-lovelace-minimalist.github.io/UI/usage/chips/chip_icon_label/#usage. Documentation screenshot shows a full color emoji (as do many examples of people's dashboards), but the description says it uses MDI and attempting to use an emoji as the label doesn't work:

![image](https://user-images.githubusercontent.com/20134/209356775-5d50ace7-fb29-4449-8416-01e8f16f11c0.png)

Results in:
![image](https://user-images.githubusercontent.com/20134/209356790-9058073f-f995-4bbb-82f7-f624beb231dc.png)

**To Reproduce**
Configure a chip card as shown in above screenshot using emoji from [here](https://github.com/ikatyang/emoji-cheat-sheet#animals--nature). Observe no emoji in UI. FireFox on Mac OS.

**Expected behavior**
Expected to show the emoji included in the config as a label.

**Screenshots**
See above.

**Additional context**
I searched and saw lots of threads asking for mdi support to be added...which is the opposite of what I'm experiencing here. The implication of the documentation screenshot (and other people's dashboards that I've seen) seems to be that emojis should work here, but they aren't. Are they expected to work?

**Comment by basbruss** [comment]
There is not icon grid in this chip like in the mdi:icon variants. To display the emoji you have to add it as string directly in the `label` part.
