### ISSUE TITLE
Purple / violet naming inconsistent

### ISSUE THREAD

**Issue by amosyuen** [UI-Lovelace-Minimalist/UI#1129]
**Describe the bug**
Color templates and `--google-violet` use `violet`, but then color variables use `purple` such as `--color-purple`. 

**Expected behavior**
They should use the same naming so that it's not confusing.
For backwards compatibility you could keep references to both.

**Comment by wilbiev** [comment]
Clean-up old issues from the list. Let me know when this issue needs to be re-opened.
