### ISSUE TITLE
Navigate Card various colors

### ISSUE THREAD

**Issue by sven41** [UI-Lovelace-Minimalist/UI#1130]
Please add various colors in the Navigate Card, now it is only blue

**Comment by benbur98** [comment]
Have made the changes. Please copy this YAML as a custom component to test with any colours you want and let me know of any issues.

**Comment by sven41** [comment]
I would like to help you, but I'm not sure how... Sorry, perhaps someone else can?

**Comment by weedpump** [comment]
The changes do not work because of a little typo. I've tested locally and created a PR.
