### ISSUE TITLE
weather-radar-card.js - 404 Error not Found

### ISSUE THREAD

**Issue by ingeniumdesign** [UI-Lovelace-Minimalist/UI#1150]
If i use the Weather Card i have a Frontend Error:

**Bug Report**
`GET https://example.com:18123/ui_lovelace_minimalist/cards/weather-radar-card/weather-radar-card.js net::ERR_ABORTED 404 (Not Found))`

The HACS Plugin is install:
https://github.com/makin-things/weather-radar-card/

```
- url: /hacsfiles/weather-radar-card/weather-radar-card.js
  type: module
```

For whatever reason, it looks for the file in the ui_lovelace_minimalist folder...

**Comment by r0m1CH** [comment]
Same issue here.

**Comment by ingeniumdesign** [comment]
i found the error. don´t install the plugins over hacs and put the checkbox on "Include custom card resources it's depending on.
"
if you install the plugins over hacs, so uncheck this part in the "configure" @r0m1CH

**Comment by r0m1CH** [comment]
All good thanks !
