### ISSUE TITLE
Browser Mod issues: wrong alignment, no sliders function

### ISSUE THREAD

**Issue by HenryKleinschmidt** [UI-Lovelace-Minimalist/UI#1155]
**Describe the bug**
Additionally to these reported  #1119,  #1108  I'm having trouble with Browser Mod in general I think.
The pop is not aligned properly and _none_ of the sliders work.

I've tested this on desktop in various browsers and on mobile (iOS) but it doesn't work correctly. 
The correct theme was applied on each device.

**Screenshots**
![IMG_1967 (Small)](https://user-images.githubusercontent.com/53699624/215461360-c980ae30-f68b-460c-80e9-0a747d2a32b0.PNG)
![IMG_1969 (Small)](https://user-images.githubusercontent.com/53699624/215461367-28ff9124-1a48-4bd2-b671-ecfcd67cc84d.PNG)

https://user-images.githubusercontent.com/53699624/215461468-0f1fe817-9dc5-460c-b03e-58f9983494db.mp4

**Additional context**

**Comment by AlexanderGlogger** [comment]
Can confirm the alignment problem. But the slider is working for me.

**Comment by VdwTom** [comment]
I have no alignment problem, but i can't move the slider from my light pop-up.
