### ISSUE TITLE
Safari does not render UI with all the styling

### ISSUE THREAD

**Issue by urosgruber** [UI-Lovelace-Minimalist/UI#1161]
**Describe the bug**
I'm first time user of this theme and not really sure if this is a result of a bug or something is misconfigured. But In Safari on the desktop some styling is missing (no colours, borders, shadows etc.) Screens attached are from Chrome and Safari.

**Expected behavior**
Both browsers should show more or less the same visuals.

**Screenshots**
![CleanShot 2023-02-06 at 08 01 21](https://user-images.githubusercontent.com/590455/216905725-ece8bebc-e4f5-4238-ad0b-4858c29da6bd.png)
![CleanShot 2023-02-06 at 08 01 14](https://user-images.githubusercontent.com/590455/216905735-77bcc9bd-c17d-48e3-8be2-b08783d4cfa5.png)

**Comment by basbruss** [comment]
In each browser/device you have to set the theme again in your user profile.

**Comment by urosgruber** [comment]
Oh damn, silly me. All is good now. Thanks @basbruss
