### ISSUE TITLE
Nothing works. No cards found. new install

### ISSUE THREAD

**Issue by kmanan** [UI-Lovelace-Minimalist/UI#1162]
Did a brand new HACS install and then got the integration. Nothing works. Here's what I get:

![image](https://user-images.githubusercontent.com/17659155/217656575-493e7965-64ca-452b-b44e-a5fb1a1d953a.png)

**Comment by Sammy1Am** [comment]
Same here; I have "Include Custom Card Resources" checked, but it doesn't seem to be working.  Where should I be seeing these downloaded to (to check and see if they're being downloaded at all)?
![image](https://user-images.githubusercontent.com/467704/219848149-0db61f5c-3606-4489-a91d-846df6499a0a.png)

**Comment by addelovein** [comment]
Same here. Tried EVERYTHING i can think of...followed all guides... Copied thos templates everywhere... Please somone respond....

**Comment by revolter** [comment]
I think that the new installer is broken, and doesn't automatically install all the required dependencies.

So, to fix it, you need to install [them](https://ui-lovelace-minimalist.github.io/UI/setup/download/#prerequisites_1) by following these steps:
- `Home Assistant`:
    + `HACS`:
        * `Integrations` > `+ EXPLORE & DOWNLOAD REPOSITORIES` (bottom right) > search "browser_mod" > `browser_mod` > `⬇️ DOWNLOAD` (bottom right) > `DOWNLOAD`
        * `Frontend`:
            - `⋮` (top right) > `Custom repositories` > set `Repository` to `https://github.com/AnthonMS/my-cards` > set `Category` to `Lovelace` > `ADD`
            - `My Cards Bundle` > `⬇️ DOWNLOAD` (bottom right) > `DOWNLOAD` > `CANCEL` ([source](https://github.com/AnthonMS/my-cards/issues/17#issuecomment-1045213931))
            - `+ EXPLORE & DOWNLOAD REPOSITORIES` (bottom right) > search "button-card" > `button-card` > `⬇️ DOWNLOAD` (bottom right) > `DOWNLOAD` > `CANCEL`
            - Repeat the last step by:
                + searching "lovelace-card-mod" and selecting `card-mod`
                + searching and selecting `mini-graph-card`
                + searching "mini-media-player" and selecting `Mini Media Player`
                + searching "light-entity-card" and selecting `Light Entity Card`
                + searching "lovelace-auto-entities" and selecting `auto-entities` > `RELOAD` (instead of `CANCEL`)
    + `Developer Tools` > `RESTART` (red) > `RESTART`

But, I think something is still missing 🤔

**Comment by GameTec-live** [comment]
I have the same issue here, new install of HASS 2023.3.6 in docker, tried both manualy installing the deps in HACS, let Minimalist deal with it, nothing is working...

**Comment by jorisvanr** [comment]
Any update on this by any chance? I'm having the same issue. I followed the steps mentioned by Revolter but also added the following (found these in another thread): 

- simple-weather-card
- layout-card
- state-switch

I also added the sources in ui-lovelace.yaml (not sure if this was a step that was needed, but every install popup mentioned something like this). The final list looked like this:

`resources:
  - url: /hacsfiles/button-card/button-card.js
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
  - url: /hacsfiles/l/mini-graph-card-bundle.js?v=0.11.0
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
  - url: /hacsfiles/light-entity-card/light-entity-card.js
  - url: /hacsfiles/my-cards/my-cards.js
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
  - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
  - url: /hacsfiles/lovelace-state-switch/state-switch.js
type: module
`

After this it worked! Yay! 

But then it didn't. The only thing I did was run a backup but nothing else. Am I missing something?

**Comment by GameTec-live** [comment]
> Best practice is to load the resources in the dashboard resources tab: [![Open your Home Assistant instance and show your dashboard resources.](https://camo.githubusercontent.com/b9a0d4c1fdd684179dbb216f01ae209bcb46567a97e0642063d8f40d996ba8c6/68747470733a2f2f6d792e686f6d652d617373697374616e742e696f2f6261646765732f6c6f76656c6163655f7265736f75726365732e737667)](https://my.home-assistant.io/redirect/lovelace_resources/)
> 
> Note that when HACS does not put the resources already there, it gives a warning like this ![Screen Shot 2023-04-04 at 14 20 36](https://user-images.githubusercontent.com/68892092/229790048-8c96be5a-a2b8-4f05-aa76-c8a1b2f026f4.png)

Thanks! this fixed it... what the hell is lovelace storage mode tho...

**Comment by smartypantsuk** [comment]
Just installed on a fresh HA OS and the same issue occurs.
The installer via HACS is definitely broken.

**Comment by GameTec-live** [comment]
> Just installed on a fresh HA OS and the same issue occurs.
> The installer via HACS is definitely broken.

ok, nope... its a lovelace thing. by default lovelace runs in storage mode, sou you have to add all of the resources manually on the resources page. theres also a way to get lovelace go out of storage mode (confiuguration.yaml, but i dont remember rn)... when installing the dependencys manually just make note of the url on each and add them in the hass resources view

**Comment by smartypantsuk** [comment]
> > Just installed on a fresh HA OS and the same issue occurs.
> > The installer via HACS is definitely broken.
> 
> ok, nope... its a lovelace thing. by default lovelace runs in storage mode, sou you have to add all of the resources manually on the resources page. theres also a way to get lovelace go out of storage mode (confiuguration.yaml, but i dont remember rn)... when installing the dependencys manually just make note of the url on each and add them in the hass resources view

Ok. Can you not put lovelace out of storage mode then run the installer in hacs?

**Comment by smartypantsuk** [comment]
![arrrggg](https://user-images.githubusercontent.com/58052383/230864825-b3bfd16d-7325-4d43-a408-c50570ccf542.jpg)

This is what I'm currently struggling with.
I've added all the resources I can see, I've refreshed browser cache and ui-lovelace-minimalist config numerous times along with restarting of HA. Sometimes I get more spinning circles, other times I get 3.

I don't have errors in logs.

**Comment by smartypantsuk** [comment]
> Ok, so, how do I (re)install this "theme"?

There doesn't seem to be a working process to install this following current guides.
If you're using configuration via UI something seems broken to me.
I've given up for now.

**Comment by revolter** [comment]
> Why do you think something is missing?

<img width="885" alt="image" src="https://user-images.githubusercontent.com/5748627/231090309-dff514d3-1c7e-43b1-8e55-4ab7245c4190.png">

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/5748627/231090354-5e693774-80b8-4423-9e5b-9235745f2b6c.png">

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/5748627/231090444-6e6558a5-ae97-43b9-a230-527258ffd09f.png">

**Comment by smartypantsuk** [comment]
> > Why do you think something is missing?
> 
> <img alt="image" width="885" src="https://user-images.githubusercontent.com/5748627/231090309-dff514d3-1c7e-43b1-8e55-4ab7245c4190.png">
> 
> <img alt="image" width="1031" src="https://user-images.githubusercontent.com/5748627/231090354-5e693774-80b8-4423-9e5b-9235745f2b6c.png">
> 
> <img alt="image" width="1299" src="https://user-images.githubusercontent.com/5748627/231090444-6e6558a5-ae97-43b9-a230-527258ffd09f.png">

Maybe that's right? Have you tried configuring cards? You got far more than I did,  mine won't load cards

**Comment by basbruss** [comment]
@revolter You will need also to set the theme in your user profile. Doing this automatically by the integration seems to be unreliable due to how HA processes theme selection in multiple places.

Note that you will need to repeat that process for each device/browser/app you use to display HA as the theme set in your user profile is saved in a cookie and not transferred between those.

**Comment by VoidWood** [comment]
The option for setting the minimalist theme is not available in the user profile settings.  How can I get it?
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/89903806/0198ac76-fbd2-4e18-9a8e-23fd550e3cf4)

**Comment by Vahn84** [comment]
To me something in the UI Minimalist Theme (or in its dependencies) is fundamentally broken. I've tried both installations (manual and through HACS) and the result is always a shitload of errors in my console 

`_getTemplateOrValue@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:437:2817
@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:437:2789
forEach@[native code]
_getTemplateOrValue@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:437:2754
@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:437:2789
forEach@[native code]
_getTemplateOrValue@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:437:2754
@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:437:2789
forEach@[native code]
_getTemplateOrValue@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:437:2754
@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:437:2789
forEach@[native code]
_getTemplateOrValue@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:437:2754
@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:437:2789
forEach@[native code]
_getTemplateOrValue@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:437:2754
@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:437:2789
forEach@[native code]
_getTemplateOrValue@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:437:2754
@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:445:409
forEach@[native code]
_buildCustomFields@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:445:299
_gridHtml@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:527:43
_cardHtml@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:489:32
render@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:429:19524
update@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:1:14824
performUpdate@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:1:6151
@http://192.168.1.20:8123/ui_lovelace_minimalist/cards/button-card/button-card.js:1:5714`

`Unhandled Promise Rejection: TypeError: e.setConfig is not a function. (In 'e.setConfig({type:"error",error:_t.toString(),origConfig:this._config})', 'e.setConfig' is undefined)`

`Error: Failed to execute 'define' on 'CustomElementRegistry': the name "my-slider" has already been used with this registry`

`Error: Failed to execute 'define' on 'CustomElementRegistry': the name "auto-entities-editor" has already been used with this registry`

`Error: Failed to execute 'define' on 'CustomElementRegistry': the name "masonry-layout" has already been used with this registry`

'Error: Failed to execute 'define' on 'CustomElementRegistry': the name "mini-graph-card" has already been used with this registry'

'Error: Failed to execute 'define' on 'CustomElementRegistry': the name "button-card-action-handler" has already been used with this registry'

`Unhandled Promise Rejection: TypeError: The superclass is not a constructor.`
