### ISSUE TITLE
Swipe navigation

### ISSUE THREAD

**Issue by albinmedoc** [UI-Lovelace-Minimalist/UI#1165]
**Is your enhancement request related to a problem? Please describe.**
I'm always frustrated when i try to go back to a previous page. As a iPhone user I'm used to swipe from left to right to go back.

**Describe the solution you'd like**
Allow defining a back_path for a view. When swiped from left to right I will be redirected to the specified page.
If the variable is not defined, do nothing when swiped (for like landing page).

**Comment by albinmedoc** [comment]
Yes, that only allows you to swipe the tabs in order. Lets say I navigated from the landing (tab 1) to living room (tab 5). Then I have to swipe 4 times to come back. 

It would be much better to specify exactly what path you want.

**Comment by basbruss** [comment]
As this project is merely a collection of templates instead of a complete Frontend replacement you are better off directing an FR to the swipe-navigation repo and using it in combination with Minimalist. :wink:

**Comment by albinmedoc** [comment]
You are correct.

**Comment by albinmedoc** [comment]
I have made a PR to [hass-swipe-navigation](https://github.com/zanna-37/hass-swipe-navigation) . You can find the PR here [#37](https://github.com/zanna-37/hass-swipe-navigation/pull/37).
