### ISSUE TITLE
Notification on all cards

### ISSUE THREAD

**Issue by albinmedoc** [UI-Lovelace-Minimalist/UI#1171]
**Is your feature request related to a problem? Please describe.**
I found myself wanting a badge/notification on multiple cards. 
This is documented at [this page](https://ui-lovelace-minimalist.github.io/UI/development/card_style_guide/#anatomy-of-cards), numbered 1, but it's only used by a few cards.

**Describe the solution you'd like**
Allow using this notification on all cards that can optionally be used by the user.

**Describe alternatives you've considered**
Code it by myself for every card. But this will be very repetitive, and not used by anyone else.  

**Additional context**
Here is the notification in use.
<img width="183" alt="Skärmavbild 2023-02-14 kl  15 18 56" src="https://user-images.githubusercontent.com/7331299/218765581-f9ea55fd-3b46-40e6-b899-be3c09d8de24.png">

**Comment by basbruss** [comment]
@albinmedoc Almost all cards have a notification badge when the state turns to `unavailable`.

**Comment by albinmedoc** [comment]
I would like to do something like the attached images.
<img width="329" alt="Skärmavbild 2023-02-14 kl  18 49 46" src="https://user-images.githubusercontent.com/7331299/218818527-0e9f5a94-e195-442a-8b85-1f5d4bcb727f.png">
<img width="331" alt="Skärmavbild 2023-02-14 kl  18 50 08" src="https://user-images.githubusercontent.com/7331299/218818530-1619f35c-4bb9-4441-81f4-a3c6b2ed914d.png">

I think it can be quite hard to implement like the first image since the notification is not at the top level (but as a child card in a custom card).

But the second image should be possible.

**Comment by basbruss** [comment]
See the linked PR, that makes custom notifications for official cards possible. Other contributors can always implement these tools to custom_cards as shown in your screenshots.

Pr makes this possible:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/68892092/218825422-8c87b3ff-cc04-4c18-8c99-21c8e08ff45e.png">

**Comment by albinmedoc** [comment]
Looks good. Great work!


Would be cool if we could make it work for all cards (top level).
Like the two appended images.
<img width="350" alt="Skärmavbild 2023-02-15 kl  07 57 12" src="https://user-images.githubusercontent.com/7331299/218955107-692394f0-4791-4701-b38d-0c6dfbaec095.png">
<img width="456" alt="Skärmavbild 2023-02-15 kl  07 54 35" src="https://user-images.githubusercontent.com/7331299/218955109-e37a1ae9-216a-4133-8cd7-ad0e64e3f6ba.png">

**Comment by albinmedoc** [comment]
I don't know exactly how it is setup. But there should be an underlying "base card" that all others inherit from?
I'm new to UI Lovelace Minimalist and Home Assistant. 

It would be great to add notification to every corner (optionally).
- notification_top_left
- notification_top_right
- notification_bottom_left
- notification_bottom_right

**Comment by basbruss** [comment]
@albinmedoc I like that idea!
I did some testing but it only works without bugs when only one badge is set next to the standard `unavailable` one.
So for now I will let it only work with one customizable badge.

**Comment by albinmedoc** [comment]
Any updates?

**Comment by wilbiev** [comment]
Cleaning-up old issues from the list. Let me know when this issue needs to be re-opened.
