### ISSUE TITLE
Documentation wrong for Custom Scenes Card

### ISSUE THREAD

**Issue by albinmedoc** [UI-Lovelace-Minimalist/UI#1172]
@sildehoop
Documentation is wrong.
See screenshot

<img width="736" alt="Skärmavbild 2023-02-14 kl  15 32 30" src="https://user-images.githubusercontent.com/7331299/218768423-e0309229-f9c5-4f90-9e41-4e681619f995.png">

**Comment by wilbiev** [comment]
Fixed with PR #1571
