### ISSUE TITLE
Light popup not working for (Switch as Light)

### ISSUE THREAD

**Issue by albinmedoc** [UI-Lovelace-Minimalist/UI#1179]
**Describe the bug**
A clear and concise description of what the bug is. No errors in console.

**To Reproduce**

1. Change type of a switch to a light using a helper entity. See [this link](https://www.home-assistant.io/integrations/switch_as_x/) how.
2. Use the [light card](https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_light/) and enable the popup.
3. In the UI double tap the card to open the popup.

**Expected behavior**
I would expect to see a working popup for toggling the light on/off. Not change color och brightness. 

**Screenshots**
<img width="1512" alt="Skärmavbild 2023-02-17 kl  18 54 39" src="https://user-images.githubusercontent.com/7331299/219740241-11df523f-edf6-4d4c-9abc-b1a5c95edd6c.png">

**Additional context**

**Comment by albinmedoc** [comment]
There is no actual benefit by using the popup when there is only on/off.

But I'd like to have the same popup as all my other light and not the standard more-options.

**Comment by wilbiev** [comment]
Cleaning-up old issues from the list. Let me know when this issue needs to be re-opened.
