### ISSUE TITLE
New card_battery is not working

### ISSUE THREAD

**Issue by mlittle408** [UI-Lovelace-Minimalist/UI#118]
Using the latest version of the code, I am testing out the new card_battery and the color of the battery icon is not changing as expected:

  - type: 'custom:button-card'
    template: card_battery
    entity: sensor.front_door_battery
    variables:
      ulm_card_battery_battery_battery_level_danger: 30
      ulm_card_battery_battery_battery_level_warning: 40
    name: Front Door

My battery is currently at 13% and the icon has not changed colors. Did I misunderstand the changes?

**Comment by vncnt-dev** [comment]
Is it possible, that you have a spelling mistake? (one _battery too much) 
Please try:
            variables:
                  ulm_card_battery_battery_level_danger: 30
                  ulm_card_battery_battery_level_warning: 40

**Comment by mlittle408** [comment]
I have no idea how I did that. Oh well, yes that is definitely a typo. It works fine now. Thanks for pointing that out! Nice work btw.
