### ISSUE TITLE
Cover Card Percentage Always Visible

### ISSUE THREAD

**Issue by DoctorMod** [UI-Lovelace-Minimalist/UI#1188]
**Describe the bug**
During commit a8a8ce1, percentages are displayed on the Cover Card even when it is undefined

**To Reproduce**

1. Create a cover card 
2. Set the entity to one that has binary states (i.e. closed and opened)
3. See error

**Expected behavior**
The percentage should be hidden, as was the previous behaviour before the cover cards were updated

**Screenshots**
![image](https://user-images.githubusercontent.com/46367601/222102862-8481f296-b971-4eca-adf6-f53f52f090da.png)

**Comment by benbur98** [comment]
Please try the change I've made in PR#1194. I cannot recreate your problem after this fix but let me know if it is still present.

**Comment by KruseLuds** [comment]
@benbur98 I re-downloaded ui-minimalist repository and restarted home assistant, I still have the same issue and it did not go away. Did I need to redoanload a something different, one of the cards?

![image](https://user-images.githubusercontent.com/96640689/222854100-a7536d0d-777d-497e-9ea4-e07287ea1bac.png)

**Comment by benbur98** [comment]
Hi @KruseLuds , yes unfortunately until the fix is rolled into the Latest release this won't be updated for you. 
One option is to modify the code for the card locally (with the updates from the PR) and reboot.
See for more info: https://ui-lovelace-minimalist.github.io/UI/setup/custom_cards/

**Comment by KruseLuds** [comment]
Ok thx

 

-Kruse

📱(M):  <tel:+1.201.925.4410> +1.201.925.4410

📞(H):  <tel:+1.201.857.8307> +1.201.857.8307

📠(F):  <tel:+1.201.857.7718> +1.201.857.7188
Current Weather and Forecast <https://www.windy.com/40.980/-74.109?40.743,-74.107,9,i:pressure,m:eNsad5E>

**Comment by DoctorMod** [comment]
Thanks @benbur98 for the help, but it still seems to be giving the same error. I took a look at the commit, and it seems that the brackets might be around the wrong bits?

**Comment by benbur98** [comment]
Yep you're completely right! Typo, Fixed now
