### ISSUE TITLE
lovelace-layout-card is missing from the requirements

### ISSUE THREAD

**Issue by Neokil** [UI-Lovelace-Minimalist/UI#1189]
I tried to setup minimalist and it took me a while since there is no reference to the [Layout-Card-Repo ](https://github.com/thomasloven/lovelace-layout-card) that contains the grid-layout component used by the Adaptive-Dashboard, so I was getting the error "custom element doesn't exist: grid-layout".

So I think it would be helpful to add this to the list of requirements.

**Comment by basbruss** [comment]
There is on the Adaptive page as it is only necessary when installing and using the adaptive dashboard.
https://ui-lovelace-minimalist.github.io/UI/setup/adaptive_dash/#additional-requirements
