### ISSUE TITLE
Since the update to 1.2.0 Custom-card "Fan" does not display

### ISSUE THREAD

**Issue by wokkeltje13** [UI-Lovelace-Minimalist/UI#1191]
`        - type: "custom:button-card" 
          template: custom_card_saxel_fan
          entity: fan.ventilator_bureau
          name: Ventilator
          variables:
            collapsible: true
            oscillate_attribute: oscillate`

Error:
![image](https://user-images.githubusercontent.com/57153640/222511099-b99cb60c-87dd-47e2-ab9e-2de40b4d4e81.png)

**Comment by benbur98** [comment]
Fixed in PR. Please Test - worksforme

**Comment by wokkeltje13** [comment]
PR seems to be almost perfect, some remarks

**Comment by wokkeltje13** [comment]
new fan card is working
