### ISSUE TITLE
Since the update to 1.2.0 Weather Card does not display

### ISSUE THREAD

**Issue by wokkeltje13** [UI-Lovelace-Minimalist/UI#1192]
`    - type: "custom:button-card"
      template: card_weather
      entity: weather.openweathermap
      variables:
        ulm_card_weather_name: " "
        ulm_card_weather_backdrop:
          fade: true
        ulm_custom_popup:
          template: "popup_weather_forecast"
          entity: weather.openweathermap
          popup_variables:
              ulm_weather_popup_surpress_first_forecast: false`

Error:
![image](https://user-images.githubusercontent.com/57153640/222512241-832de6a3-5cb0-4956-a8cd-f85fb12a1564.png)

**Comment by wokkeltje13** [comment]
Removal of line 32 works, the fix did not

**Comment by iganeshk** [comment]
Issue will persist even after reboots until the fix is pushed out as a release. Workaround without hacking would be pass your weather's sensor temperature in the following way

```yaml
  ulm_card_weather_custom:
                  - temp: '[[[ return states["weather.home"].attributes.temperature ]]]'
```
