### ISSUE TITLE
Support older browsers

### ISSUE THREAD

**Issue by Petapton** [UI-Lovelace-Minimalist/UI#1196]
**Describe the bug**
View doesn't show up properly on older devices.

**To Reproduce**
Just try to load a dashboard on an old iDevice (I tried on an iPad mini 2).

**Expected behavior**
View should load and render also on "obsolete" devices.

**Screenshots**
![IMG_7341287EB5AF-1](https://user-images.githubusercontent.com/14984292/222975838-075f5112-de95-46c3-9704-7913ca74c6dc.jpeg)

**Additional context**
I noticed of this issue when trying to set up an old iPad mini as a home controller through the web interface. After a little dive, it came out it's a matter of JS optional chaining (and maybe other new features) not being supported on older (not updated) browsers.
As a solution I think the code could be made backward-compatible when fetching the resource (instead of statically re-coding the whole thing and forcing contributors to stick with an older subset of functionalities), either serving two different copies of the same javascript (one being backward compatible), or regex-ing the whole js file on the browser itself. Of course both mechanisms should kick in only when an "unsupported" browser is detected.
I know that going to support this would make the whole code a lot more clumsy, so take this bug report as the following question: is the project willing to support old browsers? I would take care of this if there's a chance of such a PR being accepted.

**Comment by wilbiev** [comment]
Cleaning up issue list
