### ISSUE TITLE
Color and Icon is Missing

### ISSUE THREAD

**Issue by unijiang** [UI-Lovelace-Minimalist/UI#1198]
**Describe the bug**
Color is missing in UI

**To Reproduce**

1. Go to any page of Minimalist
2. Reproduced it in macOS Safari, iOS Safari, macOS Chrome.

**Screenshots**
![Snipaste_2023-03-06_22-15-49](https://user-images.githubusercontent.com/16097705/223135190-5f5fd51b-9293-4855-a294-680834127dc2.jpg)

**Additional context**
Minimalist Version: 1.2.0
Home Assistant 2023.3.1
Supervisor 2023.01.1
Operating System 9.5

**Comment by basbruss** [comment]
Set the theme to Minimalist in your user profile
I will close this as there are multiple closed bug reports, and it is not really a bug but a misconfiguration on the user's side.
https://ui-lovelace-minimalist.github.io/UI/troubleshooting/troubleshooting/
