### ISSUE TITLE
Logo and Images not loading in iOS App but correct in browser

### ISSUE THREAD

**Issue by Ragetti13** [UI-Lovelace-Minimalist/UI#1216]
**Describe the bug**
Logos and colour scheme are not loading on iOS Home Assistant App.

**To Reproduce**
I have tried reloading the yaml, restarting HA, closing and reopening the app and an iPhone soft reset but the issue still appears.

The theme appears correct within a web browser.

**Expected behaviour**

**Screenshots**
![IMG_0160](https://user-images.githubusercontent.com/66558012/224945633-8444e63c-7f8f-4e6e-b1c5-9eb765e2373c.PNG)
![IMG_0161](https://user-images.githubusercontent.com/66558012/224945650-db14e10f-9777-46b7-a289-9aba0a295513.PNG)
<img width="1545" alt="Screenshot 2023-03-14 at 08 47 14" src="https://user-images.githubusercontent.com/66558012/224945856-c5562a56-9f9c-414a-bf37-de5d85d160e6.png">
<img width="1545" alt="Screenshot 2023-03-14 at 08 47 21" src="https://user-images.githubusercontent.com/66558012/224945877-a7c0464d-83a7-4b16-8ecd-08cef2624344.png">

**Comment by basbruss** [comment]
Themes must be set separately for each device and browser in your user profile.
see #1198, #1102, #917 
<img width="999" alt="image" src="https://user-images.githubusercontent.com/68892092/224948086-2961d869-c780-4c1f-bdd9-3625e60fcf4c.png">
https://ui-lovelace-minimalist.github.io/UI/troubleshooting/troubleshooting/
