### ISSUE TITLE
No translation guide found

### ISSUE THREAD

**Issue by sebinemeth** [UI-Lovelace-Minimalist/UI#1225]
**Is your enhancement request related to a problem? Please describe.**
-
The integration is not available in all languages, and I couldn't find info on how to contribute (I would like to use Hungarian and I am willing to translate it).

**Describe the solution you'd like**
-
Please provide a quick guide on translating the integration (fork & add yaml files, or use a service like [Weblate](https://weblate.org/en/)?)

~Describe alternatives you've considered~
-
~Additional context~
-

**Comment by basbruss** [comment]
Hi @sebinemeth 

On what part of the integration do you want to contribute translations?

States within the cards are handled by HA itself. You can add strings to that with [Lokalize](https://lokalise.com/signup/3420425759f6d6d241f598.13594006/all/).

The config flow is handled within the integration and any language can be added by adding a corresponding json file. See this commit as example https://github.com/UI-Lovelace-Minimalist/UI/commit/1b512c06b8a19c00e844caf5a68ac0f31eb830bd

**Comment by sebinemeth** [comment]
Hi!
Thanks for the reply. I had two things in mind, one is the config flow (I will check and add a new JSON), and the other is some Lovelace strings, like "Good morning, Name!" in the welcome scripts card (located in
`<homeassistant-config>/custom_components/ui_lovelace_minimalist/lovelace/translations/en.yaml` in my installation, but could not find them in the repo). I guess these are what you can set the language of in the config flow, right? 
Appreciate your work and support, have a nice day.
