### ISSUE TITLE
Components show error message Cannot read properties of null (reading 'config) since update to HA Core 2023.4

### ISSUE THREAD

**Issue by pluusla** [UI-Lovelace-Minimalist/UI#1247]
**Describe the bug**
Since updating to Home Assistant Core 2023.4, I get the following error message when viewing the dashboard for all components (custom:button-card):
**Cannot read properties of null (reading 'config)**

HA Core: 2023.4
Button Card: 3.5.0
card-mod: 3.2.2
UI-Lovelace-Minimalist: 1.3.1

Everything still worked with HA Core 2032.3.6

**To Reproduce**
Update HA Core 2032.3.6 to 2023.4
Update Button Card, card-mod and ui-minimalist

**Expected behavior**
The components are correctly rendered in the dashboard again

**Additional context**
I have reloaded/reinstalled Button Card and card-mod. This has unfortunately helped nothing
The components via mushroom integration are rendered correctly (for example custom:mushroom-media-player-card)

**Comment by northrup** [comment]
Hm... I'm having this issue as well and no amount of cache clearing is fixing it 🤔

**Comment by timo-mart** [comment]
> Hm... I'm having this issue as well and no amount of cache clearing is fixing it thinking

Same for me

**Comment by jfeeser** [comment]
Same here.  Oddly it seems to be only happening on mobile.  Web seems to not have the issue.

**Comment by grant66** [comment]
Having a similar issue since updating to 2023.4.2

Seems to be related to cards which contain "template: container", deleting that line renders the card.
