### ISSUE TITLE
iOS tapbar not sticky when scrolling

### ISSUE THREAD

**Issue by dsvdglenn** [UI-Lovelace-Minimalist/UI#1248]
**Describe the bug**
When selecting the theme "minimalist-ios-tapbar" the navigation bar isn't sticking below the screen and scrolls with the page.
**To Reproduce**

scroll in dashboard

**Expected behavior**
Tapbar has to be sticky at the bottom

**Screenshots**

**Additional context**
My quick and maybe dirty fix was adding an extra postition fix at the following line at minimalist-ios-tapbar.yaml

below line 35:
       div#view{
                   position: fixed !important;

**Comment by yuhuanfan** [comment]
same issue

**Comment by basbruss** [comment]
Fixed with https://github.com/UI-Lovelace-Minimalist/UI/releases/tag/v1.3.2
