### ISSUE TITLE
slider is missing in cover card

### ISSUE THREAD

**Issue by shift-del1** [UI-Lovelace-Minimalist/UI#1251]
If I enable the controls and the slider, plus enable horizontal, the slider is not displayed. If I disable horizontal, slider will be shown again. HA Core 2023.4.0, UI Minimalist 1.3.0, all HACS modules are updated to their latest versions.

![image](https://user-images.githubusercontent.com/63366470/230334691-fde8b8b4-537a-467a-b573-f1ccd002bd6e.png)

The difference is only the horizontal parameter (disabled on the left, enabled on the right card). Thank you.

**Comment by shift-del1** [comment]
@benbur98 I have to disagree, see my screenshot [here](https://github.com/UI-Lovelace-Minimalist/UI/issues/1215). In 1.2.0 everything looked fine. However applying your PR on my dashboard fixes my issue, thank you so much.

**Comment by benbur98** [comment]
Hi @shift-del1, yes after looking into it I do agree with you that this is better. I'm still considering what you've said about a "priority" option which I think would be nice - just need a good way to implement it!

**Comment by shift-del1** [comment]
@benbur98: How about the way I described in #1215?

**Comment by benbur98** [comment]
It works yes, just difficult to be adaptable, particularly with other cards that'd benefit from this feature (e.g. the light)
