### ISSUE TITLE
"Sun" custom card uses archived repository

### ISSUE THREAD

**Issue by varyamereon** [UI-Lovelace-Minimalist/UI#1259]
**Describe the bug**
The original home-assistant-sun-card repository that the Minimalist "Sun" custom card uses is now archived. The repository shows as archived and to be removed on HACS. There is a replacement repository available [here](https://github.com/rejuvenate/lovelace-horizon-card).

**To Reproduce**

1. Go to HACS
2. Archived repository message is shown

**Expected behavior**
The repository needs updating to the new version.

**Comment by wilbiev** [comment]
Cleaning-up old issues from the list. Let me know when this issue needs to be re-opened.
