### ISSUE TITLE
Colored Light Card

### ISSUE THREAD

**Issue by chielbos** [UI-Lovelace-Minimalist/UI#126]
**Describe the solution you'd like**
At this moment i use the light card to control my philips HUE color lights.
My dashboard misses reflection of the used color.
I would love to see the light tiles reflect the current active color, like the base install does.

Design proposal:
![image](https://user-images.githubusercontent.com/9056221/146993917-47163093-ceee-4926-863d-d04bb8e24e95.png)

**Comment by CM000n** [comment]
Have you already tried the new `card_light_color` from @basbruss? 
https://github.com/UI-Lovelace-Minimalist/UI/tree/main/custom_cards/custom_card_light_color
Maybe it already meets your requirements 😉

**Comment by basbruss** [comment]
My card provides you with that functionality.
<img width="488" alt="Screen Shot 2021-12-14 at 20 10 11" src="https://user-images.githubusercontent.com/68892092/146998950-e0280f8d-fc28-450e-b10e-d40904521664.png">
The custom_card_light_color folder also includes a card without the slider :)
Note: make sure you also install custom_card_light_icon_info as there is a template inside which is used in the colored cards.

**Comment by chielbos** [comment]
Looks exactly like what I was looking for!

Gonna try tonight :)
