### ISSUE TITLE
Style and Layout does not load correctly

### ISSUE THREAD

**Issue by deanfourie1** [UI-Lovelace-Minimalist/UI#1262]
**Describe the bug**
Its almost like there is not "stylesheet, similar behavior but the layout and design is all messed up. It does not look good at all.

**To Reproduce**

1. Install from HACS
2. Open the UI lovelace minialmist from the left menu

**Expected behavior**
Sexiness

**Screenshots**
![image](https://user-images.githubusercontent.com/71812804/230769178-2c2b3c83-a2fe-4abb-8ff2-54ce65636acd.png)

![image](https://user-images.githubusercontent.com/71812804/230769205-31eac36a-e27d-432a-bb4a-3c9d34fdffe4.png)

**Additional context**
I'm not sure what I'm missing here? I've installed directly from HACS.

**Comment by smartypantsuk** [comment]
Ok I'll ask the obvious, have you reloaded ui-lovelace-minimalist via the developer tools and also refreshed your browser cache? That's the usual culprit, though I'm having similar issues with a new install.

**Comment by damusmf** [comment]
have you set your Theme to be one of the minimalist themes? 
![image](https://user-images.githubusercontent.com/31552122/230801841-98a294d4-3a34-4ce7-9cda-e53326d8ae23.png)
