### ISSUE TITLE
Custom Washer / Dryer card issues for LG SmartThinQ devices

### ISSUE THREAD

**Issue by dougmaitelli** [UI-Lovelace-Minimalist/UI#1268]
**Describe the bug**
Using the new `custom_card_haven_washer` for LG SmartThinQ washers works great but has a few limitations that could be improved and currently cause the label to always show as `undefined`.

The reason for that is because the card detects the current state as `running` using this condition:
```
["run", "pause"].indexOf(states[variables.ulm_custom_card_washer_machine_state].state) >= 0
```
https://github.com/UI-Lovelace-Minimalist/UI/pull/1214/files?short_path=db29fd1#diff-53060fd8a796a8af66bbbd40aadc8ffe6a66cefdded6a1641152f46923cb7754R122

However, for these integrations there is no property that summarizes the state as "run" or "paused", etc.

So, wouldn't it make more sense to make this array of values customizable? Or instead just assume it is running if the `ulm_custom_card_washer_job_state` is one of the values of `ulm_custom_card_washer_job_states`?
It should be safe to assume that the washer is running if the current state is one of the cycle recognized states.

**To Reproduce**

Card configuration used:
```
  - type: "custom:button-card"
    template: "custom_card_haven_washer"
    variables:
      ulm_custom_card_washer_power: sensor.washer_power
      ulm_custom_card_washer_machine_state: binary_sensor.washer_wash_completed
      ulm_custom_card_washer_job_state: sensor.washer_run_state
      ulm_custom_card_washer_job_states:
        state1:
          name: "Detecting"
          icon: "mdi:scale"
        state2:
          name: "Washing"
          icon: "mdi:waves"
        state3:
          name: "Rinsing"
          icon: "mdi:water"
        state4:
          name: "Spin"
          icon: "mdi:fan"
      ulm_custom_card_washer_label_running: >
        [[[
          return states["sensor.washer_remaining_time"];
        ]]]
      ulm_custom_card_washer_label_configuring: >
        [[[
            var name = states["sensor.washer_initial_time"].attributes.friendly_name;
            var time = states["sensor.washer_initial_time"].attributes.display_time;
            return name + " • " + time;
        ]]]
```

**Expected behavior**
The custom card should recognize the proper run state in order to show the proper label.

**Screenshots**
Attributes currently provided by the integration:
![image](https://user-images.githubusercontent.com/1277391/230801995-70812584-52b2-421f-bb3f-8469b87a06d2.png)

**Comment by dougmaitelli** [comment]
FYI @Cruguah

Btw, thanks for the amazing work here.

**Comment by dougmaitelli** [comment]
Hey @Cruguah,

I don't think there is a variable that describes the current machine state (stop, run, pause).
This is why I was thinking that it could be helpful to make the card use the program step to determine if it is running in case there is no machine state provided?

Thanks,

**Comment by shift-del1** [comment]
@dougmaitelli: you have a run state, which reminds me to the washer job states defined by the card itself. Maybe that one? I don't have a smart washing machine, but planning to buy one in the near future, so just guessing.

**Comment by dougmaitelli** [comment]
> @dougmaitelli: you have a run state, which reminds me to the washer job states defined by the card itself. Maybe that one? I don't have a smart washing machine, but planning to buy one in the near future, so just guessing.

@shift-del1 the problem is that the card is currently hard coded to use machine states like "run" and "pause" which are not the values used by the Smart ThinQ integration

**Comment by Cruguah** [comment]
Doug,

I see your point, but the machine state is used multiple ways:
1. To change the label shown
2. To change te behavoir of the start, pause and stop buttons

I wonder, can't we solve this by using a template sensor, a sensor that translate the binary_sensor.washer_wash_completed to run or stop

`
template:
  - sensor:
      - name: "washer_wash_machine_state"
        state: >
          {% if is_state('binary_sensor.washer_wash_completed', 'off') %}
            run
          {% else %}
            stop
          {% endif %}
`

And if there is a way of knowing when the washer is paused you can add this in this specific sensor

**Comment by dougmaitelli** [comment]
@Cruguah, yes, that theoretically could solve the problem, I considered doing that. However I think it would make the card more easy to use and more friendly to configure if we could have those values configured, maybe a couple variables like:
`machine_running_states: ["run"]`, `machine_stopped_states: ["stopped"]`, `machine_paused_states: ["paused"]`

**Comment by Cruguah** [comment]
Hi Doug,

Let me know if the PR version solves your problem.
I've changed the code to make it work with a single variable, the ulm_custom_card_washer_machine_stop_state.
This machine stop state defines what the actual value is (of the states[variables.ulm_custom_card_washer_machine_state].state) when your washer or dryer is stopped.
Default the variable is defined as "stop", but you can change it to your own value, make shure it is a string. The states[variables.ulm_custom_card_washer_machine_state].state is also translated to a string before testing.

Kind regards,
Cruguah

**Comment by dougmaitelli** [comment]
Thanks @Cruguah,

It does solve the issue if I use the following configuration:
```
ulm_custom_card_washer_power: sensor.washer
ulm_custom_card_washer_machine_state: sensor.washer_run_state
ulm_custom_card_washer_machine_stop_state: "-"
ulm_custom_card_washer_job_state: sensor.washer_run_state
```

It happens that the "Pause" state for the LG is also part of the job states and when it is Off it returns "-".

Thank you very much!

**Comment by Cruguah** [comment]
Great, Hope this PR get merged soon!

**Comment by Cruguah** [comment]
@dougmaitelli, If your solution works, could you send me the complete configuration of your washer, including the (name /repo of the) integration that you've used, so I can update the documentation and describe how you could setup a LG SmartThinQ washer as well. It might help others to!

**Comment by dougmaitelli** [comment]
Hi @Cruguah, here it is:

```
  - type: "custom:button-card"
    template: "custom_card_haven_washer"
    variables:
      ulm_custom_card_washer_power: sensor.washer
      ulm_custom_card_washer_machine_state: sensor.washer_run_state
      ulm_custom_card_washer_machine_stop_state: "-"
      ulm_custom_card_washer_job_state: sensor.washer_run_state
      ulm_custom_card_washer_job_states:
        state1:
          name: "Detecting"
          icon: "mdi:scale"
        state2:
          name: "Washing"
          icon: "mdi:waves"
        state3:
          name: "Rinsing"
          icon: "mdi:water"
        state4:
          name: "Spin"
          icon: "mdi:fan"
      ulm_custom_card_washer_label_idle: >
        [[[
          return "-";
        ]]]
      ulm_custom_card_washer_label_running: >
        [[[
          return states["sensor.washer_remaining_time"].state;
        ]]]
      ulm_custom_card_washer_label_configuring: >
        [[[
            var name = states["sensor.washer_initial_time"].attributes.friendly_name;
            var time = states["sensor.washer_initial_time"].attributes.display_time;
            return name + " • " + time;
        ]]]
```

I had to set `ulm_custom_card_washer_label_idle` to return an `-` since I don't have any information to display when it is idle and the card shows `undefined` if nothing is defined. It would be nice if it would default to a blank string.

Regarding `ulm_custom_card_washer_label_configuring`, I didn't test the configuring state so I am not 100% if my config is correct for that one.

Thanks,

**Comment by Cruguah** [comment]
> Hi @Cruguah, here it is:
> 
> ```
>   - type: "custom:button-card"
>     template: "custom_card_haven_washer"
>     variables:
>       ulm_custom_card_washer_power: sensor.washer
>       ulm_custom_card_washer_machine_state: sensor.washer_run_state
>       ulm_custom_card_washer_machine_stop_state: "-"
>       ulm_custom_card_washer_job_state: sensor.washer_run_state
>       ulm_custom_card_washer_job_states:
>         state1:
>           name: "Detecting"
>           icon: "mdi:scale"
>         state2:
>           name: "Washing"
>           icon: "mdi:waves"
>         state3:
>           name: "Rinsing"
>           icon: "mdi:water"
>         state4:
>           name: "Spin"
>           icon: "mdi:fan"
>       ulm_custom_card_washer_label_idle: >
>         [[[
>           return "-";
>         ]]]
>       ulm_custom_card_washer_label_running: >
>         [[[
>           return states["sensor.washer_remaining_time"].state;
>         ]]]
>       ulm_custom_card_washer_label_configuring: >
>         [[[
>             var name = states["sensor.washer_initial_time"].attributes.friendly_name;
>             var time = states["sensor.washer_initial_time"].attributes.display_time;
>             return name + " • " + time;
>         ]]]
> ```
> 
> I had to set `ulm_custom_card_washer_label_idle` to return an `-` since I don't have any information to display when it is idle and the card shows `undefined` if nothing is defined. It would be nice if it would default to a blank string.
> 
> Regarding `ulm_custom_card_washer_label_configuring`, I didn't test the configuring state so I am not 100% if my config is correct for that one.
> 
> Thanks,

And what integration did you use for LG SmartThinQ?

**Comment by dougmaitelli** [comment]
@Cruguah This one https://github.com/ollo69/ha-smartthinq-sensors

**Comment by Cruguah** [comment]
> @Cruguah This one https://github.com/ollo69/ha-smartthinq-sensors

Thanks dougmaitelli, I've added default values to the different labels so that you can see when which label is shown.
I've also added the LG confguration to the documentation. Thanx for sharing your experience.
