### ISSUE TITLE
Custom-card "Flower" doesn't render

### ISSUE THREAD

**Issue by txitxo0** [UI-Lovelace-Minimalist/UI#1272]
**Describe the bug**
The custom-card "Flower" doesn't render due to a problem searching the template ulm_custom_card_schumijo_flower_language_variables
**To Reproduce**

1. Install [lovelace-card-tools](https://github.com/thomasloven/lovelace-card-tools)
2. Install [Custom Plant integration](https://github.com/Olen/homeassistant-plant) (Optional)
3. Install [lovelace-flower-card](https://github.com/Olen/lovelace-flower-card)
4. Add the custom card to your ui lovelace minimalist installation [raw content](https://raw.githubusercontent.com/UI-Lovelace-Minimalist/UI/main/custom_cards/custom_card_schumijo_flower/custom_card_schumijo_flower.yaml)
5. Set up a card in your dashboard, i.e.:
```yam
  - type: horizontal-stack
    cards:
    - type: "custom:button-card"
      template: card_flower
      variables:
        ulm_card_flower_entity: plant.palmera
        ulm_card_flower_name: Palmera
        ulm_card_flower_species: "Arecaceae"
```

**Expected behavior**
A flower card appears

**Screenshots**
![image](https://user-images.githubusercontent.com/12279324/231075846-203725e1-5fd8-474f-83ef-5a6f03938a72.png)

**Comment by basbruss** [comment]
Hi @txitxo0 

You will also need to choose a preferred language from https://github.com/UI-Lovelace-Minimalist/UI/tree/main/custom_cards/custom_card_schumijo_flower/languages

Add the preferred file to the `custom_cards` folder and reload the yaml-configuration for ULM to make the translations active

**Comment by txitxo0** [comment]
> Hi @txitxo0
> 
> You will also need to choose a preferred language from https://github.com/UI-Lovelace-Minimalist/UI/tree/main/custom_cards/custom_card_schumijo_flower/languages
> 
> Add the preferred file to the `custom_cards` folder and reload the yaml-configuration for ULM to make the translations active


Oh, I didn't saw that in the docs, so many thanks, bug closed.

Thank you again
