### ISSUE TITLE
Where to store custom cards that are not part of UI lovelace minimalist 

### ISSUE THREAD

**Issue by mxilievski** [UI-Lovelace-Minimalist/UI#1278]
@basbruss sorry for opening an issue for this. 

My question is basically the title. I have few custom components (some tweaks to existing components) which i have no idea where to store safely. Is there some folder that is safe to store them without them being deleted on each update?

Right now i'm storing them in `/custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/custom_cards/` but they get deleted on each UI Lovelace Minimalist update.

**Comment by shogun160** [comment]
No problems here. I justed use the path mentioned in the docu: [Setup Custom Cards](https://ui-lovelace-minimalist.github.io/UI/setup/custom_cards/)

**Comment by mxilievski** [comment]
what a RTFM moment of shame. Tnx @shogun160, that worked perfectly ofcourse, closing this.
