### ISSUE TITLE
Unable to scroll dashboard when using minimallist-mobile theme

### ISSUE THREAD

**Issue by billyjoebob999** [UI-Lovelace-Minimalist/UI#1279]
**Describe the bug**
After updating to v1.3.4 I can no long scroll the dashboard when using the minimallist-mobile theme. This is true for both mobile and desktop web browsers 

**To Reproduce**
Set HA theme to minimallist-mobile. Try scrolling dashboard. For desktop, scrolling with the mouse wheel does not work.

**Additional context**
The other UI themes dont have this problem, desktop, ios-tapbar, mobile-tapbar all work just fine on mobile or desktop web browsers.

**Comment by basbruss** [comment]
Sorry to ask, but have you run the `frontend.reload_themes` service after updating?

Even a HA restart does not load changes to themes.

**Comment by billyjoebob999** [comment]
Just tried but no change. I've cleared the cache and even did a redownload but still unable to scroll. I can go into settings and it scrolls just fine there.

**Comment by basbruss** [comment]
Do you have any screen capture for reference?

**Comment by tivoo** [comment]
Same issue here. A restart and reload did not help. Also a restart after the reload service does not allow me to scroll anymore.

**Comment by ralfhanke** [comment]
Can confirm that. Neither restarting nor reloading the themes helped.

**Comment by nicojmb** [comment]
Same problem here, i run `frontend.reload_themes`  but not fix de problem

**Comment by billyjoebob999** [comment]
> Do you have any screen capture for reference?

Thankfully i'm not the only one experiencing this issue

Here is a screen capture of the issue. For reference I start off by changing the theme to ios tap bar then switching to the mobile theme

https://youtube.com/shorts/DTOjxOI9I_I

**Comment by Whininie** [comment]
same issue

**Comment by tivoo** [comment]
It seems it only affects certain mobile phones. Perhaps it depends on the OS. It might help if we share some device details as well to figure out the issue.

Device: Samsung Galaxy S22
Android 13
One UI 5.1

**Comment by Wesleyl89** [comment]
Same here

Device: OnePlus 9 Pro
Android 13
OxygenOS 13.0

**Comment by ralfhanke** [comment]
> Seems indeed to be an issue only on Android devices. On iOS everything works as it should.

Scrolling in the browser (Windows PC) using the mouse wheel no longer works either.

**Comment by basbruss** [comment]
If some of you can verify the fix I would be able to release the fix immediately!

**Comment by nicojmb** [comment]
> I think I have found a fix, tested on Chrome (MacOS), android (OnePlus 7t), and iPhone 13. changed card_mod part to:
> 
> ```yaml
>   card-mod-root: |
>     .header {
>       display: none;
>     }
>     #view {
>       margin: 0 !important;
>       height: 100vh !important;
>     }
> ```

Tried in my Pixel 7 Pro and now works perfect 👍

**Comment by billyjoebob999** [comment]
> I think I have found a fix, tested on Chrome (MacOS), android (OnePlus 7t), and iPhone 13. changed card_mod part to:
> 
> ```yaml
>   card-mod-root: |
>     .header {
>       display: none;
>     }
>     #view {
>       margin: 0 !important;
>       height: 100vh !important;
>     }
> ```

Looking at my minimalist-mobile.yaml i can see that is already there
![image](https://user-images.githubusercontent.com/51886188/232515512-f9bcaa2e-5ba9-4747-9668-19697f6c7072.png)

**Comment by nicojmb** [comment]
> > I think I have found a fix, tested on Chrome (MacOS), android (OnePlus 7t), and iPhone 13. changed card_mod part to:
> > ```yaml
> >   card-mod-root: |
> >     .header {
> >       display: none;
> >     }
> >     #view {
> >       margin: 0 !important;
> >       height: 100vh !important;
> >     }
> > ```
> 
> Looking at my minimalist-mobile.yaml i can see that is already there ![image](https://user-images.githubusercontent.com/51886188/232515512-f9bcaa2e-5ba9-4747-9668-19697f6c7072.png)

it's not the same the original has "%" and the fix has "vh"

**Comment by basbruss** [comment]
Jup as mentioned by @nicojmb percentage is not exactly the same as viewport-height. As in this case setting the viewport-height forces the app to add a scrollbar when the content is larger than the viewport.

**Comment by billyjoebob999** [comment]
Thank you both for pointing that out! Can confirm it works both on mobile and windows desktop
