### ISSUE TITLE
Missing template card light color

### ISSUE THREAD

**Issue by httpedo13** [UI-Lovelace-Minimalist/UI#128]
I tried to use the collapse card but I get the following error: Button card template "list_items_light" is missing!

**Comment by basbruss** [comment]
Sorry this template is inside the custom_card_light_icon_info folder.
If you also install this folder in your custom_cards then it will be fixed.
Both cards use that template. I will fix it in the next release :)

**Comment by httpedo13** [comment]
Thank you @basbruss! So, I've tested it and I prefer white/black card background.

**Comment by basbruss** [comment]
Fixed in #140
