### ISSUE TITLE
Move away from using px and instead use vw for styling

### ISSUE THREAD

**Issue by mlittle408** [UI-Lovelace-Minimalist/UI#129]
Have you considered using vw instead of px (for font sizes, padding, etc) in the button card template (and theme file)? It would make the it a lot more responsive and would allow you to use one theme file for desktop, tablet and mobile. I am working on a layout that works on my desktop and kiosk tablet and am running into issues related to sizing. The stumbling block is the reliance on px instead of vw. Is that something you're considering? I didn't want to have to modify the button card template for my situation, if I can avoid it.  

You can also use vmin and vmax for fonts if you want to limit the smallest and largest sizes. Just a thought.

**Comment by bavo** [comment]
Yes, good idea. 

Can you contribute to this? 
I'm happy to help you integrate the changes if you have any questions but my knowledge on vw and px is fairly limited.

**Comment by saxel** [comment]
TIL there's more than px, sp and percentage for setting size😀

**Comment by mlittle408** [comment]
Yes, I'd be happy to work on it 😀

**Comment by 13robin37** [comment]
@mlittle408 If you haven't implemented something on your end yet I'd suggest to work with variables to have some proper framework in place instead of just converting everything to responsive units. That way new cards are properly done out of the box.

To keep it simple, I would suggest the following variables, any thoughts?

`  space-xs: "0.5em"
  space-s: "1.0em"
  space-m: "1.5em"
  space-l: "2.0em"
  space-xl: "2.5em"`

**Comment by CM000n** [comment]
Maybe this issue can be addressed together with @sildehoop 's suggestion to make our internal templates more modular to be able to use them more versatile?
This just came to my mind...

**Comment by 13robin37** [comment]
A combo of variables and predefined classes would be the most versatile option if someone knows a way to apply classes to specific cards with card-mod. Haven't looked that much into it yet. 

Merry Christmas and happy holidays btw! 😄

**Comment by sildehoop** [comment]
I thought about something like this to design the cards and think about the margins and sizes
<img width="455" alt="Schermafbeelding 2021-12-27 om 15 05 28" src="https://user-images.githubusercontent.com/34340385/147479189-040eab5a-9efd-420f-a484-b1ae5303bc5d.png">

**Comment by sildehoop** [comment]
<img width="783" alt="Schermafbeelding 2021-12-27 om 16 50 24" src="https://user-images.githubusercontent.com/34340385/147487400-9fe6f462-b4ab-40bb-9497-0f1a184964e6.png">

**Comment by wilbiev** [comment]
Cleaning up issue list
