### ISSUE TITLE
Minimalist cards broken only on one device

### ISSUE THREAD

**Issue by AdrienAA** [UI-Lovelace-Minimalist/UI#1298]
Hello everyone !

I discovered Minimalist UI not so long ago, but I really love it ! 
I've been planning on creating new and better dashboards for all of my devices, but I stumbled on a problem and I can't figure it out.

### **Describe the bug**
I have been creating several minimalist dashboards for my devices on the past few days.
Everything works well, except for one specific set of conditions  : 
 - When on my lenovo smart clock 2 (hacked thanks to this tuto : https://www.youtube.com/watch?v=uSHpvbbvz7Q )
   - displaying a Minimalist dashboard
     - displaying a Minimaliste card (custom or not)
 
 **--> My minimalist UI Cards don't work and display errors.**
 
On my other devices (computer and smartphones), everything works perfectly. Also, on my lenovo smart clock 2, the other cards work perfectly, even when I put them in a minimalist dashboard.

I tried to change the theme, reboot my clock and reboot home assistant. Nothing worked.

### **To Reproduce**

1. Create a minimalist dashboard
2. Create a minimalist card in this dashboard
3. Display the dashboard on the Lenovo Smart clock 2

### **Expected behavior**
The dashboard should display the card correctly

### **Screenshots**
The first card is a "Scene Card" from the standard Minimalist UI
The bottom part are a "Mini media player" card (left) and a grid of picture cards (on the right)

Designed dashboard expected result. (Screenshot taken from my computer) : 
![Capture d'écran 2023-05-11 195543](https://github.com/UI-Lovelace-Minimalist/UI/assets/40207734/e02e8c40-c7c9-4d0d-8fbe-d18134ec1dae)

Result on the Lenovo Smart clock 2 (sorry for the poor quality) : 

![344536393_558757543047403_645828814251693956_n](https://github.com/UI-Lovelace-Minimalist/UI/assets/40207734/6ed48d32-f5e5-4f7a-9a2d-a0ccf3d77fc3)

After scrolling down a long time...

![344502517_823008712766763_7509887836761887739_n](https://github.com/UI-Lovelace-Minimalist/UI/assets/40207734/ade6b9c8-3f3f-4b5f-b80c-93950eb74813)

### **Additional infos**

- At first I though that it was because of a problem of screen dimension and resolution, but on my computer I tried a lot of different resolutions (even really small ones) and the dashboards never crashed.

- The very long error code is actually the source code of the card that has a problem (Scened Card). the "title of the error is : 

ButtonCardJSTemplateError: SyntaxError: Unexpected token . in 'var pills = [] const entities = [variables.entity_1?.entity_id, variables.entity_2?.entity_id, v...'

(I suppose it has been truncated) 

Thanks in advance for your help ! I'm not a pro in all this, but I try to learn as much as possible :)

Adrien

**Comment by wilbiev** [comment]
Cleaning-up old issues from the list. Let me know when this issue needs to be re-opened.
