### ISSUE TITLE
Room card with humidity option next to temperature

### ISSUE THREAD

**Issue by miszczur** [UI-Lovelace-Minimalist/UI#1301]
Is any chance to configure room card to show humidity next to temperature option?

**Comment by basbruss** [comment]
@miszczur 

You can change the `label` value to a javascript template to give both temperature and humidity.
An example is given on the documentation page of the custom room card https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_esh_room/#customizations
