### ISSUE TITLE
Problems since HA update 2023.5.3

### ISSUE THREAD

**Issue by HomeassistantNewb** [UI-Lovelace-Minimalist/UI#1302]
I updated Home Assistant to Version stated above and my Dashboard isn't working anymore. (Screenshot of how it looks now!)

I have followed things I randomly found online such as:
- getting rid of the include line in the Dashboard.yaml file
- calling frontend.reload_themes

but no luck! If anyone has any hints or ways to help it would be much appriciated.

Screenshot
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/99397299/e4c5b6d6-e1cc-4a80-9d4e-79d29d1c4bbb)

**Comment by basbruss** [comment]
Hi @HomeassistantNewb 

What versions of Minimalist and button-card do you have installed?

**Comment by HomeassistantNewb** [comment]
> Hi @HomeassistantNewb
> 
> What versions of Minimalist and button-card do you have installed?

Minimalist is on v1.3.5 and button-card is on v3.4.2

**Comment by bigal2112** [comment]
Make sure to clear cached images and files from the browser. That fixed it for me.

**Comment by HomeassistantNewb** [comment]
> Make sure to clear cached images and files from the browser. That fixed it for me.

@bigal2112 I cleared all my Browser Cache but no luck. Isn’t working on mobile either. Seems to be a Template big I think.

**Comment by bigal2112** [comment]
Hmm, that's weird. I had exactly the same issue as you have shown. All I had to do was make sure EVERYTHING was updated so went into HACS and made sure all the cards and Integrations and Frontend stuff was updated, cleared my cached, restarted HA and it worked. Same with the mobile, just cleared the cached and up came the Minimalist UI.

Sorry I can't be of anymore help, hope you get it fixed soon.

**Comment by mqtt-fan** [comment]
I have the same issue, restarting HA and clearing the cache didn't help. Error Message looks a little bit different on Chrome.
![Uploading Bildschirmfoto 2023-08-05 um 18.28.46.png…]()

**Comment by HomeassistantNewb** [comment]
> I have the same issue, restarting HA and clearing the cache didn't help. Error Message looks a little bit different on Chrome.
> ![Bildschirmfoto 2023-08-05 um 18 28 46](https://user-images.githubusercontent.com/32242849/258600056-03fe0b8b-b16b-49ea-8e16-3fc5e7d00627.png)

I managed to fix the issue by going back to an older version I had where it worked, updated everything in Hass and Hacs and then doing the Hass and supervisor updates.

**Comment by shodushi** [comment]
I fixed it after fixing the path in my lovelace/xxxxxxx.yaml:

from:
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

to:

button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/"

**Comment by wilbiev** [comment]
After installation of the integration the folder ../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates should exist. 
![image](https://github.com/user-attachments/assets/c6575c19-b928-4fff-a044-c8a76bba903c)
