### ISSUE TITLE
Icon opacity changed after update

### ISSUE THREAD

**Issue by tieskuh** [UI-Lovelace-Minimalist/UI#1306]
Since one of the latest updates, the icon on the graph card is grey (0.2).

<img width="167" alt="image" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/115901851/ed521289-3b0a-4c3b-8b2d-01feb46c7258">

Previously it was black (1.0) like this:

<img width="172" alt="image" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/115901851/255e04a0-e5f6-46d2-a8bc-bb9da128ef1f">

There doesn't seem to be a setting to get it back to the 'old' style. Changing the color also changes the intensity of the background.

**Comment by wilbiev** [comment]
Cleaning-up issue list. Let me know when this issue needs to be reopened.
