### ISSUE TITLE
Display Precision not Updating in Chip Cards

### ISSUE THREAD

**Issue by IMakeTP** [UI-Lovelace-Minimalist/UI#1313]
**Describe the bug**
Similar to the issue with Mushroom, Minimalist chip cards are not updating with precision adjustments made within HA UI.
https://github.com/home-assistant/frontend/issues/15582

**To Reproduce**

yaml code:
              type: 'custom:button-card'
              template: chip_icon_label
              label:  >
                [[[
                  return states['sensor.meater_probe_ambient'].state + "°F / " + states['sensor.meater_probe_internal'].state + "°F"
                ]]]
              icon: mdi:grill
              color: "var(--google-red)"

![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/132024767/3253b4d4-756e-476d-bd8b-ba041bdb5e15)

**Expected behavior**
Temperature display should be with zero significant digits

**Screenshots**
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/132024767/2bee1ba5-633d-4810-b8f4-5f79efdb843d)

**Additional context**

**Comment by andyblac** [comment]
how would use it for example above
```
label: '[[[ return states["sensor.front_garden_motion_sensor_temperature"].state + "°C" ]]]'
```

**Comment by basbruss** [comment]
> how would use it for example above
> 
> ```
> label: '[[[ return states["sensor.front_garden_motion_sensor_temperature"].state + "°C" ]]]'
> ```

It would not work without globally setting the entity.
So the minimal things you need to have in your card/chip is:
```yaml
template:
  - ulm_translation_engine
entity: sensor.front_garden_motion_sensor_temperature
label: "[[[ return variables.ulm_translation_state_unit ]]]"
```
