### ISSUE TITLE
Missing custom_card_yagrasdemonde_lights_count_languages_variable

### ISSUE THREAD

**Issue by NeoFax75** [UI-Lovelace-Minimalist/UI#1321]
**Describe the bug**
Installed custom_card_yagrasdemonde_lights_count by copying and pasting the yaml along with other custom cards in my /config/ui_lovelace_minimalist/custom_cards/ folder.  Restarted HA and I get the "Button Card template "custom_card_yagrasdemonde_lights_count_languages_variable" is missing!

**To Reproduce**

1. Copy yaml from WIKI
2. Create folder custom_card_yagrasdemonde_lights_count inside custom_cards folder.
3. Create file custom_card_yagrasdemonde_lights_count.yaml inside the previous steps folder.

**Expected behavior**
Should be able to see the button displayed with how many lights are on.

**Comment by basbruss** [comment]
Also paste the preferred language file in that folder, some custom cards do have their own language file accompanied on the github.

**Comment by Bodrick01** [comment]
Any further resolution to this one?  I'm seeing the same issue.  Regret the suggestion to "paste the preferred language file" doesn't make sense to me (noob here!) and I can't see any additional files associated with this custom card.

**Comment by Bodrick01** [comment]
OK, so I found the answer to that last one: https://community.home-assistant.io/t/language-variables-missing-in-button-cards/539797
Card still doesn't work, but maybe I'm  a step further forward!  :-)

**Comment by wilbiev** [comment]
Should be fixed in current version of custom card.
