### ISSUE TITLE
Installation documentation references non-existent dependency `my-cards-slider-card`

### ISSUE THREAD

**Issue by Lx** [UI-Lovelace-Minimalist/UI#1323]
**Describe the bug**
- The steps for installing the integration give a list of required Lovelace resources to install manually if the user wishes to manage them via HACS.
- One such dependency is `my-cards-slider-card`.
- This dependency doesn't exist on HACS by that name, or by any similar name.

**Expected behavior**
The list of manually installable resources should be provided with search terms that will correctly identify all required HACS downloads—or, where a resource is known not to be on HACS, a specific URL should be given.

**Comment by basbruss** [comment]
You can click on the dependency on the wiki (which is a hyperlink). That will bring you to the correct repo. If a repo is not part of the default HACS store you can always add it as custom repo following the HACS documentation, sometimes this is also included on the repo of the card itself.

**Comment by Lx** [comment]
Thank you.  This helped me to understand the cause: I didn't realise they were hyperlinks.

The dependency list is currently formatted as a [data table](https://squidfunk.github.io/mkdocs-material/reference/data-tables/), whose cells change colour when moused over, but which do not change the pointer unless moved directly over the dependency names.  Granted, the text is blue—but it's also `fixed-width-formatted`, which is also commonly formatted in a different colour without being a hyperlink.

I don't think a data table is the most user-friendly choice here.  I will propose something a little simpler and more obvious in a pull request.
