### ISSUE TITLE
Adaptive dashboard not loading

### ISSUE THREAD

**Issue by srThibaultP** [UI-Lovelace-Minimalist/UI#1336]
**Describe the bug**
The dashboard show default text but without cards.
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/42326001/e6ec24a0-21f9-4ad9-b3c4-f6e6981da9bc)

**To Reproduce**
Follow the install guide in the wiki.

**Expected behavior**
Cards loading like in the default dashboard.
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/42326001/e904481c-2eab-4912-8c16-b9d4e3814708)

**Screenshots**
Lovelace resources :
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/42326001/44347a73-e7d3-4baf-9d84-a5a155022417)

Integration config :
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/42326001/c86e1000-41ce-4795-acea-2f14bfd1a2ca)

**Additional context**
Tried uninstall and reinstall the integration but still the same issue.

**Comment by basbruss** [comment]
That's not a bug but are the placeholders from the grid the adaptive dashboard uses.

All is working as it should 😉
