### ISSUE TITLE
Button card template ‘card person info' is missing

### ISSUE THREAD

**Issue by MeepoKiki** [UI-Lovelace-Minimalist/UI#1353]
**Describe the bug**

**To Reproduce**

1. Copy yaml from WIKI
2. Create folder custom_card_person_info inside custom_cards folder.
3. Create file custom_card_person_info.yaml inside the previous steps folder.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yannik2480** [comment]
+1
