### ISSUE TITLE
Change icon based on light state

### ISSUE THREAD

**Issue by JueK3y-Prv** [UI-Lovelace-Minimalist/UI#1365]
**Affected card:**
- Light Card

**Requested feature:**
Adding the possibility to change the light icon depending on the state.
For example: "mdi:lightbulb" for lights off and "mdi:lightbulb-outline" for lights on.

This is already possible in the custom card "Room" by Everything Smart Home.

**Comment by basbruss** [comment]
You already can by templating the variable.
```yaml
variables:
  ulm_card_light_icon: "[[[ return entity.state == 'on' ? 'mdi:lightbulb-outline' : 'mdi:lightbulb']]]"
