### ISSUE TITLE
UI crashes on mobile but not on desktop

### ISSUE THREAD

**Issue by norimicry** [UI-Lovelace-Minimalist/UI#1372]
**Describe the bug**
When using the minimalist ui on mobile, the app goes into a crashing loop but works fine on desktop. Not consistent, sometimes able to work for a bit after a restart but ends up back in a loop after a short time. I’m not sure if it’s a specific card causing the issue. Only using 3 custom cards, esh_welcome, esh_room, and camera_card. 

*To Reproduce**

1. Install minimalist UI
2. Navigate to mobile app with minimalist dashboard

**Expected behavior**
UI to work the same as desktop

**Screenshots**

https://github.com/UI-Lovelace-Minimalist/UI/assets/46500116/f3e5e3bd-0aec-4294-8e09-31e4a9bb999d

![Screenshot 2023-09-13 181328](https://github.com/UI-Lovelace-Minimalist/UI/assets/46500116/bafeb37f-de92-4ea0-9339-40110739700b)

**Additional context**

**Comment by norimicry** [comment]
found an error in a card

**Comment by pragyamishra56** [comment]
@norimicry 
Sir could you please assign me this issue it would be my first contributions
