### ISSUE TITLE
card_vertical_button icon position is not correct

### ISSUE THREAD

**Issue by inancatil** [UI-Lovelace-Minimalist/UI#1375]
Just the title. Code and output is as below:

![Web capture_20-9-2023_162554_192 168 1 2](https://github.com/UI-Lovelace-Minimalist/UI/assets/29947095/53f8a411-e255-4865-888b-d85a9ef89f44)
 
 
![Web capture_20-9-2023_162516_192 168 1 2](https://github.com/UI-Lovelace-Minimalist/UI/assets/29947095/b7a0d8c8-b579-4834-9b16-d45d91a0f9c2)

**Comment by basbruss** [comment]
Icon position seems correct?

**Comment by inancatil** [comment]
> Icon position seems correct?

It is positioned horizontally in the wiki.

![Screenshot_20230920_164421_Samsung Internet.jpg](https://github.com/UI-Lovelace-Minimalist/UI/assets/29947095/765bff33-b9d0-44e3-b5eb-07f4c32a52c2)

**Comment by basbruss** [comment]
That's obviously wrong 😓 , hence the vertical_button_card.

**Comment by wilbiev** [comment]
Cleaning-up issue list. Let me know when this issue needs to be reopened.
