### ISSUE TITLE
Cards don't render "template ... is missing"

### ISSUE THREAD

**Issue by gabi1324** [UI-Lovelace-Minimalist/UI#1376]
**Describe the bug**
I just configured this integration in HA, but I can't manage to make the cards render. Default and custom cards say "template ... is missing".

**Expected behavior**

**Screenshots**
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/61083655/e3f655a3-55ff-4192-ab84-e73e631adaf8)

![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/61083655/bc435a84-d7e6-46f8-a0b3-e4e02147f2c6)

**Additional context**
Setting the integration to download the custom cards I selected doesn't work, nor does adding the custom card yaml and translation in the custom cards folder. 
I downloaded all of the required cards from HACS before downloading "Ui-Lovelace-Minimalist" from HACS.

**Comment by jwardle** [comment]
Seeing the same issue with my standard HACS installation as well, however for the "card_light" template

**Comment by szelag-michal** [comment]
same here also for "card_light" template

**Comment by ahattink** [comment]
![afbeelding](https://github.com/UI-Lovelace-Minimalist/UI/assets/54348036/4c3d9bbe-ccaf-4f76-bf50-7bf4c2859bca)
Same here with thermostat cards.

**Comment by trwy7** [comment]
Same here with all of my cards

**Comment by wilbiev** [comment]
Cleaning-up issue list. Let me know when this issue needs to be reopened.
