### ISSUE TITLE
ui doesn't load correctly

### ISSUE THREAD

**Issue by Luke001IT** [UI-Lovelace-Minimalist/UI#1377]
**Describe the bug**
Minimalist dashboard does't load correctly 

**Screenshots**
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/64697208/7e9c553b-04d8-4a51-b5f9-0f4c13ec3323)

**Comment by peterjohan52** [comment]
There are no colors.

**Comment by basbruss** [comment]
You need to select the theme in your user profile

**Comment by peterjohan52** [comment]
Works now. Thanks.
