### ISSUE TITLE
minimalist-ios-tapbar theme: bar is at top of screen in 2023.10

### ISSUE THREAD

**Issue by finder39** [UI-Lovelace-Minimalist/UI#1382]
**Describe the bug**
It seems that the minimalist-ios-tapbar theme broke with the latest HA release.

**To Reproduce**
Be on:
- HA: 2023.10.0
- Minimalist: v1.3.6
- Theme: minimalist-ios-tapbar

**Expected behavior**
The bar should be at the bottom of the view like it is in 2023.9.x

**Screenshots**
![IMG_0124](https://github.com/UI-Lovelace-Minimalist/UI/assets/518673/3b3b7944-ea11-4173-8e09-23f2e22ff73d)

**Comment by finder39** [comment]
It seems to have fixed itself ¯\_(ツ)_/¯

**Comment by basbruss** [comment]
Actually it was fixed by https://github.com/thomasloven/lovelace-card-mod/releases/tag/3.2.3

Which is only downloadable after ha is upgraded to 2023.10.x

**Comment by finder39** [comment]
@basbruss looks like it's back up top for me. Is it a problem with card-mod and not minimalist ui?

**Comment by basbruss** [comment]
Cache?

**Comment by finder39** [comment]
Yup that worked
