### ISSUE TITLE
Android 14 Color Issues

### ISSUE THREAD

**Issue by 7uAip6** [UI-Lovelace-Minimalist/UI#1390]
**Describe the bug**
Installing the Home Assistant app on an Android 14 device with a different color palette chosen on the OS level results in unusable colors for Lovelace cards.  When I created my dashboard, I did not modify any colors originally and that is what is shown on OldDevice.jpg.  I'm hoping there's a way to fix the issue from a lovelace perspective?  The non-lovelace dashboards look the same on both devices.

![Old_Device](https://github.com/UI-Lovelace-Minimalist/UI/assets/86699865/7f610e37-0d15-453f-ab0c-5e2296493f10)
![New_Device](https://github.com/UI-Lovelace-Minimalist/UI/assets/86699865/54fba08b-51fa-4930-99bc-9dafd8007b4f)

**Comment by paulbuechner** [comment]
I had a similar problem today. This is not related to Android Theming. 

Based on your screenshots I assume that the HACS installed plugin resources aren't properly linked to your dashboards... (Settings -> Dashboards -> "3 dots" -> Resources)

When downloading a plugin HACS reminds you to link this resources when you using Lovelace in Edit-Mode. The resource path for each plugin is shown the the download modal.

Hope this helps!

**Comment by 7uAip6** [comment]
> I had a similar problem today. This is not related to Android Theming.
> 
> Based on your screenshots I assume that the HACS installed plugin resources aren't properly linked to your dashboards... (Settings -> Dashboards -> "3 dots" -> Resources)
> 
> When downloading a plugin HACS reminds you to link this resources when you using Lovelace in Edit-Mode. The resource path for each plugin is shown the the download modal.
> 
> Hope this helps!

Thanks Paul, but unfortunately I'm still confused.  Do I do this from my mobile device?  If so, I did and I get a list of things, but I'm not really sure what to be looking for.

**Comment by basbruss** [comment]
Each device/browser/user needs to set the correct theme so it's saved in the cookies.
Because you installed the app on a (new) device you will need to go in the HA app to the user-profile and select one of the minimalist themes.

This is also explained in the FAQ https://ui-lovelace-minimalist.github.io/UI/troubleshooting/troubleshooting/

**Comment by 7uAip6** [comment]
> Each device/browser/user needs to set the correct theme so it's saved in the cookies. Because you installed the app on a (new) device you will need to go in the HA app to the user-profile and select one of the minimalist themes.
> 
> This is also explained in the FAQ https://ui-lovelace-minimalist.github.io/UI/troubleshooting/troubleshooting/

Thank you good sir!
