### ISSUE TITLE
Dashboard not working after HA2023.11.0 upgrade

### ISSUE THREAD

**Issue by wokkeltje13** [UI-Lovelace-Minimalist/UI#1394]
Most of the buttons and items are not showing after I did the upgrade to HA core 2023.11.0

No idea where to find logs. Can't see anything new related to Minimalist

**Comment by finder39** [comment]
Same here. I downgraded to 2023.10.5 for now with no problems as a temporary fix

**Comment by sMauldaeschle** [comment]
I have the same issue here. I haven't been able to figure out a pattern, which elements are not working anymore.

**Comment by basbruss** [comment]
Probably a card-mod issue.

**Comment by dahlbergc** [comment]
> Probably a card-mod issue.
> 
> Multiple beta testers had frontend issues due to card mod according the discord beta channel

I couldn't find anything related to 2023.11 issues at the card-mod git.  Unfortunately, HomeAssistant logs aren't spitting out anything useful as to the cause of the ui-minimalist display issue.

**Comment by basbruss** [comment]
Does the developers page (f12) show something useful?

**Comment by christopherdopp** [comment]
I am having what I believe is the same problem. I am seeing the following in the console multiple times:

```
button-card.js:426 ButtonCardJSTemplateError: TypeError: Cannot read properties of undefined (reading 'match') in 'var number = hass.resources[hass['language']]["ui.duration.hour"];
  var matches = number.match(/[...'
    at Ti.eval (eval at _evalTemplate (button-card.js:434:2161), <anonymous>:5:24)
    at Ti._evalTemplate (button-card.js:434:2257)
    at Ti._getTemplateOrValue (button-card.js:434:2877)
    at Ti._objectEvalTemplate (button-card.js:434:2586)
    at button-card.js:426:19432
    at Array.forEach (<anonymous>)
    at Ti.render (button-card.js:426:19389)
    at Ti.update (button-card.js:1:14818)
    at Ti.performUpdate (button-card.js:1:6145)
    at Ti.scheduleUpdate (button-card.js:1:5792)
```

**Comment by christopherdopp** [comment]
> Same here. I downgraded to 2023.10.5 for now with no problems as a temporary fix

What is the best way to downgrade the core version? I haven't had to do that before. Do I restore a backup or enter a CLI command?

**Comment by wokkeltje13** [comment]
i did a restore in the GUI of the backup created during the 2023.11 upgrade (took almost half an hour for a 2GB DB)

**Comment by dahlbergc** [comment]
> What is the best way to downgrade the core version? I haven't had to do that before. Do I restore a backup or enter a CLI command?

from the CLI, enter the following command:

`ha core update --version 2023.10`

**Comment by msl2424** [comment]
Same issue since updating to 2023.11.0. Many of my UI Lovelace Minimalist dashboard elements showed an error message similar to what @christopherdopp pasted, and then after refreshing the page, those elements just no longer showed at all.

**Comment by kblin** [comment]
As a quick workaround, I went into my `custom_components/ui_lovelace_minimalist/ulm_templates/default.yml` file and in the `ulm_translation_hour` and `ulm_translation_hours` settings changed the line `var matches = number.match(/[^{\}]+(?=})/g);` to `var matches = number?.match(/[^{\}]+(?=})/g);` (note the extra `?` after `number). That still won't get me the right translation for "hour" and "hours", but it gets rid of the error so all my cards show up again.

**Comment by owiebaclay** [comment]
> As a quick workaround, I went into my `custom_components/ui_lovelace_minimalist/ulm_templates/default.yml` file and in the `ulm_translation_hour` and `ulm_translation_hours` settings changed the line `var matches = number.match(/[^{\}]+(?=})/g);` to `var matches = number?.match(/[^{\}]+(?=})/g);` (note the extra `?` after `number`). That still won't get me the right translation for "hour" and "hours", but it gets rid of the error so all my cards show up again.

Thank you for this quick workaround. This fix will do for the time being. Thanks again.

**Comment by basbruss** [comment]
@kblin @owiebaclay release 1.3.7 https://github.com/UI-Lovelace-Minimalist/UI/releases/tag/v1.3.7 also includes a fix. Could you test that? I didn't have any problems before so are not able to tell if it works

**Comment by kblin** [comment]
Hm, interesting, I did check HACS for updates before, but I had to manually refresh to see the 1.3.7 version.
Anyway, I can confirm that I also don't have any issues with 1.3.7 (after having rolled back my workaround to confirm things were broken again).

**Comment by basbruss** [comment]
@kblin Thanks.
That's because I released the fix just moments before you made your initial comment. HACS looks for updates once a day for updates, or when ha is restarted, or when you manually click on update information``

**Comment by kblin** [comment]
I figured, thanks for the rapid fix. 👍

**Comment by owiebaclay** [comment]
> @kblin @owiebaclay release 1.3.7 https://github.com/UI-Lovelace-Minimalist/UI/releases/tag/v1.3.7 also includes a fix. Could you test that? I didn't have any problems before so are not able to tell if it works

Installed the new update and everything works fine. Thank you for your work.

**Comment by diegocade1** [comment]
after fix, almost everything is now visible, only error I'm getting is:

`Type Error: e,trim is not a function
[Error dumping[object Object]]`

card shows a date

**Comment by markmghali** [comment]
Same, upgraded to 1.3.7 fixed the overall issue just have 2 cards with the same error 

Type Error: e.trim is not a function [Error dumping[object Object]]

**Comment by rcflores84** [comment]
I upgraded to 1.3.7 and my cards are still not showing up.  I also couldn't find ulm_translation_hour and ulm_translation_hours in my default.yaml file.

**Comment by KeeganWooten** [comment]
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/66805023/3af1cbad-f431-4d75-9fe1-66fd505d3c8d)

Upgraded to 1.3.7 as well, also HA 2023.11.0 and have cards not displaying. I see no error call outs, as though the cards are displaying "correctly" just invisible.

**Comment by KeeganWooten** [comment]
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/66805023/2f97a55c-dad8-49e1-99a8-de94cdc970cd)

I was able to get cards to begin appearing by commenting out the associated entity in the configuration of that card. This has only worked so far on cards that can generate without an entity, like room cards. For example:

Working:
`    - type: 'custom:button-card'
      template:
        - card_room
        - yellow_on
      name: Basement
      # entity: light.basement
      icon: hue:room-stairs
      tap_action:
        action: toggle
      hold_action:
        action: navigate
        navigation_path: 'basement'
      variables:
        label_use_temperature: false
        label_use_brightness: true`


Not Working:
`    - type: 'custom:button-card'
      template:
        - card_room
        - yellow_on
      name: Basement
      entity: light.basement
      icon: hue:room-stairs
      tap_action:
        action: toggle
      hold_action:
        action: navigate
        navigation_path: 'basement'
      variables:
        label_use_temperature: false
        label_use_brightness: true`


But neither 
`      - type: "custom:button-card"
        template: card_light
        # entity: light.lvg_w_r`

Nor this:
`      - type: "custom:button-card"
        template: card_light
        entity: light.lvg_w_r`

display at all, remaining "invisible." Hopefully this information helps track down the issue

**Comment by KeeganWooten** [comment]
This issue seems to have been fixed with 2023.11.1.

**Comment by diegocade1** [comment]
> This issue seems to have been fixed with 2023.11.1.

not yet, if the card doesnt show up,  it shows an error

![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/46531987/b7a8995c-dc39-4d87-bc61-95d822c74851)

**Comment by KeeganWooten** [comment]
I was referring to the invisible cards not reading the entity. 

Although what I was referring to seems to have stop occuring on mobile app, it is occuring still on the web browser.

**Comment by perezrojose** [comment]
Hello, I have the same error that my buttons does not appear, checking the “\config\custom_components\” folder, the “_ui_lovelace_minimalist_” folder is missing, which contains all the templates. I copied the folder from version 1.3.6 to this version and everything came back, I think it is an error due to missing update files

**Comment by KeeganWooten** [comment]
My "ui_lovelace_minimaist" folder is still present and accounted for. I have noticed that I am only able to see the cards when I connect locally and on mobile. If I connect through my domain on mobile, or through either local or domain on desktop, the cards remain invisible until I comment out the primary entity.

**Comment by rcflores84** [comment]
I had two room cards that weren't working.  Both of those room cards had a cover entity shown.  I commented those out and the room cards started working again.

**Comment by KeeganWooten** [comment]
> > I have noticed that I am only able to see the cards when I connect locally and on mobile.
> 
> Same thing for me. No clue why.
> 
> The problems persists after updating to the recent version of everything. I can only see room cards, navigation cards, and graph cards (without title). Any light cards, binary sensor cards, time cards, switch cards, etc are missing.

I was able to fix this on all my devices by clearing the cache of both the local address and domain address in the respective browser. For my mobiles, I uninstalled the app, and reinstalled. **Important note**: I fixed it on 2 apps, but I had to do it twice on one because I set it back up while connected to the same network as the HA server, so it seemed to just grab the cache again. You need to set it up while connected to a _different network_ (whether that's data or a different wifi). For desktop, I opened up 2 tabs, one local connection and one domain, cleared cookies and cache, closed the browser, then opened it back up and connected to the domain first. This fixed all my problems. My guess is that my server UI was cached on all these devices in the original 1.3.6/2023.11.0 broken configuration. Removing a primary entity on a card corrected it, and so it was "redrawn" but when reintroducing the primary entity, it just grabbed the cached UI which was broken (just my theory). Hope this helps some people get their dashboards back!

**Comment by jymdman** [comment]
> > > I have noticed that I am only able to see the cards when I connect locally and on mobile.
> > 
> > 
> > Same thing for me. No clue why.
> > The problems persists after updating to the recent version of everything. I can only see room cards, navigation cards, and graph cards (without title). Any light cards, binary sensor cards, time cards, switch cards, etc are missing.
> 
> I was able to fix this on all my devices by clearing the cache of both the local address and domain address in the respective browser. For my mobiles, I uninstalled the app, and reinstalled. **Important note**: I fixed it on 2 apps, but I had to do it twice on one because I set it back up while connected to the same network as the HA server, so it seemed to just grab the cache again. You need to set it up while connected to a _different network_ (whether that's data or a different wifi). For desktop, I opened up 2 tabs, one local connection and one domain, cleared cookies and cache, closed the browser, then opened it back up and connected to the domain first. This fixed all my problems. My guess is that my server UI was cached on all these devices in the original 1.3.6/2023.11.0 broken configuration. Removing a primary entity on a card corrected it, and so it was "redrawn" but when reintroducing the primary entity, it just grabbed the cached UI which was broken (just my theory). Hope this helps some people get their dashboards back!

Thank you @KeeganWooten !

Reinstalling homeassistant app on my mobile device fixed the invisible card problem.

**Comment by LukasPoque** [comment]
Do you happen to have any updates on this? All my binary sensor cards have disappeared too.

**Comment by seanm581** [comment]
still having this issue with binary sensor cards
