### ISSUE TITLE
Changes made to yaml reset after restart

### ISSUE THREAD

**Issue by ATaylor5596** [UI-Lovelace-Minimalist/UI#1405]
When I makes changes to the .yaml of certain cards the changes are applied but are removed if I restart home assistant. I changed some lines for font and color on certain cards and those changes are still applied after a restart, but when changes are made to other cards, in this case specifically the alarm chip card and the persons card, any and all changes are removed if you restart home assistant. Manually saving in VSC doesn't seem to work either.

Correction, any changes I made to .yaml don't save. I added new color values to the themes folder and they are also gone after a restart.

**Comment by basbruss** [comment]
Have you read this?
<img width="959" alt="image" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/68892092/bd9e1f12-c390-4492-8bbc-eef57138aacc">
https://ui-lovelace-minimalist.github.io/UI/setup/custom_cards/#custom-cards

**Comment by ATaylor5596** [comment]
Out of all the reading I did looks like that's the one thing I glossed over. Unfortunate.
