### ISSUE TITLE
Some words missing in translation

### ISSUE THREAD

**Issue by misa1515** [UI-Lovelace-Minimalist/UI#1422]
**Describe the bug**
Missing words in translation (screenshot attached).

**Expected behavior**
Please add missing words to translation.

**Screenshots**
Attached.

![1701699066019](https://github.com/UI-Lovelace-Minimalist/UI/assets/61636045/22b36090-7f25-40aa-a258-cf4cc4914e26)

**Comment by wilbiev** [comment]
Translation file sk.json is up-to-date.
