### ISSUE TITLE
TyppeError: Reading macth - HA 2023.12.1

### ISSUE THREAD

**Issue by tv4you2016** [UI-Lovelace-Minimalist/UI#1425]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**

Hello, I just updated my HA to version 2023.12.1 and this error appears using the minimalist lovelace ui.

**Version of the card**
Version: 4.1.1

**Screenshots**

> **version HA 2023 11 03**

![2023 11 03](https://github.com/custom-cards/button-card/assets/83761813/f45b8423-52a7-4808-aa80-a9095742d018)

> **version HA 2023 12 01**
![2023 12 01](https://github.com/custom-cards/button-card/assets/83761813/137777d4-d3f4-4467-9c04-7c82eea23458)

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [Version 120.0.6099.71 (64 bits)]

**Comment by basbruss** [comment]
Update to the latest minimalist release 😉

**Comment by tv4you2016** [comment]
Solved
