### ISSUE TITLE
Wrong folder structure custom_light_cards

### ISSUE THREAD

**Issue by basbruss** [UI-Lovelace-Minimalist/UI#143]
**Describe the bug**
@CM000n Hi I noticed my PR has a wrong folder structure. The new changes are inside the old folder without deleting the old files from release 1.0.0
```
config
  └── minimalist-templates
     └── custom_card_light_color
        └── custom_card_light_color.yaml ## can be delete
        └── readme.md ## can be delete
        └── custom_card_light_color ### this is the folder with release 1.0.1
          └── custom_card_light_color.yaml
          └── readme.md
     └── button_card_templates.yaml
     └── EN.yaml
```
I have made a PR with the right structure to the main branch. Could you approve it so users willing to update can use the right files? #144

**Comment by CM000n** [comment]
Hi @basbruss, I just merged your hotfix to main now.
