### ISSUE TITLE
[PR AVAILABLE] custom_card_mpse_printer/custom_card_bar_card/custom_card_sisimomo_printer not compatible with card_mod v3.4.0+

### ISSUE THREAD

**Issue by tieskuh** [UI-Lovelace-Minimalist/UI#1435]
**Describe the bug**
Card mod has a breaking change in v3.4.0: https://github.com/thomasloven/lovelace-card-mod/releases/tag/v3.4.0
custom_card_mpse_printer didn't implement that yet.

**To Reproduce**
Style is not applied, card doesn't look like it should.

**Screenshots**
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/115901851/3cf99b92-e8e7-49c2-b577-759577d0e5f0)

**Fix for the issue**
https://github.com/UI-Lovelace-Minimalist/UI/pull/1432

**Comment by Luke15153** [comment]
This problem affects at least these two cards too:
 - custom_cards/custom_card_bar_card
 - custom_cards/custom_card_sisimomo_printer

Same solution, just add card_mod: as parent of style:

**Comment by Liionboy** [comment]
Problem is with all card with bar:

![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/87735636/78c7f825-62f2-45fe-90f2-6738cd628e0f)

**Comment by tieskuh** [comment]
Fix for custom_cards/custom_card_bar_card:
https://github.com/UI-Lovelace-Minimalist/UI/pull/1437

Fix for custom_cards/custom_card_sisimomo_printer
https://github.com/UI-Lovelace-Minimalist/UI/pull/1438

@Liionboy Which card is that?

**Comment by Liionboy** [comment]
Is custom_card_bar_card

**Comment by tieskuh** [comment]
Not much going on in the minimalist github....
If you are still facing the problem, the easiest way is to revert to card-mod 3.3.1 via HACS until the PR is approved.

![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/115901851/d1ae18ec-b5e7-4046-84a6-8860ab41de18)
