### ISSUE TITLE
Failed to setup on HA Core 2024.1.2

### ISSUE THREAD

**Issue by AlbertoKarakoutev** [UI-Lovelace-Minimalist/UI#1441]
**Describe the bug**
Lovelace fails to be set up. Error logs show timeouts to GitHub when fetching custom cards. After 20 seconds, the integration setup fails.

**To Reproduce**

1. Update to HA Core 2024.1.2
2. Observe issue 

**Expected behavior**
Lovelace should be set up

**Screenshots**

**Additional context**
All dashboards are not showing up, but the YAMLs are still there. Downgrading to HA Core 2024.1.1 fixed the problem.

**Related Logs** (can be found in the browser-console (F12))
- 

**Related Card Config**
-

**Comment by Ruu-D** [comment]
I have the same problem.

**Comment by seaton88** [comment]
Same issue here

**Comment by AlbertoKarakoutev** [comment]
Mkay, seems like HA auto-updated upon restart even though I skipped the update. Also, it didn't create a backup even though I have specifically told it to do so before every update. Real bummer. Anyway, at least I can post an error log now from Lovelace:

```
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 08:50:42 (1 occurrences)
Last logged: 08:50:42

Error setting up entry UI Lovelace Minimalist for ui_lovelace_minimalist
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 124, in async_setup_entry
    return await async_initialize_integration(hass=hass, config_entry=config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 104, in async_initialize_integration
    startup_result = await async_startup()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 90, in async_startup
    await ulm.configure_community_cards()
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 285, in configure_community_cards
    language_files = await self.async_github_get_tree(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 183, in async_github_get_tree
    response = await self.async_github_api_method(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 216, in async_github_api_method
    raise Exception(_exception)
Exception: Timeout of 20 reached while waiting for https://api.github.com/repos/UI-Lovelace-Minimalist/UI/contents/custom_cards/custom_card_eraycetinay_lock/languages

```

**Comment by AlbertoKarakoutev** [comment]
Fixed with HA Core 2024.1.3, closing

**Comment by AlbertoKarakoutev** [comment]
Bug reappeared with HA Core 2024.1.3

**Comment by JoaquinDillen** [comment]
I have the same problem, a couple of weeks ago updated the HA Core, but all the cards failed to load, i was able to go back to a backup. Yesterday i tried again and the issue continues...  ![8d4673f416801ab763818c27225587bed6c08e8a](https://github.com/UI-Lovelace-Minimalist/UI/assets/36713733/a2c14b48-2c44-42fe-9833-600043a4f97d)

**Comment by AlbertoKarakoutev** [comment]
Tip (for my case at least): disabling and re-enabling the Lovelace integration a couple of times seems to fix the issue.

**Comment by Vib1240n** [comment]
Having the same issue on Home assistant 2024.1.5. Tried disabling and enabling multiple times and no success. 

Core: 2024.1.5
Supervisor: 2023.12.1
Operating System: 11.4

**Comment by cactusbob** [comment]
I'm having the same issues as Vib1240n

Core: 2024.1.5
Supervisor: 2023.12.1

**Comment by orgebar** [comment]
Also same behaviour core-2024.1.6.
Home Assistant OS 11.5
supervisor-2023.12.1

Issue was the same with 2024.1.5. and I believe 2024.1.4. also. I tried reinstalling the integration a couple times within the last 2-3 weeks, but after a short time it fails to load again.

**Comment by Manbearpig92** [comment]
weirdest thing, the dashboard works on a desktop  but not on the mobile device

**Comment by Manbearpig92** [comment]
This worked for me: create a new room and restart home assistant. after doing this all my old cards were functioning as expected. I then commented out the new card I made and restarted home assistant. Everything has been working great so far.... Knock on wood
