### ISSUE TITLE
UI Lovelace Minimalist Failed to setup after Restart

### ISSUE THREAD

**Issue by Vib1240n** [UI-Lovelace-Minimalist/UI#1449]
Encountered Bug when clean installing UI Lovelace Minimalist. Not sure if I'm missing any code in my configuration.yaml but after I manually installed and followed directions to install this integration, I encountered the error `custom element doesn't exist grid-layout` in adaptive dashboard, restarted HA and now seeing the error under "Devices and Services" in UI Lovelace Minimalist integration "UI Lovelace Minimalist Failed to Set up". 

1. Follow either manual or HACS installation method and install Integration
2. After installing, view default provided dashboard for any errors (`Custom element doesn't exist: grid-layout`
3. Restart Home assistant, wait for integration to initialize.

**Expected behavior**
Should initialize properly with all custom components loaded. 

**Screenshots**
![Screenshot 2024-01-25 at 4 30 57 PM](https://github.com/UI-Lovelace-Minimalist/UI/assets/71455013/ac9522c8-4aba-4d92-a68f-b95b227a0c6d)

**Additional context**
Here are the logs from HA-
```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 124, in async_setup_entry
return await async_initialize_integration(hass=hass, config_entry=config_entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 104, in async_initialize_integration
startup_result = await async_startup()
^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 90, in async_startup
await ulm.configure_community_cards()
File "/config/custom_components/ui_lovelace_minimalist/base.py", line 280, in configure_community_cards
content=await self.async_github_get_file(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ui_lovelace_minimalist/base.py", line 178, in async_github_get_file
return decode_content(response.data.content)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ui_lovelace_minimalist/utils/decode.py", line 7, in decode_content
return b64decode(bytearray(content, "utf-8")).decode()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

```configuration.yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: storage
```

**Comment by duanemck** [comment]
I'm seeing this now but not after a fresh installation. 
I had to hard reboot my Pi and after HA is finished starting up, UI-Lovelace-Minimalist fails to setup. 
I have seen this occasionally in the past and normally an HA restart fixes it but that doesn't seem to be working this morning. 

HA: 2024.1.1
UI-Lovelace-Minimalist: 1.3.9

**Comment by duanemck** [comment]
> I'm seeing this now but not after a fresh installation. I had to hard reboot my Pi and after HA is finished starting up, UI-Lovelace-Minimalist fails to setup. I have seen this occasionally in the past and normally an HA restart fixes it but that doesn't seem to be working this morning.
> 
> My logs show that it's timing our fetching something from github, the specific URL seems to be different on each restart but if I curl the URL from the PI I'm getting responses instantly.
> 
> e.g: `Exception: Timeout of 20 reached while waiting for https://api.github.com/repos/UI-Lovelace-Minimalist/UI/contents/custom_cards/custom_card_httpedo13_sun`
> 
> HA: 2024.1.1 UI-Lovelace-Minimalist: 1.3.9

Upgrading to HA 2024.1.5 seems to have fixed this for me

**Comment by Vib1240n** [comment]
> > I'm seeing this now but not after a fresh installation. I had to hard reboot my Pi and after HA is finished starting up, UI-Lovelace-Minimalist fails to setup. I have seen this occasionally in the past and normally an HA restart fixes it but that doesn't seem to be working this morning.
> > My logs show that it's timing our fetching something from github, the specific URL seems to be different on each restart but if I curl the URL from the PI I'm getting responses instantly.
> > e.g: `Exception: Timeout of 20 reached while waiting for https://api.github.com/repos/UI-Lovelace-Minimalist/UI/contents/custom_cards/custom_card_httpedo13_sun`
> > HA: 2024.1.1 UI-Lovelace-Minimalist: 1.3.9
> 
> Upgrading to HA 2024.1.5 seems to have fixed this for me

I upgraded to 2024.1.6 and it restarted the HA and it failed to load. Even after restart and rebooting Pi multiple times, nothing seems to be working. I don't want to do a fresh installation again but it is kind of annoying that I haven't been able to find any solution or direction nor have I heard from anyone from the Dev team.

**Comment by orgebar** [comment]
> > > I'm seeing this now but not after a fresh installation. I had to hard reboot my Pi and after HA is finished starting up, UI-Lovelace-Minimalist fails to setup. I have seen this occasionally in the past and normally an HA restart fixes it but that doesn't seem to be working this morning.
> > > My logs show that it's timing our fetching something from github, the specific URL seems to be different on each restart but if I curl the URL from the PI I'm getting responses instantly.
> > > e.g: `Exception: Timeout of 20 reached while waiting for https://api.github.com/repos/UI-Lovelace-Minimalist/UI/contents/custom_cards/custom_card_httpedo13_sun`
> > > HA: 2024.1.1 UI-Lovelace-Minimalist: 1.3.9
> > 
> > 
> > Upgrading to HA 2024.1.5 seems to have fixed this for me
> 
> I upgraded to 2024.1.6 and it restarted the HA and it failed to load. Even after restart and rebooting Pi multiple times, nothing seems to be working. I don't want to do a fresh installation again but it is kind of annoying that I haven't been able to find any solution or direction nor have I heard from anyone from the Dev team.

Same here. I even tried reinstalling a couple times, but after a short time the integration fails to load again.

**Comment by dsvirdiau** [comment]
I have to same issue. Reinstalled from start a couple of times. Won't install custom cards even after checking the box

**Comment by dsvirdiau** [comment]
`Error setting up entry UI Lovelace Minimalist for ui_lovelace_minimalist
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 442, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 124, in async_setup_entry
    return await async_initialize_integration(hass=hass, config_entry=config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 104, in async_initialize_integration
    startup_result = await async_startup()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 90, in async_startup
    await ulm.configure_community_cards()
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 280, in configure_community_cards
    content=await self.async_github_get_file(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 178, in async_github_get_file
    return decode_content(response.data.content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/utils/decode.py", line 7, in decode_content
    return b64decode(bytearray(content, "utf-8")).decode()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte`

**Comment by Vib1240n** [comment]
So, I think I found a workout for this. I disabled the integration, then re-enabled it which triggered to configure it again. When re-configuring it, I turned off "require github authentication for community card" and clicked finish and that seemed to start it up properly and I can view all my dashboards again. I had to manually add all the cards that I'm using in my dashboard under /ui_lovelace_minimalist/custom_cards/ and then all my cards showed up properly. 

So there is some issue that's happening after a restart where I believe minimalist UI isn't able to re authenticate with github and it fails to load up the integration.

**Comment by orgebar** [comment]
> So, I think I found a workout for this. I disabled the integration, then re-enabled it which triggered to configure it again. When re-configuring it, I turned off "require github authentication for community card" and clicked finish and that seemed to start it up properly and I can view all my dashboards again. I had to manually add all the cards that I'm using in my dashboard under /ui_lovelace_minimalist/custom_cards/ and then all my cards showed up properly. 
> 
> 
> 
> So there is some issue that's happening after a restart where I believe minimalist UI isn't able to re authenticate with github and it fails to load up the integration. 

Thanks! This worked for me too.

Any guesses why the github connection causes this? For me it was a real pain to get it connected to github in the first place. All attempts from an iPhone failed and from PC it worked right away. Could it be an issue with the iOS app?
