### ISSUE TITLE
Mobile theme not working as expected

### ISSUE THREAD

**Issue by mdchaudhari** [UI-Lovelace-Minimalist/UI#1458]
**Describe the bug**
The 'minimalist-mobile' theme does not enable kiosk mode (i.e. hide hamburger icon navigation, etc.)

**To Reproduce**

1. Go to your profile
3. Scroll down to 'Theme'
4. Select 'minimalist-mobile'
5. Go to dashboard and see that navigation is still present

**Expected behavior**
Phone enters kiosk mode with most navigation (e.g. hamburger icon) hidden

**Screenshots**
![Screenshot_20240215-094218](https://github.com/UI-Lovelace-Minimalist/UI/assets/8600943/678395c6-fdce-4aa0-b9ab-ec6b1786dca5)

**Comment by wilbiev** [comment]
Cleaning-up old issues from the list. Let me know when this issue needs to be re-opened.
