### ISSUE TITLE
Thermostat card does not handle cooling

### ISSUE THREAD

**Issue by mp-se** [UI-Lovelace-Minimalist/UI#147]
The thermostat card only changes color if heating. Adding this code will also highlight cooling mode. I've tested this and it works fine. 

card_thermostat:
----
    - operator: "template"
      value: >
        [[[
          return entity.state == 'cool'
        ]]]
      styles:
        icon:
          - color: "rgba(var(--color-blue),1)"
        img_cell:
          - background-color: "rgba(var(--color-blue),0.2)"
        card:
          - background-color: "rgba(var(--color-background-blue),var(--opacity-bg))"
        name:
          - color: "rgba(var(--color-blue-text),1)"
        label:
          - color: "rgba(var(--color-blue-text),1)"

**Comment by httpedo13** [comment]
where did you add this code?

**Comment by mp-se** [comment]
it should go under state: 

I belive there is an state template for "heat" but no for "cool"

**Comment by httpedo13** [comment]
Yes, it can be adapted, but I don't think it's enough to just change that

**Comment by mp-se** [comment]
you are right, it depends on what the intent is with the card. showing status or controlling the thermostat. 

This will only make is show blue color when cooling mode is on. I believe it is showing red when heating mode is on. I created my own card that also can change the temperature which I'm using for my beer fridge. 

Perhaps we should look into what would be needed/expected and combine efforts into one standard card ? We could continue this thread in discussions or on discord.
