### ISSUE TITLE
New Installation the UI doesn't show as expected.

### ISSUE THREAD

**Issue by andylow** [UI-Lovelace-Minimalist/UI#1472]
**Describe the bug**
UI doesn't show as expected on a brand-new installation.

**To Reproduce**
Follow HACS installation guide.

**Screenshots**
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/7241168/6e509488-9a8e-486c-9212-feed14d70341)

**Related Logs** (can be found in the browser-console (F12))
```
button-card.js?hacstag=146194325412:426  TypeError: e.trim is not a function
    at Ti._getTemplateOrValue (button-card.js?hacstag=146194325412:434:2813)
    at button-card.js?hacstag=146194325412:434:2770
    at Array.forEach (<anonymous>)
    at Ti._getTemplateOrValue (button-card.js?hacstag=146194325412:434:2747)
    at button-card.js?hacstag=146194325412:434:2770
    at Array.forEach (<anonymous>)
    at Ti._getTemplateOrValue (button-card.js?hacstag=146194325412:434:2747)
    at button-card.js?hacstag=146194325412:434:2770
    at Array.forEach (<anonymous>)
    at Ti._getTemplateOrValue (button-card.js?hacstag=146194325412:434:2747)
```

**Related Card Config**
No changes on original sample yaml configuration.

**Comment by andylow** [comment]
Captured console logs:
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/7241168/40cf0ed3-8f07-4bd7-96be-cbf3ac035c54)

**Comment by piotrkpaul** [comment]
+1, got the same issue

**Comment by tv4you2016** [comment]
Try updating all libs to the latest versions...

Required Integration[¶](https://ui-lovelace-minimalist.github.io/UI/setup/download/#required-integration)
[browser_mod](https://github.com/thomasloven/hass-browser_mod) by Thomas Lovén
Required Lovelace Resources[¶](https://ui-lovelace-minimalist.github.io/UI/setup/download/#required-lovelace-resources)
[button-card](https://github.com/custom-cards/button-card) by RomRider
[card-mod](https://github.com/thomasloven/lovelace-card-mod) by Thomas Lovén
[mini-graph-card](https://github.com/kalkih/mini-graph-card) by Karl Kihlström
[Mini Media Player](https://github.com/kalkih/mini-media-player) by Karl Kihlström
[My Cards Bundle](https://github.com/AnthonMS/my-cards) by AnthonMS**
[Light Entity Card](https://github.com/ljmerza/light-entity-card) by Leonardo Merza
[auto-entities](https://github.com/thomasloven/lovelace-auto-entities) by Thomas Lovén

**Comment by ipm79** [comment]
Turns out the above list is missing
layout-card
state-switch

As soon as these are installed via HACS it works.
see also https://github.com/UI-Lovelace-Minimalist/UI/issues/1047

**Comment by alexkahler** [comment]
I have the same issue. Elements are showing, but they don't look right. I have added layout-card and state-switch. I have both tried manually installing all dependencies, and also used the checkbox for having Lovelace install them for me.
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/15639915/fcfd39e6-a89e-47f7-b838-b08249b69cf0)

**Comment by sombody88** [comment]
Same here. New install.  Popup is even worse it is just text. 

layout-card and state-switch already.

![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/76803961/bac18128-8d50-4ea1-b4ea-fababd38c1fb)

**Comment by redb0** [comment]
I have a similar problem as in the previous message.
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/30475117/835605f9-d308-49e0-9b6e-1d8342df12da)

I've tried installing libraries automatically and manually. Has someone found a solution?

**Comment by pheliperocha** [comment]
Same here. Installed manually all dependencies, including layout-card and state-switch mentioned here.
Home Assistant Version: 2024.3.1

In the console I'm receiving the following errors, seems something related to button-card. I'm using v4.1.2

```
ButtonCardJSTemplateError: TypeError: Cannot read properties of undefined (reading 'ulm_show_last_changed') in 'if (typeof(entity) !== 'undefined' && entity !== undefined){
    let device_class = entity.attribu...'
    at ti.eval (eval at _evalTemplate (:8123/hacsfiles/button-card/button-card.js:425:9303), <anonymous>:10:18)
    at ti._evalTemplate (:8123/hacsfiles/button-card/button-card.js:425:9389)
    at ti._getTemplateOrValue (:8123/hacsfiles/button-card/button-card.js:425:9976)
    at :8123/hacsfiles/button-card/button-card.js:425:9869
    at Array.forEach (<anonymous>)
    at ti._getTemplateOrValue (:8123/hacsfiles/button-card/button-card.js:425:9846)
    at ti._objectEvalTemplate (:8123/hacsfiles/button-card/button-card.js:425:9685)
    at ti.render (:8123/hacsfiles/button-card/button-card.js:425:6853)
    at ti.update (:8123/hacsfiles/button-card/button-card.js:1:19873)
    at ti.performUpdate (:8123/hacsfiles/button-card/button-card.js:1:16761)
```

```
Uncaught (in promise) TypeError: e.setConfig is not a function
    at ti.render (button-card.js:425:7051)
    at ti.update (button-card.js:1:19873)
    at ti.performUpdate (button-card.js:1:16761)
    at ti._enqueueUpdate (button-card.js:1:16413)
```

**Comment by selfeky** [comment]
I have the exact same issue1

**Comment by gosoares** [comment]
I'm having the same issue!

**Comment by TrueTechy** [comment]
> I have the same issue. Elements are showing, but they don't look right. I have added layout-card and state-switch. I have both tried manually installing all dependencies, and also used the checkbox for having Lovelace install them for me. ![image](https://private-user-images.githubusercontent.com/15639915/311458503-fcfd39e6-a89e-47f7-b838-b08249b69cf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjk4OTQsIm5iZiI6MTcxMjI2OTU5NCwicGF0aCI6Ii8xNTYzOTkxNS8zMTE0NTg1MDMtZmNmZDM5ZTYtYTg5ZS00N2Y3LWI4MzgtYjA4MjQ5YjY5Y2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDIyMjYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NzllOWUzODM4OTY4MjMyNTJmOWVmNzg0MGIxMWQ5NWZhMjlkZmViOTNlNTljYTkxZTY2Njc4MGI4NTkyYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5_rE1L89xwb0KLMz7Zjxd_ft6bkRx7eiVh_vR8XAZlQ)

For this weird looking quirk I found that you had to change the theme your user is set to one of the minimalist-* ones instead of having it on default as mine was before
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/23321780/28206eee-ba6c-465d-acd5-4fb8caf15b6f)

**Comment by deantomasevic** [comment]
Same here.
everything is up2date.

**Comment by Vipale** [comment]
Same here, fresh install and everything up2date

**Comment by sparvalarva** [comment]
Yeah, same issue here. Looks even worse than yours.

**Comment by JaroslawPalczynski** [comment]
Same here.

**Comment by armandvanderwalt** [comment]
Same for me

**Comment by ncp1113** [comment]
I am having the same issue on new install using HACS. This shows up in the example view.
<img width="544" alt="Screen Shot 2024-08-07 at 11 33 27 AM" src="https://github.com/user-attachments/assets/58278fba-afdd-4786-b546-02c7a01d81c6">

**Comment by sergivillar** [comment]
Having same issue, someone manage to fix this? I a fresh install and it look like this , also note the errors in the console

![Uploading Screenshot 2024-12-20 at 19.09.51.png…]()

**Comment by sergivillar** [comment]
> > I have the same issue. Elements are showing, but they don't look right. I have added layout-card and state-switch. I have both tried manually installing all dependencies, and also used the checkbox for having Lovelace install them for me. ![image](https://private-user-images.githubusercontent.com/15639915/311458503-fcfd39e6-a89e-47f7-b838-b08249b69cf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjk4OTQsIm5iZiI6MTcxMjI2OTU5NCwicGF0aCI6Ii8xNTYzOTkxNS8zMTE0NTg1MDMtZmNmZDM5ZTYtYTg5ZS00N2Y3LWI4MzgtYjA4MjQ5YjY5Y2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDIyMjYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NzllOWUzODM4OTY4MjMyNTJmOWVmNzg0MGIxMWQ5NWZhMjlkZmViOTNlNTljYTkxZTY2Njc4MGI4NTkyYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5_rE1L89xwb0KLMz7Zjxd_ft6bkRx7eiVh_vR8XAZlQ)
> 
> For this weird looking quirk I found that you had to change the theme your user is set to one of the minimalist-* ones instead of having it on default as mine was before ![image](https://private-user-images.githubusercontent.com/23321780/319791451-28206eee-ba6c-465d-acd5-4fb8caf15b6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MTg2MzAsIm5iZiI6MTczNDcxODMzMCwicGF0aCI6Ii8yMzMyMTc4MC8zMTk3OTE0NTEtMjgyMDZlZWUtYmE2Yy00NjVkLWFjZDUtNGZiOGNhZjE1YjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDE4MTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzODAwNmFlZTZiNjZkMjRhZmNkMmRjNTJjOTg0MzQyMDVhZGQ2YTMxMGFmYjE0NzA2N2IyODZmNGRhNmI0NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I2xJwHnF4weK0o5fricAyHOmJvPczeW3LOoVZju9yho)

this fixed the issue for me

**Comment by wilbiev** [comment]
Documentation updated in PR #1559
