### ISSUE TITLE
Minor speeling mistake

### ISSUE THREAD

**Issue by ItsCharged** [UI-Lovelace-Minimalist/UI#1481]
**Describe the bug**
Website speeling mistake

**To Reproduce**

1. Go to [Here](https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_graph/)
2. Scroll down to Usage
3. Read ulm_card_graph_entity2:
4. Speeling mistake

**Expected behavior**
Seeing Bedroom and not Bedgroom 😐

**Screenshot**
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/90069597/9d6d40f6-3ee6-47e0-b9f4-ec7fcdc8430c)

**Additional context**
Pls fix text

**Comment by wilbiev** [comment]
Fixed in release v1.3.14
