### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by JStaegerino** [UI-Lovelace-Minimalist/UI#1490]
When trying to start a pull request, Hassfet validation always fails.

This seems to be the case for other users too, always with the same error message:

![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/66831023/01c6879b-3246-42fa-928a-8de173f96f5e)

Pull request #1488, #1484, #1479, #1474, ...

**Comment by kor4ik** [comment]
In PR https://github.com/UI-Lovelace-Minimalist/UI/pull/1517 
#1517 as well

**Comment by wilbiev** [comment]
Fixed in release v1.3.14
