### ISSUE TITLE
Unable to configure - add new custom cards via integration

### ISSUE THREAD

**Issue by khangwei** [UI-Lovelace-Minimalist/UI#1493]
Hi,

I used to be able to just go to integrations and configure, then add custom cards. I am now getting unknown error after a long loading process and HA crashes. Anyone has similar experience or know how to resolve this? Thank you

v1.3.9

![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/34676173/bc57513b-16db-436c-831a-5146f0b45afa)

**Comment by kdruelle** [comment]
Same for me, except I cannot enable custom card. Each attempt to click on submit leads to ha crashes.

**Comment by BradenJ6164** [comment]
I am also having this issue. Home assistant goes into recovery mode. It also corrupts each theme file in config/themes/minimalist-*.yaml. When opening the file in VS Code it will show a corrupted error. Deleting the themes and restarting the home assistant fixes the issue but all the settings revert to default again. It's also impossible to edit the created dashboards without corrupting the theme files.

**Comment by lolziac** [comment]
I'm having the same issue, latest HA and Minimalist UI (v1.3.9).
Whatever change I try to do in settings, It just hangs and crashes HA.

**Comment by 0la1** [comment]
Exact same issue and behavior as @khangwei 

Core: Version: 2024.5.2
Supervisor: Version: 2024.05.1
OS: Version: 12.2

**Comment by BananaSacks** [comment]
Ditto - Fresh update to Core & Supervisor this AM & then tried to install lovelace-minimalist for the first time.  Noticed that CPU pegs & OOM errors.  Bumped up cores & mem, same results.  Requires a forced reboot to stabilize.  

Note however, I was able to install the integration - it is when I attempt to change and apply (any) integration config that everything goes to hell in a handbasket.

**Comment by yolani** [comment]
Same here, can't change any configuration, not even the name of the default dashboards.

**Comment by Patrick1610** [comment]
I have the same issue, this is my config
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/6585375/c3d68a73-4850-4104-b0eb-adc863f540c2)
Eventually need this to change to minimalist-mobile

**Comment by BananaSacks** [comment]
Is this a dead project?  I thought Lovelace was the bee's knees for HA?  Or are we the only people having issues and we should stop hoping that this is an actual bug someone will actually look into?

**Comment by lravelo** [comment]
I'm having essentially the same issue.  I go to set up UI Lovelace Minimalist under Devices and when I hit submit it just hangs and the CPU spikes up over 80% and never comes back down. At this point Home Assistant becomes completely unresponsive.  Ultimately, I have to reboot my HA VM to get it working again. I'm running HA 2024.5.3 and HAOS 12.3.

**Comment by emilio6479** [comment]
Same here, can't change any configuration

**Comment by robinbohnen** [comment]
Same problem here!

**Comment by jeffrhap** [comment]
Having the same issue! Useless like this!

**Comment by locafra** [comment]
Same here.
Hard reset to make HA works again

**Comment by kappe72** [comment]
I have the same problem.

Core: 2024.5.4
Supervisor: 2024.05.1
OS: 12.3

**Comment by GroteGehaktBal** [comment]
same thing for me

**Comment by wilbiev** [comment]
I fixed two issues with my limited knowledge of Python and Home Assistant. You can find the modified files __init__.py and base.py in my GitHub repository https://github.com/wilbiev/UI/tree/main/custom_components/ui_lovelace_minimalist
The solved issues are the hanging (problem in the reload of the integration) and the log messages 'Detected blocking call'

**Comment by Ruu-D** [comment]
> I fixed two issues with my limited knowledge of Python and Home Assistant. You can find the modified files **init**.py and base.py in my GitHub repository https://github.com/wilbiev/UI/tree/main/custom_components/ui_lovelace_minimalist The solved issues are the hanging (problem in the reload of the integration) and the log messages 'Detected blocking call'

Hi there @wilbiev . I have managed to recover my custom YAML dashboard (which was removed from the menu bar after HA Core update). Thanks for the modified .py files!!! However, after using MINIMALIST UI for over a year now, i struggle to have further confidence in the project, as its not maintained very well... I'm going to try to recreate my dashboard using [MUSHROOM CARDS](https://community.home-assistant.io/t/mushroom-cards-build-a-beautiful-dashboard-easily-part-1/388590) (less flexible as YAML but modified via UI).

**Comment by wilbiev** [comment]
Fixed in new release v1.3.11
