### ISSUE TITLE
The dependencies list in the download section is missing dependencies

### ISSUE THREAD

**Issue by jtoniolo** [UI-Lovelace-Minimalist/UI#1497]
**Describe the bug**
The dependencies list in the download section is missing dependencies.

I needed to download layout-card and state-switch in addition to the rest to get it going.

**To Reproduce**
Should be self-evident. Go look at the download instructions.

**Expected behavior**
The dependencies list should be complete.

**Screenshots**
N/A

**Additional context**
When the automatic HACS install doesn't install everything, it would be really helpful to have a complete list. Particularly for those new to your dashboard or HA.

**Comment by wilbiev** [comment]
Fixed in new release v1.3.11
