### ISSUE TITLE
'ui_lovelace_minimalist' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop

### ISSUE THREAD

**Issue by acibo** [UI-Lovelace-Minimalist/UI#1535]
Log entry upon restarting HA after installing UI_Lovelace_Minimalist.  It requests that a bug report be created.

#######################################################################################
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 5:24:25 PM (1 occurrences)
Last logged: 5:24:25 PM

Detected that custom integration 'ui_lovelace_minimalist' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/ui_lovelace_minimalist/cards", "/config/custom_components/ui_lovelace_minimalist/cards", True)])`; This function will be removed in 2025.7 at custom_components/ui_lovelace_minimalist/base.py, line 366: self.hass.http.register_static_path(, please create a bug report at https://github.com/UI-Lovelace-Minimalist/UI/issues
#######################################################################################

**Comment by wilbiev** [comment]
Will be fixed in release v1.3.12
