### ISSUE TITLE
Can't delete dashboards automatically created by integration

### ISSUE THREAD

**Issue by alxhander** [UI-Lovelace-Minimalist/UI#1539]
**Describe the bug**
I need to remove the two Dashboards created by integration, but i can't. 
When i click in the 3 dots to edit the HA says "The edit UI is not available when in YAML mode".
I don't want to "hide" those dashboards, i need to delete.

**To Reproduce**
1. Click the icon of new dashboard
2. Click the 3 dots in right upper corner
3. voilá: "The edit UI is not available when in YAML mode"

**Expected behavior**
Able to delete and get rid of the new undesired automatically created dashboard

**Screenshots**
![image](https://github.com/user-attachments/assets/99e01853-dc5d-4dd9-96f1-354ee52c312c)
![image](https://github.com/user-attachments/assets/1864e458-0dd2-4491-a374-66b5d6f5af33)

```yaml
paste the yaml code here
```

**Comment by Nusserdt** [comment]
Same issue for me, and they looks like that:

![image](https://github.com/user-attachments/assets/cca33d4e-9916-476d-af78-6b6ad0f42106)

![image](https://github.com/user-attachments/assets/61259b25-551d-4bf6-ac1d-14779f336a30)

**Comment by Ajay250496** [comment]
Same here, I have this issue. When I try to configure the integration, it doesn't give me the options and then configures 2 dashboards, one is editable via yaml and one is not. When i try to reconfigure, my HA hangs with 1000s of logs saying 
"removing unknown panel adaptive dash" It basically breaks my system trying to reconfigure the integration.

Reinstalling does not fix it.

**Comment by wilbiev** [comment]
Issue solved in new available release v1.3.11

**Comment by nilsi** [comment]
I still cant delete the adaptive dashboard. Tried deleting the folder multiple times but it gets added again automatically. Using the latest v.1.3.14 and have tried the above fix. Im out of ideas.

**Comment by wilbiev** [comment]
You can enable/disable dashboards in the configuration of the UI Lovelace Minimalist integration. Go to Settings/Devices & services/UI Lovelace Minimalist and click 'Configure'.
