### ISSUE TITLE
Special characters are not allowed in "/config/themes/minimalist-mobile/minimalist-mobile.yaml", position 0

### ISSUE THREAD

**Issue by remco59** [UI-Lovelace-Minimalist/UI#1546]
**Describe the bug**
When setting up the integration Home Assistant freezes. I tried rebooting, but then it booted into recovery mode. When trying to reboot from the ui it tell's that special characters are not allowed.

**To Reproduce**
1. Navigate to "Settings" --> "Devices & Services"
2. Click "+ Add Integration"
3. Search for and select -> "UI Lovelace Minimalist"
4. On the integration page click 'Configure'
5. Using default settings, click Submit

**Expected behavior**
The integration to be set up correctly

**Error message**
The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: unacceptable character #x0000: special characters are not allowed in "/config/themes/minimalist-mobile/minimalist-mobile.yaml", position 0

**Comment by KruseLuds** [comment]
I set up mine by hand a long time ago by editing .yaml files, I thought setting this up from the UI was not (yet?) a possibility or available?

**Comment by wilbiev** [comment]
Fixed in version >= v1.3.11
