### ISSUE TITLE
Warning in HA on Raspberry Pi5

### ISSUE THREAD

**Issue by astraa1704** [UI-Lovelace-Minimalist/UI#1551]
Found this error in the logs, logging it for backward compatibility.

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:189 
First occurred: 15:30:20 (1 occurrences) 
Last logged: 15:30:20

Detected that custom integration 'ui_lovelace_minimalist' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/ui_lovelace_minimalist/cards", "/config/custom_components/ui_lovelace_minimalist/cards", True)])`; This function will be removed in 2025.7 at custom_components/ui_lovelace_minimalist/base.py, line 366: self.hass.http.register_static_path(, please create a bug report at https://github.com/UI-Lovelace-Minimalist/UI/issues

**Comment by astraa1704** [comment]
another one..\

Logger: homeassistant.data_entry_flow
Source: data_entry_flow.py:819 
First occurred: 15:25:06 (1 occurrences) 
Last logged: 15:25:06

custom_components.ui_lovelace_minimalist.config_flow::UlmFlowHandler calls async_show_progress without passing a progress task, this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author

**Comment by wilbiev** [comment]
Fixed in new release v1.3.11
