### ISSUE TITLE
blocking I/O in the event loop

### ISSUE THREAD

**Issue by rosentrieb** [UI-Lovelace-Minimalist/UI#1552]
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:189
Erstmals aufgetreten: 06:45:16 (1 Vorkommnisse)
Zuletzt protokolliert: 06:45:16

Detected that custom integration 'ui_lovelace_minimalist' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/ui_lovelace_minimalist/cards", "/config/custom_components/ui_lovelace_minimalist/cards", True)])`; This function will be removed in 2025.7 at custom_components/ui_lovelace_minimalist/base.py, line 366: self.hass.http.register_static_path(, please create a bug report at https://github.com/UI-Lovelace-Minimalist/UI/issues

**Comment by wilbiev** [comment]
Issue solved in new available release v1.3.11
