### ISSUE TITLE
integration installation error

### ISSUE THREAD

**Issue by d4nm0** [UI-Lovelace-Minimalist/UI#1556]
after following the following instructions found on the wiki. after clicking to install the integration i get an error 500. I never get this error when installing integrations. https://ui-lovelace-minimalist.github.io/UI/setup/installation/
  Navigate to "Settings" --> "Devices & Services"
  Click "+ Add Integration"
  Search for and select -> "UI Lovelace Minimalist"

![image](https://github.com/user-attachments/assets/54ab7dd5-b298-4e55-b58a-9419375dfa69)

**Comment by WillemSpork** [comment]
I’m experiencing the same issue, but with an existing installation. Dashboards are no longer working, and even a fresh installation doesn’t resolve the problem. The error also pointed me to the following error in the log:

Unable to install package aiofiles==0.8.0: × No solution found when resolving dependencies: ╰─▶ Because you require aiofiles==0.8.0 and aiofiles>=24.1.0, we can conclude that your requirements are unsatisfiable.

**Comment by razsteinmetz** [comment]
Same issue here too
`[homeassistant.util.package] Unable to install package aiofiles==0.8.0: × No solution found when resolving dependencies:
  ╰─▶ Because you require aiofiles==0.8.0 and aiofiles>=24.1.0, we can
      conclude that your requirements are unsatisfiable.`

**Comment by WillemSpork** [comment]
I noticed that people are already working on this error and a possible solution in #1553.

**Comment by razsteinmetz** [comment]
correct there is a solution there. thanks

**Comment by Nusserdt** [comment]
same issue here:

![image](https://github.com/user-attachments/assets/67bca4ed-54d0-4135-b5f1-23fd02cb7c51)

> Error
> Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

I don't get the fix for that issue, should really do:

> I just edited
> custom_components/ui_lovelace_minimalist/manifest.json
> and removed the aiofiles==0.8.0 line, rebooted Home Assistant, and it works again.

or just wait for a fix?

**Comment by Manbearpig92** [comment]
Same issue. My dashboard won't load and I get the error 500

**Comment by koenvm25** [comment]
I am experiencing the same issue when trying to add the integration.

**Comment by wilbiev** [comment]
Issue solved in new available release v1.3.11
