### ISSUE TITLE
homeassistant.helpers.frame

### ISSUE THREAD

**Issue by fawzi-iit** [UI-Lovelace-Minimalist/UI#1570]
HA:
**Core**: 2024.12.5
**Supervisor**: 2024.12.0
**OS**: 14.1
**Frontend**: 20241127.8
**UI Lovelace Minimalist**: v1.3.13

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 12:15:48 PM (1 occurrences)
Last logged: 12:15:48 PM

Detected that custom integration 'ui_lovelace_minimalist' sets option flow config_entry explicitly, which is deprecated at custom_components/ui_lovelace_minimalist/config_flow.py, line 245: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/UI-Lovelace-Minimalist/UI/issues

**Comment by wilbiev** [comment]
Fixed in release 1.3.14
