### ISSUE TITLE
Breaking changes section

### ISSUE THREAD

**Issue by Depechie** [UI-Lovelace-Minimalist/UI#161]
I just updated to the 1.0.0 beta 10 version and the visual change is the following ( cfr below ) without changing my yml design file.

Several questions...

- How do I get the top menu's back ( the icons to select the pages )
- How can I set the card margins myself? The new version is wider and now the text on the cards sticks to the sides. There is less room
- I did not see the breaking changes section about these things? Or did I miss something?

Pre 1.0.0
![IMG_1105](https://user-images.githubusercontent.com/351693/147509389-56a8777f-4a31-483c-8ae4-6315000ac11c.PNG)

1.0.0
![IMG_1232](https://user-images.githubusercontent.com/351693/147509394-b67c92fa-7678-4545-ade5-6d191aaf99fd.PNG)

**Comment by CM000n** [comment]
Because these are not breaking changes. They have not broken anything. These are just regular visual changes, all of which were listed in the last changelogs. In fact, hiding the top navigation bar was even a bugfix, as it was never intended to be visible on mobile devices.

https://github.com/UI-Lovelace-Minimalist/UI/pull/92

**Comment by Depechie** [comment]
Ok maybe the breaking change was a bit to much. But in my opinion I thought the YAML Config did change because the top menu bar was no longer showing. Hence I thought it was a breaking change.
Pitty it got lost because it was actually not supposed to be there, I did not know that.

Thx for pointing to the padding info!

**Comment by CM000n** [comment]
You can bring back the old behavior by deleting the code lines 13-23 in the mobile theme.
But you would have to be careful that your manual changes are not overwritten with a new release every time you update the theme files. ;-)
