### ISSUE TITLE
Add Graph bar style

### ISSUE THREAD

**Issue by CM000n** [UI-Lovelace-Minimalist/UI#190]
### Discussed in https://github.com/UI-Lovelace-Minimalist/UI/discussions/187

<div type='discussions-op-text'>

<sup>Originally posted by **BramScheepers** January  2, 2022</sup>
On the wiki site I see a graph for wattage made out of bars, how can i change my graph to this design?</div>

**Comment by mp-se** [comment]
In discussions I have posed some config that will enable the bars as in the image. https://github.com/UI-Lovelace-Minimalist/UI/discussions/172#discussioncomment-1890590

I know how to fix this so I can take on this feature.  There are other params that probably is good to have as config params besides the type of graph.

**Comment by CM000n** [comment]
> In discussions I have posed some config that will enable the bars as in the image. [#172 (comment)](https://github.com/UI-Lovelace-Minimalist/UI/discussions/172#discussioncomment-1890590)
> 
> I know how to fix this so I can take on this feature. There are other params that probably is good to have as config params besides the type of graph.

👍
But Even though the method you describe is a valid approach, it requires a knowledge of our internal templates.
I think we should just provide the possible options for `graph:` here to the end user as possible variables.

**Comment by mp-se** [comment]
I can take the lead for handling this, perhaps also merge my card with dual grahps into the same base card.

**Comment by mp-se** [comment]
The standard graph card has the following parameters;

```
- type: 'custom:button-card'
  template: card_graph
  variables:
    ulm_card_graph_color: "var(--google-blue)"
    ulm_card_graph_name: Temperature Livingroom
    ulm_card_graph_entity: sensor.livingroom_temperature
```
if we add the following to steer if it should be a line or bar graph. It defaults to fill (line with filled area to bottom) if not included. line just shows a line without fill. 
```
    ulm_card_graph_entity: fill | line | bar 
```
To include my custom card (dual graph) the following optional settings could be added. 
```
    ulm_card_graph_color2: "var(--google-blue)"
    ulm_card_graph_entity2: sensor.livingroom_temperature
```
To make it more configurable I propose we also add the following parameters:
```
    ulm_card_graph_hours: 24 (is the default)
    ulm_card_graph_entity2: sensor.livingroom_temperature
```
Any other options that could be useful?

**Comment by mp-se** [comment]
Here is how the card looks with the different options added: 
![image](https://user-images.githubusercontent.com/51722613/148178705-03cff298-696f-441c-94f9-fc91c1231ddf.png)

**Comment by CM000n** [comment]
Thanks for your thoughts. This looks very good to me! 
I think that should also cover most use cases for now and makes the card much more flexible.

**Comment by mp-se** [comment]
If there are more features from the mini-graph-cards that we want to use, it's quite easy to extend it further. And it should be backwards compatible so no one should need to change anything if they dont want to use the new features.

**Comment by CM000n** [comment]
closed by https://github.com/UI-Lovelace-Minimalist/UI/pull/210

**Comment by BramScheepers** [comment]
Has this feature been implemented yet? I would love to use it.

**Comment by bavo** [comment]
Sadly not. 

But you can cherry pick the commit or copy the files into your configuration (depending on your git knowledge) :stuck_out_tongue_winking_eye:
