### ISSUE TITLE
Add a simple weather card

### ISSUE THREAD

**Issue by mp-se** [UI-Lovelace-Minimalist/UI#207]
There is no standard weather card (there is one in the screenshots). Based on discussion on discord this could be a good option to use.

https://github.com/kalkih/simple-weather-card

**Comment by mp-se** [comment]
I can take the lead for this.

**Comment by mp-se** [comment]
This is what a basic card would look like. The question is what options we should use?

![image](https://user-images.githubusercontent.com/51722613/148248395-c982b5c5-656d-408a-aa0e-0610e481a117.png)

**Comment by CM000n** [comment]
Cold up there in Sweden ;-)
I think you can follow @httpedo13's customization of the `custom:sun-card` and just pass most of the card options through it:
https://github.com/UI-Lovelace-Minimalist/UI/pull/202/files

**Comment by mp-se** [comment]
Not that cold, have been worse ;-) thanks, i will check that for some inspiration. Will fix the vertical buttons first.

**Comment by mp-se** [comment]
Fixed in PR #212

**Comment by CM000n** [comment]
closed by https://github.com/UI-Lovelace-Minimalist/UI/pull/212
