### ISSUE TITLE
Notification badge entity unavailable suggestion

### ISSUE THREAD

**Issue by AndyVRD** [UI-Lovelace-Minimalist/UI#268]
**Describe the solution you'd like**
Now there is a notification badge if an entity is unavailable. Recently started using the custom light cards from @basbruss which are realy nice btw. Because one of my light entities where unavailable i noticed that the notification badge shows twice, one in the middle of the card and one thats partly visible in the img_cell. I contacted Bas and he described that this issue excist because both templates for icon and name using this custom_fields notification standard. After multiple attempts trying to fix it which is impossible i think because of card structure (img_cell is way smaller...) i tried a different approach.

**Describe alternatives you've considered**
Just get rid of the custom_fields notification badge and change the MDI icon in the img_cell with a mdi:help-circle. This way other futher more complex cards will not have the same problem...

**Example template code**
```
icon: >
  [[[
    var icon = 'mdi:lightbulb';
      if (variables.ulm_card_light_icon != null){
        var icon = variables.ulm_card_light_icon;
      }
      if (states[entity.entity_id].state == 'unavailable'){
        return 'mdi:help-circle';
      }
      else{
        return icon ;
      }
    return icon ;
  ]]]
```
**Example Result Card**

<img width="386" alt="Notification MDI" src="https://user-images.githubusercontent.com/67138158/149921637-e1883454-c97a-4e3d-823f-d558207c0c43.png">

**Comment by basbruss** [comment]
@schumijo @CM000n  Do you prefer this suggested approach or fixing the bug and show a little 'notification' icon above the `img_cell` as all other templates do? Which includes improving some bits in `icon_more_info` template.

**Comment by schumijo** [comment]
Hi @basbruss 

I think it is solved with the new all in one light card. But I don't have access to my laptop and HA to confirm today.

**Comment by basbruss** [comment]
Hi @schumijo 

Yeah was in the dev fase, but one line was not included with copying the code. So I've - made a PR which fixes it

**Comment by CM000n** [comment]
Sry for the late reply.
I would definetly prefer the little 'notification' icon above the img_cell as all other templates do.

**Comment by CM000n** [comment]
Should be resolved with https://github.com/UI-Lovelace-Minimalist/UI/pull/277 in next release
