### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by tsfhcz** [UI-Lovelace-Minimalist/UI#269]
Hello,
can you help me? I have followed installation to the letter according the:
https://ui-lovelace-minimalist.netlify.app/installation/yaml-mode
but on Minimalist page I get errors:

Button-card template ‘edge‘ is missing!
Button-card template ‘title‘ is missing!
Button-card template ‘edge‘ is missing!

Button-card is installed and in resources.. and button-card is working OK when I tested it.
Thank you.

**Comment by CM000n** [comment]
Ca you please share your folder structure, lovelace config and dashboard configuration?

**Comment by tsfhcz** [comment]
I have found out that there is missing instruction that I should copy not only themes directory, but also minimalist-templates to the config directory. When I did that I finally have "empty" Minimalist page with message "Welcome to UI-Lovelace-Minimalist".

**Comment by CM000n** [comment]
> I have found out that there is missing instruction that I should copy not only themes directory, but also minimalist-templates to the config directory. When I did that I finally have "empty" Minimalist page with message "Welcome to UI-Lovelace-Minimalist".

In point 4 of the installation instructions it is described exactly that you have to copy the minimalist templates AND the themes. Even the resulting folder structure is shown:

https://ui-lovelace-minimalist.netlify.app/installation/yaml-mode

**Comment by tsfhcz** [comment]
I am very thankful and ashamed.
