### ISSUE TITLE
[Documentation] Missing documentation for chip_mdi*

### ISSUE THREAD

**Issue by Keyruu** [UI-Lovelace-Minimalist/UI#299]
**Describe the bug**
The template string in [chip_mdi_icon_state](https://ui-lovelace-minimalist.github.io/UI/usage/chips/chip_mdi_icon_state/#usage) and [chip_mdi_icon_only](https://ui-lovelace-minimalist.github.io/UI/usage/chips/chip_mdi_icon_only/#usage) is wrong.
It's `example` but should be `chip_mdi_icon_state` and `chip_mdi_icon_only`.

**Comment by Keyruu** [comment]
I actually just noticed that the whole page for both chips is just an example page except for the picture.

**Comment by CM000n** [comment]
Should be fixed with https://github.com/UI-Lovelace-Minimalist/UI/pull/305
