### ISSUE TITLE
Cant install from the link in the new wiki

### ISSUE THREAD

**Issue by 1liminal1** [UI-Lovelace-Minimalist/UI#302]
**Describe the bug**
When trying to install from the integration link in the wiki. I get the following error.

![image](https://user-images.githubusercontent.com/10505942/150708634-87dda884-90fa-4c96-9de1-af26ecdeaeb2.png)

**To Reproduce**
click the link in the new wiki to install the integration

![image](https://user-images.githubusercontent.com/10505942/150708847-818876e3-549e-466f-bce2-3648110b3066.png)

**Expected behavior**
Install 

**Screenshots**
Above

**Additional context**

**Comment by CM000n** [comment]
Is your "My Home Assistant" integration configured properly?:
https://www.home-assistant.io/integrations/my/
And did you really download the minimalist Ui integratiopn via HACS **before** you tried to install it?

**Comment by stokkie90** [comment]
Did you add the repository to custom repositories. If it can't find a match you will get this error.

**Comment by 1liminal1** [comment]
Hey mate, 

This is all good. 

I think the instructions need to be a little clearer. It reads like you just need to install the integration from the link and then your good to go. But of course you need to install from HACS then use the link. 

Ill close this now,
