### ISSUE TITLE
Wrong template for media player popup

### ISSUE THREAD

**Issue by freebeergesicht** [UI-Lovelace-Minimalist/UI#304]
**Describe the bug**
In file popup_media_player_infos.yaml is a wrong template for the volume slider.

**To Reproduce**
Actual code:
_content2:
      card:
        **type: "custom:slider-card"**
        entity: "[[[ return variables.ulm_popup_media_player_entity ]]]"_

Should be:
content2:
      _card:
        **type: "custom:my-slider"**
        entity: "[[[ return variables.ulm_popup_media_player_entity ]]]"_

**Comment by CM000n** [comment]
Thank you! Fixed with https://github.com/UI-Lovelace-Minimalist/UI/pull/306
