### ISSUE TITLE
[Documentation] Wrong example variables in card_light

### ISSUE THREAD

**Issue by Keyruu** [UI-Lovelace-Minimalist/UI#307]
**Describe the bug**
The example code of the [card_light](https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_light/#description) component uses the wrong variables. 
It states:
`- type: "custom:button-card"
  template: card_light
  entity: light.allee
  variables:
    ulm_card_light_slider_enable_slider: true
    ulm_card_light_slider_enable_color: true
    ulm_card_light_slider_force_background_color: true`
It should be:
`- type: "custom:button-card"
  template: card_light
  entity: light.allee
  variables:
    ulm_card_light_enable_slider: true
    ulm_card_light_enable_color: true
    ulm_card_light_force_background_color: true`

**Comment by CM000n** [comment]
Should be fixed with https://github.com/UI-Lovelace-Minimalist/UI/releases/tag/v0.0.2
