### ISSUE TITLE
Better explanation about include_dir_merge_named & custom_cards

### ISSUE THREAD

**Issue by eliseo-juan** [UI-Lovelace-Minimalist/UI#309]
**Is your enhancement request related to a problem? Please describe.**
In case you are using custom cards, there is not an explained way of explaining how to add the dir `custom_cards` to `include_dir_merge_named`

**Describe the solution you'd like**
Here we could explain it better: https://ui-lovelace-minimalist.github.io/UI/setup/configuration/?h=custom#custom-cards
because I have no idea how to solve it.

**Describe alternatives you've considered**
Explain a bit more how to add custom_card path to resources.
**Additional context**

**Comment by CM000n** [comment]
Mhmm, isn't that clear enough? We have even shown an example of how the folder structure must look like :-) 

Basically you just have to create an folder inside `ui_lovelace_minimalist/custom_cards` for each cusom_card you want to add and put the custom_card.yaml file and the language file you need for the custom_card inside.

Would that be easier to understand? Feel free to suggest how it would be easier to understand.

**Comment by CM000n** [comment]
I will update the explanation with next release https://github.com/UI-Lovelace-Minimalist/UI/pull/308/files#diff-c0af5774bd4db564aac5d7fa832cd24f12b9f12c4e442e5b9afc2352b5847a7e
Please have a look if that is better understandable.

**Comment by eliseo-juan** [comment]
Now its clear! Thank you!
