### ISSUE TITLE
[Documentation] Wrong card picture for card_media_player_with_controls

### ISSUE THREAD

**Issue by Keyruu** [UI-Lovelace-Minimalist/UI#313]
**Describe the bug**
I think the picture from this card [card_media_player_with_controls](https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_media_player_with_controls/#usage) is the picture for this card [card_media_player_with_control](https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_media_player_with_control/) and I think one should be named differently.

**Comment by CM000n** [comment]
No, the pictures fit. Unfortunately, it is a misleading calculation at the moment. There are already efforts to standardise the media_player cards. https://github.com/UI-Lovelace-Minimalist/UI/pull/289

**Comment by Keyruu** [comment]
Are you sure the pictures fit? 
https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_media_player_with_controls/#usage
This states: With the card_media_player_with_controls you have the state of your media_player and on the second line PREVIOUS / PLAY-PAUSE / NEXT to control it
The picture: 
![image](https://user-images.githubusercontent.com/53177682/150867393-4cd8c79b-1ff7-46f5-85b9-44e5752de6c2.png)

https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_media_player_with_control/
This states: This is the second media-player-card, in contrast to the first one above, it shows the cover art from your media player.
The picture: 
![image](https://user-images.githubusercontent.com/53177682/150867510-f0277efb-bf4e-4ff1-a4b4-ccc91893f7c9.png)
