### ISSUE TITLE
Paddy's Welcome Card not displaying in UI

### ISSUE THREAD

**Issue by skandiah94** [UI-Lovelace-Minimalist/UI#316]
Paddy's welcome card (and it's variations) do not display or error in the UI after migration to the HACS install. 
If I inspect the webpage I can see there are no elements generated for the card or any errors in the UI

Here's what I've done so far to debug

- Verified custom components are available in `/config/custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/custom_cards`
- Verified other custom components are functioning as expected (e.g. custom chips I've made, other template for button-card)
- Attempted to force an error by mis-configuring the card (e.g. removing the weather variable), neither the card nor any errors displayed in the UI
- Removed components that were directly installed from HACS (button-card, mini-graph etc) and set "include custom card resources" to yes
- Reloaded Minimalist and rebooted HA to verify the above changes didn't break anything else

**Comment by skandiah94** [comment]
So I don't know how or why this appeared, but looks like it's an issue with the "type: markdown" declaration (not sure if that's the right word for yamls..)

Out of curiosity I commented out all of the "type: markdown" declarations and forced a refresh of the dashboard but no immediate change

![image](https://user-images.githubusercontent.com/55882334/150904433-eb8fa566-cd74-4382-b2b8-dd765f5f36fe.png)

**Comment by CM000n** [comment]
Strange, because the markdown card is actually a backed in part of Home Assistant and not a custom element: https://www.home-assistant.io/lovelace/markdown/ 
:-/

**Comment by CM000n** [comment]
Looks like you are not alone in this and that the problem already existed before the HACS integration:
https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/1271

Maybe a stupid question, but have you cleared your browser cache once? Do you have this error on all your devices?

**Comment by CM000n** [comment]
I have now tested it in my own setup @skandiah94 and unfortunately cannot reproduce it.
Everything is displaye
<img width="325" alt="Screenshot 2022-01-25 115351" src="https://user-images.githubusercontent.com/7945681/150964082-1d9e9b5d-fe14-471e-b8f4-b3668824c736.png">
d as expected:

**Comment by rick2909** [comment]
I first had the problem with the error `Custom element doesn't exist: markdown.` this is not happening anny more.
But the hole card doesn't show unil adding the following code:
```yaml
- type: "markdown"
  content: "!"
```

hope this helps

**Comment by CM000n** [comment]
Mhmm, maybe some problem with lazy loading of lovelace ressources itself.

**Comment by rick2909** [comment]
Since I don't want a markdown to ruin my dashboard, I use this as a workaround
```yaml
      - type: "markdown"
        content: "!"
        card_mod:
        style: |
          ha-card {
            display: none;
          }
```

**Comment by willyp713** [comment]
+1 for the same issue. No iteration of the Paddy Welcome card is working for me (basic, with weather, or with news). They all leave a blank space on the page where the card should be.

**Comment by Pepeanuts** [comment]
same here

> +1 for the same issue. No iteration of the Paddy Welcome card is working for me (basic, with weather, or with news). They all leave a blank space on the page where the card should be.

**Comment by skandiah94** [comment]
> Looks like you are not alone in this and that the problem already existed before the HACS integration: https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/1271
> 
> Maybe a stupid question, but have you cleared your browser cache once? Do you have this error on all your devices?

Sorry for the delayed reply, I was interstate in for a few days.

Yes, I see it across all devices, mobile app, mobile browser, desktop browser, laptop browser, also via internal and external URLs
I've tried clearing browser cache, different browsers, and to be safe also incognito mode too. 

Oddly I only noticed this behaviour after the HACS install, but if peple were seeing it before as well it could be a config thing?

**Comment by skandiah94** [comment]
@CM000n Ok so I think I've fixed it, I reconfigured the HACS install to **not** include custom cards/resources and re-installed all the dependencies via HACS and the card is displaying as expected.

I tried this because my mini-media-player card wasn't being found even though it was "installed" as a dependency.

I think the issue stems from how the Minimalist integration adds dependencies?

**Comment by willyp713** [comment]
> @CM000n Ok so I think I've fixed it, I reconfigured the HACS install to **not** include custom cards/resources and re-installed all the dependencies via HACS and the card is displaying as expected.
> 
> I tried this because my mini-media-player card wasn't being found even though it was "installed" as a dependency.
> 
> I think the issue stems from how the Minimalist integration adds dependencies?

I followed this advice and got the card to display again **BUT** it is displaying the wrong language now. It shows Portuguese, even though my config is set to English (GB) and there is no Portuguese language file in the custom_card_paddy_welcome folder.

**Comment by Pepeanuts** [comment]
@CM000n @skandiah94 we dont have this issue on v0.0.2 no ?

@willyp713 maybe check if you have the last version of custom_card paddy welcome card

**Comment by skandiah94** [comment]
@Pepeanuts I didn't, but I also had duplicate installs of all the dependencies so I cannot say for sure if 0.0.2 didn't have the issue

**Comment by peetereczek** [comment]
I have a bit different issue, welcome string is in wrong language

![Screenshot_20220131-091035_Home Assistant.png](https://user-images.githubusercontent.com/42431204/151759096-246e3706-025a-4842-9530-adad6ff45257.png)

I would expect English or Polish

I also have mentioned issue above with missing markdown, but only with Chrome web browser

**Comment by CM000n** [comment]
> I have a bit different issue, welcome string is in wrong language
> 
> ![Screenshot_20220131-091035_Home Assistant.png](https://user-images.githubusercontent.com/42431204/151759096-246e3706-025a-4842-9530-adad6ff45257.png)
> 
> I would expect English or Polish. I have only Polish language in card resources (config/ui_lovelace_minimalist/custom_cards/custom_card_paddy_welcome/languages/PL.yaml)
> 
> I also have mentioned issue above with missing markdown, but only with Chrome web browser, where while card is missing

Please open another Issue on that and don't mix things up! ;-)
