### ISSUE TITLE
Home Assistant Phone app unable to load resources for dashboard from external URL (HACS Install)

### ISSUE THREAD

**Issue by skandiah94** [UI-Lovelace-Minimalist/UI#317]
I couldn't think of a nice one liner but here's a nice table that explains what I'm seeing. I'm guessing it might be an issue with how resources are presented to the Home Assistant application? 

Google Play HA Application Version - 2022.1.1-full
Minimalist HACS Version - 0.0.2
Home Assistant Version - 2021.12.10
Install Type - Home Assistant Container

| Device | Access Method | Result |
|---------|------------------|----------|
| Desktop | Browser - External URL | Dashboard loads as expected |
| Desktop | Browser - Internal URL | Dashboard loads as expected | 
| Phone | Browser - External URL | Dashboard loads as expected |
| Phone | Browser - Internal URL | Dashboard loads as expected | 
| Phone | Application - Internal URL | Dashboard loads as expected | 
| Phone | Application - External URL | Dashboard reports custom elements do not exist |

**Comment by skandiah94** [comment]
Update to HACS ver - 0.0.3, behaviour is still the same

**Comment by stokkie90** [comment]
Did you clear the cache of you app? that might help. due to some changes in the cards/resources. 

Also are you using HACS for the card dependency have you checked the "Include custom card resources it's depending on." on the configure page of the integration.

**Comment by M3m0rys** [comment]
Funny I have the exact opposite problem 
External Link works fine but my internal link won't display all cards

**Comment by skandiah94** [comment]
> Did you clear the cache of you app? that might help. due to some changes in the cards/resources.
> 
> Also are you using HACS for the card dependency have you checked the "Include custom card resources it's depending on." on the configure page of the integration.

Sorry for the delay, I was interstate for a few days.

I've cleared the cache of the application and also performed a re-install.

I've removed all the HACS installs of card dependencies (except mini-card-player) and have checked the include custom card resources

**Comment by skandiah94** [comment]
So I fixed this issue along with  [https://github.com/UI-Lovelace-Minimalist/UI/issues/317](url) by reconfiguring Minimalist to **not** include custom cards/resources and re-installing all the dependencies via HACS 

Since doing this everything displays as expect using both internal and external URLs on both browser and HA App

**Comment by mekenthompson** [comment]
Thanks @skandiah94 ; I did the same thing and this resolved:

- Uninstall UI-Lovelace-Minimalist integration
- Re-download UI-Lovelace-Minimalist via HACs
- Download/Install button-card repo and front via HACs
- Restart HASS
- Install UI-Lovelace-Minimalist integration (leave include custom cards/resources unticked)
