### ISSUE TITLE
more-info tap_action on card_person not working

### ISSUE THREAD

**Issue by CM000n** [UI-Lovelace-Minimalist/UI#32]
I noticed earlier this day that the `more-info` `tap_action` on `card_person` is not working.
With a tap on the person card nothing happens at all
Maybe I'll manage to take a closer look soon and fix it myself.
But I thought I'll record it here in any case, in case someone should be faster than me ;-)

**Comment by Paddy0174** [comment]
Done. 🤣

**Comment by CM000n** [comment]
That was realy fast ;D

**Comment by Paddy0174** [comment]
It was just one line missing under the `tap_action`. I actually remember thinking about, if the more-info is useful, while working on that card, but must have lost the thought anywhere in between... :rofl: :rofl:
