### ISSUE TITLE
Chip items / menu are half / not showing

### ISSUE THREAD

**Issue by robbinonline** [UI-Lovelace-Minimalist/UI#323]
Since the last update v0.0.3 HACS install my chips icons are not showing, see screenshots and screenrecording.
There are more chip icons above in the screenshot.

![IMG_0753](https://user-images.githubusercontent.com/660835/150994742-a37938ec-5551-400f-a48c-9e21a588ff45.PNG)
https://youtube.com/shorts/TaJfzi9nX9w?feature=share

**Comment by robbinonline** [comment]
---
ui_lovelace_minimalist: !include "../../custom_components/ui_lovelace_minimalist/lovelace/plugins/ui_lovelace_minimalist.yaml"
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "UI Lovelace Minimalist"
theme: "minimalist-mobile"
views:
  - title: Home
    path: home
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: chip_icon_state
            variables:
              ulm_chip_icon_state_icon: "🚨"
              ulm_chip_icon_state_entity: alarm_control_panel.ha_home_alarm
            tap_action:
              action: call-service
              service: light.toggle
              service_data:
                entity_id: light.hanglamp
            triggers_update: light.toggle
          - type: "custom:button-card"
            template: chip_presence_detection
            variables:
              ulm_chip_presence_counter_residents: sensor.people_home
          - type: "custom:button-card"
            template: chip_icon_state
            variables:
              ulm_chip_icon_state_icon: "⚡"
              ulm_chip_icon_state_entity: sensor.stroomverbruik_afgekort
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge

          - type: custom:button-card
            template: chip_temperature
            variables:
              ulm_chip_temperature_inside: sensor.netatmo_jdm_weather_station_temperature
              ulm_chip_temperature_outside: sensor.netatmo_jdm_weather_station_outdoor_module_temperature
              ulm_chip_temperature_weather: weather.openweathermap
            tap_action:
              action: navigate
              navigation_path: /ui-lovelace-minimalist/weer
          - type: custom:button-card
            template: chip_icon_state
            variables:
              ulm_chip_icon_state_icon: "🎶"
              ulm_chip_icon_state_entity: media_player.woonkamer

**Comment by robbinonline** [comment]
`---
ui_lovelace_minimalist: !include "../../custom_components/ui_lovelace_minimalist/lovelace/plugins/ui_lovelace_minimalist.yaml"
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "UI Lovelace Minimalist"
theme: "minimalist-mobile"
views:
  - title: Home
    path: home
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: chip_icon_state
            variables:
              ulm_chip_icon_state_icon: "🚨"
              ulm_chip_icon_state_entity: alarm_control_panel.ha_home_alarm
            tap_action:
              action: call-service
              service: light.toggle
              service_data:
                entity_id: light.hanglamp
            triggers_update: light.toggle
          - type: "custom:button-card"
            template: chip_presence_detection
            variables:
              ulm_chip_presence_counter_residents: sensor.people_home
          - type: "custom:button-card"
            template: chip_icon_state
            variables:
              ulm_chip_icon_state_icon: "⚡"
              ulm_chip_icon_state_entity: sensor.stroomverbruik_afgekort
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge

          - type: custom:button-card
            template: chip_temperature
            variables:
              ulm_chip_temperature_inside: sensor.netatmo_jdm_weather_station_temperature
              ulm_chip_temperature_outside: sensor.netatmo_jdm_weather_station_outdoor_module_temperature
              ulm_chip_temperature_weather: weather.openweathermap
            tap_action:
              action: navigate
              navigation_path: /ui-lovelace-minimalist/weer
          - type: custom:button-card
            template: chip_icon_state
            variables:
              ulm_chip_icon_state_icon: "🎶"
              ulm_chip_icon_state_entity: media_player.woonkamer
`

**Comment by CM000n** [comment]
Thanks for reporting yout bug.
Can you please use proper code formating? 
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

It's hard to tell what's possibly wrong with your current represantation of code ;-)

**Comment by robbinonline** [comment]
I found out it only happens when hard refresh the page. If I go from by example the default Engery Home Assistant page into the new dashboard and then go to another view then it's fine. But when I refresh the page is again not showing.

See new screencast: https://youtube.com/shorts/G1UDLqGHHBo?feature=share

**Comment by CM000n** [comment]
Maybr some kind of caching error with your Browser?
Again: Please format your code example

**Comment by M3m0rys** [comment]
I think this is the same Error that i noticed

**Comment by robbinonline** [comment]
Yes it looks like the same error.
@CM000n I format the code like the example right? With the triple '

**Comment by CM000n** [comment]
Someone in Discord just had the same problem. What helped for this person was:

> You should try to reset front end cache in the app and close it and try again
Home Assistant > Settings > Companion App > Debugging

Please also test this and give feedback if it helped you @robbinonline & @M3m0rys

**Comment by M3m0rys** [comment]
> Someone in Discord just had the same problem. What helped for this person was:
> 
> > You should try to reset front end cache in the app and close it and try again
> > Home Assistant > Settings > Companion App > Debugging
> 
> Please also test this and give feedback if it helped you @robbinonline & @M3m0rys

I seem to be to incompetent to find that option
I already wiped cache via Android Settings and reinstalling the app

**Comment by robbinonline** [comment]
> Someone in Discord just had the same problem. What helped for this person was:
> 
> > You should try to reset front end cache in the app and close it and try again
> > Home Assistant > Settings > Companion App > Debugging
> 
> Please also test this and give feedback if it helped you @robbinonline & @M3m0rys

I try that, but that is no the solution here.

**Comment by M3m0rys** [comment]
@robbinonline what device are you using?

**Comment by robbinonline** [comment]
> @robbinonline what device are you using?

iPhone 12 Pro Max with iOS 15.2.1

**Comment by M3m0rys** [comment]
> > @robbinonline what device are you using?
> 
> iPhone 12 Pro Max with iOS 15.2.1

did you create a new ui since HACS update or copy/pase your old?

**Comment by robbinonline** [comment]
Copy paste, from a old .yaml file an used the new ui-lovelace.yaml
In v0.0.2 i have no problems with more than one view(s).

**Comment by M3m0rys** [comment]
> Copy paste, from a old .yaml file an used the new ui-lovelace.yaml In v0.0.2 i have no problems with more than one view(s).

same as i did. but bug is gone when using only one view

**Comment by robbinonline** [comment]
Good news!! I just update to v0.0.4. Made backup of ui-lovelace.yaml delete the file, deleted the integration. Add it again and restore the data in ui-lovelace.yaml. Problem solved :)

**Comment by CM000n** [comment]
LOL, very interesting. Because there were definitely no changes to the chips or the layout in the current release :-D

**Comment by stokkie90** [comment]
I think related to a loaded js file.

**Comment by M3m0rys** [comment]
> think related to a loaded js file. That is now removed

can confirm after v0.0.4 update lovelace working again

**Comment by CM000n** [comment]
Glad it works now again for all of you :-)
