### ISSUE TITLE
card_power_outlet won't update consumption without refresh

### ISSUE THREAD

**Issue by camelen** [UI-Lovelace-Minimalist/UI#326]
While using card_power_outlet I can't get consumption on the card without refreshing the page.

Can't get the insert code to work cause I'm an idiot but this is my settings:

- type:'custom:button-card'
  template: card_power_outlet
  variables:
    ulm_card_power_outlet_consumption_sensor: sensor.high_load_switch_electric_consumption_w
  entity: switch.high_load_switch
  name: Motorvärmare

I'm using 0.0.3 via HACS.

If I have a card_graph below with the same entity the graph instantly updates when I press the button on the power switch card.

If I refresh the page it shows the consumption on the power outlet card.

**Comment by CM000n** [comment]
Thank you for reporting. Should be fixed with: https://github.com/UI-Lovelace-Minimalist/UI/pull/328
