### ISSUE TITLE
Mobile app acting wierd

### ISSUE THREAD

**Issue by M3m0rys** [UI-Lovelace-Minimalist/UI#327]
After Clearing App Cache the Companion App startet to act wierd

1. Top of Lovelace ist cut off/ isn't displayed complete (size of top Nav bar) 
    Theme: Minimalist-Mobile
2. Nav bar is sometimes displayed at the Bottom of the Screen overlaying Lovelace 
    Theme:Minimalist-Desktop

both errors can be temporarily solved by changing to another lovelace and back do minimalist-lovelace
after reloading app errors are back.

Errors also appear when the Theme and Dashboard are used in Mobile Browser

App is 2022.1-full
newest HACS install

**Comment by CM000n** [comment]
Strange, can't reprpduce this on my Apple and Android devices.
Can you please share the code of your dashboard config.

**Comment by CM000n** [comment]
I think your bug report is a duplicate. I would handle everything in it for better focus: https://github.com/UI-Lovelace-Minimalist/UI/issues/323
