### ISSUE TITLE
Create a Troubleshooting page 

### ISSUE THREAD

**Issue by stokkie90** [UI-Lovelace-Minimalist/UI#329]
Add a page where we can redirect users to when they having trouble with their configuration/setup. 

Things like:
- when & how to Clear cache
  - on mobile-app
  - browser
- Custom card is not working
  - reload integration (how?)

please add more suggestions in the comments

**Comment by r0binj** [comment]
What I can come up with:
* Lastest ULM version 
* Lastest Home Assistant
* Which install method is used

* how to clear cache on different browser / OS 
* include a checklist when create a issue for better and faster support
