### ISSUE TITLE
Errors after upgrade to 0.0.4

### ISSUE THREAD

**Issue by briis** [UI-Lovelace-Minimalist/UI#333]
**Describe the bug**

After upgrading to 0.0.4 and restarting Home Assistant I am presented with the below error when trying to display the page:

`in "/config/ui_lovelace_minimalist/dashboard/ui-lovelace.yaml", line 2, column 25: Unable to read file /config/ui_lovelace_minimalist/dashboard/../custom_components/ui_lovelace_minimalist/lovelace/plugins/ui_lovelace_minimalist.yaml.`

**To Reproduce**

**Expected behavior**
Loading my Dashboard

**Screenshots**
<img width="1796" alt="Skærmbillede 2022-01-26 kl  15 35 14" src="https://user-images.githubusercontent.com/24776272/151182681-2e3cafac-af76-4a84-b95d-76be1f983439.png">

**Additional context**

**Comment by TheTimeWalker** [comment]
Release contains breaking change. See here: https://github.com/UI-Lovelace-Minimalist/UI/releases/tag/v0.0.4

**Comment by briis** [comment]
ALWAYS read the Release Notes carefully😁 and I did not. Closing this now. Thanks
