### ISSUE TITLE
Broken after update

### ISSUE THREAD

**Issue by M3m0rys** [UI-Lovelace-Minimalist/UI#334]
after updateing to v0.0.4

the lovelace does no longer work

Error message
in "/config/ui_lovelace_minimalist/dashboard/ui-lovelace.yaml", line 2, column 25: Unable to read file /config/ui_lovelace_minimalist/dashboard/custom_components/ui_lovelace_minimalist/lovelace/plugins/ui_lovelace_minimalist.yaml.

**Comment by CM000n** [comment]
Please read the Breaking Changes @M3m0rys! 
[https://github.com/UI-Lovelace-Minimalist/UI/releases/tag/v0.0.4](https://github.com/UI-Lovelace-Minimalist/UI/releases/tag/v0.0.4)

**Comment by M3m0rys** [comment]
> Please read the Breaking Changes @M3m0rys! https://github.com/UI-Lovelace-Minimalist/UI/releases/tag/v0.0.4

im a bit confused were schould i place my old UI yaml file?

**Comment by M3m0rys** [comment]
> Please read the Breaking Changes @M3m0rys! https://github.com/UI-Lovelace-Minimalist/UI/releases/tag/v0.0.4

works again thanks!
