### ISSUE TITLE
Reloading UI Lovelace Minimalist from server control page in Home Assistant no longer works

### ISSUE THREAD

**Issue by thomasfals** [UI-Lovelace-Minimalist/UI#340]
**Describe the bug**
Reloading UI Lovelace Minimalist from server control page in Home Assistant no longer works

**To Reproduce**
Update to v.0.04

1. Go to 'http://SERVERIP:8123/config/server_control'
2. Click on 'UI Lovelace Minimalis'

**Expected behavior**
UI Lovelace Minimalist yaml would reload

**Screenshots**

**Additional context**

**Comment by willyp713** [comment]
Same here since updating to 0.04

**Comment by Tommatheussen** [comment]
I came across this as well when debugging some custom cards, what I found is that it does reload, but it doesn't clear the browsers cache. If you change your dashboard page itself, Lovelace will reload the resources correctly without needing to restart

**Comment by stokkie90** [comment]
It will copy any changes in the `ui_lovelace_minimalist/custom_cards` to the button templates directory within the hacs integration. A refresh of the browser is not included currently. I have some ideas about it and got it sort of working once. 

https://github.com/UI-Lovelace-Minimalist/UI/blob/main/custom_components/ui_lovelace_minimalist/configure.py#L102


To test if it works. Make changes to your `custom cards`, hit reload ulm and check if the changes are also now in `custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/custom_cards`
