### ISSUE TITLE
Cover template has hardcoded icons that can't be changed by user

### ISSUE THREAD

**Issue by willyp713** [UI-Lovelace-Minimalist/UI#344]
**Is your feature request related to a problem? Please describe.**
[Cover template](https://github.com/UI-Lovelace-Minimalist/UI/blob/main/custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/internal_templates/cover.yaml) is hardcoded to use `mdi:window-shutter` and `mdi:window-shutter-open`. This icon doesn't make sense for other types of covers: garages, gates, etc.

**Describe the solution you'd like**
Allow the icon to be set by the user for [Card Cover with Buttons](https://github.com/UI-Lovelace-Minimalist/UI/blob/main/custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/2-line_cards/card_cover_with_buttons.yaml).

**Describe alternatives you've considered**
Tried making a custom version of `cover.yaml` but it broke the UI. It appears that these internal cards behave differently than custom cards.

**Additional context**
n/a

**Comment by willyp713** [comment]
Sorry this should probably be enhancement not feature request. Didn't read closely enough :(

**Comment by willyp713** [comment]
This is *partially* resolved by #621 but it only allows from pre-defined icons. So you can choose "garage" but you can't choose any mdi icon. Example: if you only have a 1-car garage, but the icon is for a 2-car garage.

**Comment by benbur98** [comment]
Alert icons still need work to implement. This is different to other many other cards as the Icon is set manually to allow for blind/garage/gate etc... and varies depending on the State (open/closed)

**Comment by wilbiev** [comment]
Cleaning up issue list
