### ISSUE TITLE
Allow user to change color on chip mdi icons

### ISSUE THREAD

**Issue by willyp713** [UI-Lovelace-Minimalist/UI#345]
**Is your enhancement request related to a problem? Please describe.**
`Chip_mdi_x` cards default to black and white.

**Describe the solution you'd like**
Allow user to define a color for these icons. For example, if you want to have an alert or warning chip color red. Or a good chip could be green.

**Describe alternatives you've considered**
Looked for emoji but couldn't find one that was relevant. MDI has many more options.

**Additional context**
n/a

**Comment by basbruss** [comment]
I already have something similar in mine personal config. I can try to make it supported by all the mdi_chips.
![image](https://user-images.githubusercontent.com/68892092/151509743-ccfebcd2-af31-4d66-bc80-f6031bd57b9a.png)

**Comment by aehru** [comment]
Hello,
I've worked on it for those chips for my personal use : 

- [ ] chip_mdi_icon_only
- [ ] chip_mdi_icon_state
- [ ] chip_navigate

Color of the icon is in a variable like `ulm_[chip_complete_name]_icon_color`

I will do a PR and update the doc too if the feature is still required. I think we can also control the text color like @basbruss shows in his screenshot.

**Comment by mon3y78** [comment]
i think it is a useful function !!!

**Comment by aehru** [comment]
Okay, will do that and also fix #360 with commented solution.
