### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by Stooovie** [UI-Lovelace-Minimalist/UI#357]
The documentation is wholly unclear. Almost every step has some little unclear of confusing detail.

Examples: 

` In the example it was assumed that the .yaml file is located in the top level of the Home Assistant configuration.`
Why is this assumed when the previous step clearly shows that the .yaml file is in config/ui_lovelace_minimalist/dashboard. Unnecessary confusion.

Folder structure in Configuration page:
![Screenshot 2022-01-30 at 10 38 55](https://user-images.githubusercontent.com/10572373/151694527-d2214c22-b182-4f16-a2b0-f67351854736.jpg)
is very different than in the Installation page:
![Screenshot 2022-01-30 at 10 38 30](https://user-images.githubusercontent.com/10572373/151694517-7dd438fc-9893-47ea-9f67-727c95bd5cc6.jpg)

Themes path is spelled "themes", "themes/" and "/themes" on the same page... 

Info at[ this page](https://ui-lovelace-minimalist.netlify.app/installation/yaml-mode) is different again...
![Screenshot 2022-01-30 at 10 54 06](https://user-images.githubusercontent.com/10572373/151694977-35522bac-a5f4-4aa5-a1d1-361f26b1dd18.jpg)

**Comment by CM000n** [comment]
> Why is this assumed when the previous step clearly shows that the .yaml file is in config/ui_lovelace_minimalist/dashboard. 

Because that is only the case for the auto generated lovelace dashboard.yaml file which already included that link and therefore this part of the documentation is irrelevant.
Most people that using there own lovelace Dashboard files have them on the top level of the folder structure or somewhere else

**Comment by CM000n** [comment]
Also the page you are linked is outdated ;-)
It seems you are using the deprecated wiki that no longer belongs to us.
Please use only this one: https://ui-lovelace-minimalist.github.io/UI/

**Comment by CM000n** [comment]
You other points should be adressed with https://github.com/UI-Lovelace-Minimalist/UI/pull/361

**Comment by Stooovie** [comment]
Thank you! The whole project looks ridiculously good, but I haven't been able to install it even with two years of HA experience. I hope I'll find a video tutorial somewhere when it gets a bit more widespread.
