### ISSUE TITLE
card_light slider visible when entity is unavaliable

### ISSUE THREAD

**Issue by peetereczek** [UI-Lovelace-Minimalist/UI#364]
**Describe the bug**
When light entity is unavaliable, slider is not hidden despite appropriate flag in card variables (ulm_card_light_enable_collapse: true)

**To Reproduce**

1. Create card_light with slider and slider collapse flag
2. Make light entity unavaliable
3. See error

**Expected behavior**
Slider should be hided, both for off and unavailable states

**Screenshots**
![image](https://user-images.githubusercontent.com/42431204/151787292-aa94cb0b-aec4-4825-96af-ab5747936ed8.png)

**Additional context**
- type: custom:button-card
              template: card_light_color
              entity: light.sonoff_1000ee2034
              variables:
                ulm_card_light_name: Łóżko RGB
                ulm_card_light_icon: mdi:bed
                ulm_card_light_enable_slider: true
                ulm_card_light_enable_color: true
                ulm_card_light_force_background_color: true
                ulm_card_light_enable_collapse: true
                ulm_card_light_enable_popup: true
- type: custom:button-card
              template: card_light
              entity: light.light_ikea_sypialnia
              variables:
                ulm_card_light_name: Szafka nocna
                ulm_card_light_icon: mdi:lamp-outline
                ulm_card_light_enable_slider: true
                ulm_card_light_enable_collapse: true
                ulm_card_light_enable_popup: true

**Comment by schumijo** [comment]
Thank you @peetereczek 
PR #375 created
