### ISSUE TITLE
chip_alarm unknown state

### ISSUE THREAD

**Issue by peetereczek** [UI-Lovelace-Minimalist/UI#376]
**Describe the bug**
Chip_alarm says unknown, when alarm state is armed_night

**To Reproduce**

1. Create chip_alarm
2. Arm alarm for night (set armed_night state)
3. See error

**Expected behavior**
State should be displayed with correct icon:
<img width="31" alt="image" src="https://user-images.githubusercontent.com/42431204/152069921-91fb9638-fe33-44a3-846d-8b2c8b6a86ed.png">

**Screenshots**
Chip currently:
<img width="82" alt="image" src="https://user-images.githubusercontent.com/42431204/152069713-2d10f310-af8c-4068-9da5-94249bc6f74c.png">

Alarm armed night:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/42431204/152069727-1ffb2ddc-ecf9-4d72-91b7-ee278e2c6f94.png">
<img width="309" alt="image" src="https://user-images.githubusercontent.com/42431204/152069789-81e32825-47ed-4fa0-b92f-e931e3bfd636.png">

**Comment by CM000n** [comment]
Schould be fixed with next release: https://github.com/UI-Lovelace-Minimalist/UI/pull/410
Thx to @Toudix
