### ISSUE TITLE
step 4 of installation

### ISSUE THREAD

**Issue by nickelnine** [UI-Lovelace-Minimalist/UI#405]
**Describe the bug**
It states to move `themes` and `minimalist-templates` folders from unpacked `config` folder to HA `config` but the downloaded zip from GitHub does not contain any `config` folder.

**To Reproduce**

1. Go to '[.[.](https://github.com/UI-Lovelace-Minimalist/UI).](https://github.com/UI-Lovelace-Minimalist/UI)'
2. Click on 'Code then download zip'
3. Extract zip to see contents
4. No config folder
5. 
**Expected behavior**
a folder labelled 'config'

**Screenshots**

**Additional context**

**Comment by bruvv** [comment]
Use this wiki: https://ui-lovelace-minimalist.github.io/UI/ the one you are using is old and outdated.
