### ISSUE TITLE
Error when reloading service

### ISSUE THREAD

**Issue by bruvv** [UI-Lovelace-Minimalist/UI#414]
**Describe the bug**
When I make changes to custom cards and I want to reload the intergration I get an error and no reload happens

**To Reproduce**
reload

**Expected behavior**
Do reload

**Screenshots**
```
https://hass.url.com/frontend_latest/app.19214a15.js:1387:5476 TypeError: t.parentElement is null
:0:0 ResizeObserver loop completed with undelivered notifications
```

**Comment by wilbiev** [comment]
Cleaning up issue list
