### ISSUE TITLE
Russian language

### ISSUE THREAD

**Issue by nefedovd** [UI-Lovelace-Minimalist/UI#417]
Please add Russian language in future update.

**Comment by sildehoop** [comment]
Would you be able to do the translation?

**Comment by acidquest** [comment]
---
ulm_language_variables:
  variables:
    ulm_on: "включено"
    ulm_off: "выключено"
    ulm_open: "открыто"
    ulm_closed: "закрыто"
    ulm_unavailable: "недоступно"
    ulm_standby: "ожидание"
    ulm_idle: "бездействие"
    ulm_currency: "RUB"
    ulm_auto: "Авто"
    ulm_heat: "Нагрев"
    ulm_cool: "Охлаждение"
    ulm_dry: "Осушение"
    ulm_fan_only: "Вентиляция"
    ulm_heat_cool: "Нагрев/Охлаждение"
    ulm_heating: "Нагревание"
    ulm_cooling: "Охдаждение"
    ulm_person_state_home: "дома"
    ulm_person_state_away: "не дома"
    ulm_person_state_not_home: "не дома"
    ulm_device_state_home: "Онлайн"
    ulm_device_state_not_home: "Офлайн"
    ulm_popups_back: "Назад"
    ulm_popups_toggle: "Переключение"
    ulm_popups_statistics: "Статистика"
    ulm_popups_history: "История"
    ulm_popups_brightness: "Яркость"
    ulm_popups_color_temp: "Температура"
    ulm_popups_color: "Цвет"
    ulm_unknown: "неизвестно"
    ulm_alarm_armed_home: "Режим: дома"
    ulm_alarm_armed_away: "Режим: не дома"
    ulm_alarm_armed_night: "Ночной режим"
    ulm_alarm_disarmed: "Охрана снята"
    ulm_alarm_arming: "Охрана установлена"
    ulm_alarm_triggered: "ВНИМАНИЕ!!!"
    ulm_playing: "Играет"
    ulm_paused: "Пауза"
    ulm_updates_available: "Доступно обновление!"
    ulm_no_updates_available: "Обновлений нет"
    ulm_morning: "Доброе утро"
    ulm_afternoon: "Добрый день"
    ulm_evening: "Добрый вечер"
    ulm_hello: "Привет"
    ulm_cleaning: "Убирается"
    ulm_returning: "Возвращается"
    ulm_docked: "На базе"
    ulm_mopping: "Мытье полов"

**Comment by basbruss** [comment]
closed with #756
