### ISSUE TITLE
Safari not displaying UI page

### ISSUE THREAD

**Issue by marcodallago** [UI-Lovelace-Minimalist/UI#438]
From a few version Safari does not correctly show the Minimalist Lovelace UI in macOS.

This happens also with iOS, so I don't think it's a browser configuration issue.

Lovelace container results blank and all Home Assistant Ui becomes unresponsive. 

In Chrome and Edge there are no problems. Also logs seems not to show any issue.

Am I the only one ? I'm not sure it's a configuration issue.

**Comment by Neu-Bob** [comment]
I am a Mac user on Safari and I can't get it to show up either

**Comment by miniminne** [comment]
Hey! I'm on iOS/macOS and I'm not seeing this problem in the browser. 

Are you using HAOS or one of the other methods of running HA? Did you follow the manual install method, or did you use HACS?

**Comment by collider123** [comment]
I have exactly the same problem. Safari on iPhone and Mac has problem.  HA running on HAOS and install minimalist in HACS. 

Another information is that I migrated from the old minimalist(the version is not installed in HACS). 

Using

**Comment by wilbiev** [comment]
Cleaning up issue list
