### ISSUE TITLE
Icon, label and state on media_player cards not readable

### ISSUE THREAD

**Issue by CM000n** [UI-Lovelace-Minimalist/UI#44]
I have the problem that with media player cards neither the icon, nor the label and the status are readable when the media player is on but no cover art is available while on light theme:
![7656765nt](https://user-images.githubusercontent.com/7945681/142402443-1e2455a5-ad62-4cda-ac76-8d277781f359.PNG)

Here we should probably change something about the color selection or representation in general?

I would also suggest treating media players that are in idle or pause mode similar to media players that are off. Or at least we should rethink the representation here as well.
For example, Sonos speakers are always in idle mode when nothing is playing. So for most of the day they are treated in the UI like media players that are on but idle. But from the user perspective however, they are turned off.

**Comment by schumijo** [comment]
Hi @CM000n,

Maybe we could play with CSS to contrast text and background :
[https://css-tricks.com/methods-contrasting-text-backgrounds/](url)

**Comment by CM000n** [comment]
Really very interesting article @schumijo. Thanks a lot!
But I wonder if it wouldn't be easier to just use a different default design if there is no media backgound?

**Comment by mekenthompson** [comment]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/8923913/154792673-d5481c06-5b79-4a8d-a8b7-5e9635d76bad.png">
I have same issue, I can see media player on/off, but not title of the device. For this example I'm using NVIDIA shield connected as Android TV (ADB).
