### ISSUE TITLE
Add Fahrenheit to Thermostat Card 

### ISSUE THREAD

**Issue by miniminne** [UI-Lovelace-Minimalist/UI#441]
Hi ya'll! I noticed when utilizing the thermostat card (at least via HACS) it only returns values as "celsius" despite the climate entity reporting values in Fahrenheit. 

Digging into the code for the thermostat card, I noticed that the code is set to always return the value as `temperature + *C` vs determining the correct unit of measurement to use based on either user input or the values returned by the climate entity. 

Example of the hardcoded string: 
![Screen Shot 2022-02-18 at 9 42 21 AM](https://user-images.githubusercontent.com/8529568/154714662-9183b4ab-a0bd-4f26-bb5e-30d711d1609a.png)

Requesting this as an enhancement since I'd hate to make the update every time the HACS integration updates and I do not have the necessary JavaScript skills to make this a PR sadly.

**Comment by CM000n** [comment]
Fixed by yourself in PR https://github.com/UI-Lovelace-Minimalist/UI/pull/450 ;-)
Thank you very much!
