### ISSUE TITLE
Fix padding swipe-card

### ISSUE THREAD

**Issue by bruvv** [UI-Lovelace-Minimalist/UI#454]
**Is your enhancement request related to a problem? Please describe.**
When you are using this awesome [swipe-card](https://github.com/bramkragten/swipe-card) it needs a little more room at the bottom. (using the `.swiper-container` class)
Without fix:
![image](https://user-images.githubusercontent.com/3063928/154935842-474aa1b7-ba12-43f5-b4f7-c6effaf82f17.png)

**Describe the solution you'd like**
add `padding-bottom: 4px`:
![image](https://user-images.githubusercontent.com/3063928/154935921-74ed0f9d-17a1-4a48-836e-fbb88c30872d.png)

**Comment by CM000n** [comment]
Good find! Can you create a PR for it?

**Comment by bruvv** [comment]
If I just knew how to. If you can tell me which file I need to modify I can haha

**Comment by CM000n** [comment]
Oh ok, I thought you had already made the change on your page somehow.

**Comment by bruvv** [comment]
@basbruss would you perhaps know how to fix this?

**Comment by basbruss** [comment]
@bruvv Where did you add the padding to obtain the screenshot? Is it added to the chips or to the swiper-card? I also have still this issue, so I don't know of any solution.
