### ISSUE TITLE
 Theme: hide app-toolbar with card-mod issue

### ISSUE THREAD

**Issue by rphlwnk** [UI-Lovelace-Minimalist/UI#47]
I noticed that the `app-toolbar` on the minimailist-mobile theme is still showing even if it should be hidden with card-mod-root styling:

```
  card-mod-theme: mobile
  card-mod-root: |
    app-toolbar {
      display: none;
    } 
```

I fixed this with writing the complete name of the them (first line of yaml file) in `card-mod-theme:`

```
  card-mod-theme: minimalist-mobile
  card-mod-root: |
    app-toolbar {
      display: none;
    } 
```

Dont know if this is a issue that only i have.

**Comment by CM000n** [comment]
Thank you for pointing this out. This should be fixed in the next release https://github.com/UI-Lovelace-Minimalist/UI/commit/9271054fb5aad13f5b6516e36f11c9589950201e
