### ISSUE TITLE
Card Room instructions on how to get temperature are unclear

### ISSUE THREAD

**Issue by CaliLuke** [UI-Lovelace-Minimalist/UI#472]
**Describe the bug**

I can't figure out how to use the "temperature" option to pass a room temperature to the card. I tried a variety of entities and configurations and it's not working properly. 

The docs are unclear: https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_room/#room-entity

**To Reproduce**

![image](https://user-images.githubusercontent.com/73209/155625350-852aded9-819d-4c8e-84cc-bda23c3ab913.png)

**Expected behavior**
I would like to see the temperature in the tile, a better example would probably suffice.

**Screenshots**

![image](https://user-images.githubusercontent.com/73209/155625371-8884b69d-35a4-4c85-b0a1-f24f777cd6f1.png)

**Additional context**

**Comment by CaliLuke** [comment]
I figured it out by putting the thermostat as the main entity for the card. Still, that should be better documented. What is the "temperature" variable for? where does it go?

**Comment by CaliLuke** [comment]
So if I want to use the tap action for the main card to be a toggle, is there a way to make it not try toggling the temperature sensor?

**Comment by thiagobucca** [comment]
i've the same use case as yours, since i guess this is not the way the card is intented to work i''ll cook up a custom card to make the temperature a variable you can pass through.

**Comment by thiagobucca** [comment]
You can edit the card_room template and make something like this:

Line 16:

`      if (variables.label_use_temperature && variables.temperature_entity) {
        return (states[`${variables.temperature_entity}`].state) + ('°C');`

and in your dashboard:

`              variables:
                label_use_temperature: true
                label_use_brightness: false
                temperature_entity: sensor.your_sensor`

**Comment by sjoshua270** [comment]
> So if I want to use the tap action for the main card to be a toggle, is there a way to make it not try toggling the temperature sensor?

Can you set `tap_action` for the whole card?

**Comment by wilbiev** [comment]
Cleaning up issue list
