### ISSUE TITLE
Missing "configo" folder on downloaded install zip package

### ISSUE THREAD

**Issue by r-zlo** [UI-Lovelace-Minimalist/UI#482]
In the installation guide (https://ui-lovelace-minimalist.netlify.app/installation/yaml-mode), step 4, there is an instruction to locate a folder called "config" from the downloaded zip file. 
such folder doesn't seem to exist. 
I also check the git repo but couldn't find this folder (and mentioned content that should be inside it)

**Comment by basbruss** [comment]
Sorry, the wiki your are using is somewhat outdated. The correct installation instructions can be found on this page: https://ui-lovelace-minimalist.github.io/UI/setup/download . It's correct though that the config folder is not anymore included in the zip file :wink:

**Comment by r-zlo** [comment]
Great; thank you @basbruss ... that worked now!!!
