### ISSUE TITLE
Views won't update without HA reboot

### ISSUE THREAD

**Issue by johangroenewold** [UI-Lovelace-Minimalist/UI#492]
I've decided to split my Lovelace Minimalist pages into the 'views' map, using the `views: !include_dir_merge_list "views/"` code in `ui-lovelace.yaml` to prevent clogging up the main file.

However, after doing so, it takes a reboot of Home Assistant before I can see any changes I make in the different files inside `./config/ui_lovelace_minimalist/dashboard/views/`, where before it just took a page refresh to see any changes. Clearing the cache also doesn't work.

For now I'll just use single `ui-lovelace.yaml` file to keep tweaking the pages, but I really would like to use this feature in the future.

**Comment by CM000n** [comment]
There is nothing we can do on our side here. This behaviour is introduced by Home Assistant itself. HA only reads the  main dashboard .yaml file and none of the other !include files. Lovelace will only trigger a full refresh if your main dashboard .yaml file has changed. If you change any other file nothing changes at the lovelace frontend side hence HA thinks nothing has changed.

**Comment by johangroenewold** [comment]
Okay, thanks for the quick response and the amazing work in general!
I'll work around this issue and continue enjoying this project!
