### ISSUE TITLE
UI seems to not load correctly

### ISSUE THREAD

**Issue by inancatil** [UI-Lovelace-Minimalist/UI#495]
After initial setup UI doesn't load properly. I installed via HACS and didn't change anything. Sample UI is looking not good. I did the remote access setup and using HA with my duckdns url with ssl certificate. That might cause problem but I am not sure.
 
**Screenshots**
 ![ui](https://user-images.githubusercontent.com/29947095/156447631-f8ce319e-0a27-4455-906f-8880cdc6f869.png)

**Comment by basbruss** [comment]
Please set the theme correctly in your profile. Or enable the blueprint which is also included.

**Comment by inancatil** [comment]
Thanks it almost fixed. There are still those parts that wont load properly. I get the same console errors about weather card and mini media player
![u'2](https://user-images.githubusercontent.com/29947095/156549834-7126dd2f-06f1-4a74-ad55-54cdd1268c04.png)

**Comment by joepbos** [comment]
I'm having the same issue on the welcome card with the weather chip not displaying text.

**Comment by keesfluitman** [comment]
![ui](https://user-images.githubusercontent.com/101324355/162440117-7ad9e396-63a1-4402-a3fa-202213d1cf43.png)
![resources](https://user-images.githubusercontent.com/101324355/162440125-cabb2224-d5ee-4332-9e80-a3d75210c7a3.png)

A. Doesnt look good.
B. Seems like every resource is properly accounted for right?

Any ideas why it's not showing everything properly? Or where I should start looking?

**Comment by basbruss** [comment]
The theme is not correctly applied. Please check your user_profile in the bottom-left corner and set it to the minimalist theme. https://ui-lovelace-minimalist.github.io/UI/troubleshooting/troubleshooting/ 😉

**Comment by basbruss** [comment]
It does look like it should. The `welcome_card` searches without any alteration of the variables for script entities in your HA-setup. If you don't have some it will display no pills/buttons. You can also set if you prefer the language to Dutch in the integration configuration.
