### ISSUE TITLE
Rounded Title and subtitle

### ISSUE THREAD

**Issue by majorhector** [UI-Lovelace-Minimalist/UI#496]
card_title has rounded corner when subtitle is configurated. Doesn't happened if I set only the title. This issue is started after v0.0.6-hotfix2 update

![Immagine](https://user-images.githubusercontent.com/81853764/156449500-615317e7-9e43-42dd-9207-ab771fcb5599.png)

**Comment by basbruss** [comment]
This is caused by the `ha-card-border-radius` which is now added in the theme-files. I will look if I can get a fix with altering some of the paddings for the title card
