### ISSUE TITLE
custom_card_afvalophaling, all 4 type of waste required also when not available in city

### ISSUE THREAD

**Issue by robbinonline** [UI-Lovelace-Minimalist/UI#497]
I love to use the custom_card_afvalophaling only all 4 types of waste (GFT, PMD, Restafval, Papier) are required.
Only I the place where I live there is no PDM waste, so when I leave that one empty or not use in the code the card does not show up.

When I add it in the configuration of afvalbeheer and then add the pdm sensor it shows unknown.

So please make some waste types optional.

**Comment by AndyVRD** [comment]
Hi,

I will release a fix for this.

**Comment by CM000n** [comment]
Resolved by https://github.com/UI-Lovelace-Minimalist/UI/pull/507
