### ISSUE TITLE
Thermostat Card missing or not working

### ISSUE THREAD

**Issue by nordmanntanne** [UI-Lovelace-Minimalist/UI#51]
Hi,

i noticed here https://community.home-assistant.io/t/lovelace-ui-minimalist/322687 that you use a thermostat card. But i can not find it in the documentation. The custom card template custom_card_thermostat ist not working probertly. How did you realize this template card for controlling climate entities?

**Comment by nordmanntanne** [comment]
![Screenshot 2021-12-01 142058](https://user-images.githubusercontent.com/68467135/144250900-0a530287-64f6-491d-a19e-8cc466846af3.png)

**Comment by saxel** [comment]
The card made by TBens hasn't been migrated yet. See [https://github.com/UI-Lovelace-Minimalist/UI/issues/4](https://github.com/UI-Lovelace-Minimalist/UI/issues/4)

**Comment by CM000n** [comment]
Hey @schumijo. Can we close this issue with your PR https://github.com/UI-Lovelace-Minimalist/UI/pull/84 ?
Or is there still some work to do in your opinion?

**Comment by schumijo** [comment]
Hi @CM000n 
You can close

**Comment by CM000n** [comment]
Closed in v1.0.0-beta.8 🏳️‍🌈
