### ISSUE TITLE
How do I set up two columns of cards?

### ISSUE THREAD

**Issue by nijez** [UI-Lovelace-Minimalist/UI#510]
How do I set up two columns of cards? Such as temperature and humidity sensors or light cards
![image](https://user-images.githubusercontent.com/46086777/156738898-a6a5c7bc-8863-4d56-8439-aebfb7be373a.png)
views:
  - title: "Example View"
    path: 0
    icon: "mdi:flower"
    cards:
      - type: "vertical-stack"
        cards:
          - type: "custom:button-card"
            template: "card_title"
            name: "全屋智能"
            label: "阿金的全屋智能系统"
          - type: 'custom:button-card'
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-blue)"
              ulm_card_graph_name: 一楼温度
              ulm_card_graph_entity: sensor.0x00158d0002388c7e_temperature
              ulm_card_graph_type: fill
              ulm_card_graph_hours: 24
          - type: 'custom:button-card'
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-blue)"
              ulm_card_graph_name: 卧室温度
              ulm_card_graph_entity: sensor.temperature_lumi_158d000149fffd
              ulm_card_graph_type: fill
              ulm_card_graph_hours: 24

**Comment by stokkie90** [comment]
Put the 2 graph cards in a horizontal-stack 

```yaml

title: "Example View"
path: 0
icon: "mdi:flower"
cards:

  - type: "vertical-stack"
    cards:
      - type: "custom:button-card"
        template: "card_title"
        name: "全屋智能"
        label: "阿金的全屋智能系统"
      - type: horizontal-stack
        cards:
          - type: 'custom:button-card'
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-blue)"
              ulm_card_graph_name: 一楼温度
              ulm_card_graph_entity: sensor.0x00158d0002388c7e_temperature
              ulm_card_graph_type: fill
              ulm_card_graph_hours: 24
          - type: 'custom:button-card'
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-blue)"
              ulm_card_graph_name: 卧室温度
              ulm_card_graph_entity: sensor.temperature_lumi_158d000149fffd
              ulm_card_graph_type: fill
              ulm_card_graph_hours: 24

**Comment by nijez** [comment]
Thanks a lot, I solved the problem perfectly

**Comment by nijez** [comment]
Is there a mode for tablet or PC?

**Comment by sjoshua270** [comment]
> Is there a mode for tablet or PC?

Do you mean by layout? I've found that it's best to have two different Dashboards for different devices.
I know that's a bit cumbersome, but here's a guide from HA: https://www.home-assistant.io/lovelace/dashboards/#adding-more-dashboards-with-yaml
