### ISSUE TITLE
Constant "Custom element doesn't exist" errors

### ISSUE THREAD

**Issue by antonio1475** [UI-Lovelace-Minimalist/UI#511]
**Describe the bug**
I get constant/random "Custom element doesn't exist" in custom cards, especially after refreshes (and even more if it's a cache refresh i.e. Shift-Refresh). **Those resources are enabled and load/work most of the time** - it's not that they never work/worked.

Minimalist is installed via HACS, and checkbox "Include custom card resources it's depending on" is enabled in the Integration configuration (and it works, most of the time).

Same happens in a non-minimalist Dashboard (eg. a UI dashboard, where I'm using card-mod, button-card,... too).

**To Reproduce**

1. Minimalist installed via HACS.
2. Checkbox "Include custom card resources it's depending on" is enabled in the Integration configuration 
3. Go to a dashboard that uses custom card resources (not necesarily a Minimalist yaml one)
4. Refresh/hard-refresh (refresh cache).
5. See error (sometimes!)

**Expected behavior**
Resources to load as normal, always.

**Screenshots**
![image](https://user-images.githubusercontent.com/63130724/156877668-f3333fdd-4384-47a5-bead-9c94e090bfe4.png)

**Additional context**
Before installing Minimalist, I had button-card, card-mod and others manually installed, then via HACS, and they always loaded perfectly. (I removed them before adding Minimalist, so that I could enable the checkbox without double-loading as warned)

Should I disable the checkbox and install those resources directly via HACS as before?

**Comment by Templum** [comment]
@antonio1475 I experience similar issues, but they started more recently. Not too sure if they maybe changed something in the recent updates that could impact load order.

**Comment by antonio1475** [comment]
@Templum I uninstalled Minimalist from HACS (it states that the HACS installation is sometimes broken) and did the manual installation, without the checkbox in the integration.
I then installed button-card and card-mod through HACS and it's been working perfect since.

**Comment by Templum** [comment]
@antonio1475 what do you mean by manual installation, are you referring to that you reinstalled Minimalist via HACS choosing to provide the dependencies on your own. Or did you manually install Minimalist?

**Comment by antonio1475** [comment]
@Templum 

High level steps I did (some restarts might be required in-between, follow the official instructions):
1. Delete Minimalist from HACS
2. Review/delete leftover folders in custom_components/minimalist
(careful in not deleting config/ui_lovelace_minimalist, where your dashboard and possible custom cards are stored.
3. [Manual Download](https://ui-lovelace-minimalist.github.io/UI/setup/download/#manual-download) (no HACS).
4. Set up the Integration: without the checkbox for the dependencies.
5. Install the dependencies like button-card "manually" (via HACS).

:)

**Comment by Intecpsp** [comment]
I've been seeing this issue since updating to 6.x. I installed through HACS and didn't have any issue until recently like the others are stating. I'd prefer not to do the manual install since I wouldn't receive update notifications. There has to be another way of keeping the HACS install and not having constant errors. Do any devs know of a recent change that would be causing this?

**Comment by basbruss** [comment]
The best way is to just install the `UI Lovelace Minimalist` through HACS(no manual install needed) and install all dependencies also by yourself through HACS. Than uncheck `install dependencies` in the configure menu within the integrations-tab and reload HA.
<img width="274" alt="Screen Shot 2022-03-08 at 14 05 30" src="https://user-images.githubusercontent.com/68892092/157243866-8d63c73f-2588-416d-adb1-90f58eed251a.png">

**Comment by Intecpsp** [comment]
My "workaround" for now is to just have a backup dashboard that uses default HA cards. Prioritize the minimalist dashboard, but fall back to the backup if there is a loading error

**Comment by antonio1475** [comment]
> The best way is to just install the `UI Lovelace Minimalist` through HACS(no manual install needed) and install all dependencies also by yourself through HACS. Than uncheck `install dependencies` in the configure menu within the integrations-tab and reload HA. 

That's... simple and obvious 😅 
I now honestly don't know why I went the manual download route... I might have been obfuscated at the time, read that [HACS installation sometimes is broken](https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/1142?u=antonio1475), and went full overboard...

Good point. I will try that too to stay within HACS. Thanks.

**Comment by nickmaleao** [comment]
I'm also having the same issues, but for me the problem its worse, after upgrading to the latest HA and minimalist v0.0.7 some of the cards aren't even loading and I don't get any error, if I use the home assistant android app I don't have any issues loading the cards. The problem only happens if I use a browser, tested on Chrome and Firefox both in incognito mode

**Comment by rick2909** [comment]
For me, it is the complete opposite of what nickmaleao has. Browser works, but app just shows that every element doesn't exist. this is on a clean install.

**Comment by xavierdemoor** [comment]
I have the same problem as @rick2909. I have no problem in a browser, never. But on HA app, lot of the time I need to restart the app a random number of time to not get the error.

I installed minimalist via HACS and checked include custom cards. Since "my-cards-slider-cards" is not available on HACS anymore, I don't know how to install it manually.

**Comment by MikeTheCleric** [comment]
Hi! I've got the same problem. Sometimes the GUI on browser needs a reload or restarting the app to load the resources. There are nwes about a possible solution? Thanks in advice!
