### ISSUE TITLE
Battery card not working

### ISSUE THREAD

**Issue by damianeickhoff** [UI-Lovelace-Minimalist/UI#52]
Looks like the battery card isn't working. When defined, it gives **undefined%** as state.

Don't know what exactly is wrong, but I think the template tries to get the battery attribute from the battery sensor, but the state of the sensor is the battery percentage it self.

Through the generic card it works fine.

![afbeelding](https://user-images.githubusercontent.com/12126826/144261618-906f152c-9442-43e7-96d5-639bc3decf14.png)

**Comment by saethone** [comment]
in the variables, set the ulm_card_battery_attribute: line as blank and it will just use the state. you'll do that with any battery sensors, otherwise its assuming youre looking for the "battery" attribute of an entitiy

**Comment by damianeickhoff** [comment]
Ah, should have tried that. That worked indeed! Mercí!
