### ISSUE TITLE
Light card popup not working

### ISSUE THREAD

**Issue by NWalledge** [UI-Lovelace-Minimalist/UI#524]
**Describe the bug**
Im putting in the code to get a popup for my lights but its not working. i input the code and change the entities and it doesn't popup when i hold down the button on my dashboard. Any ideas? i have all the needed cards installed via HACS

**To Reproduce**
For example :
- type: "custom:button-card"
  template:
    - card_light
  entity: light.cuisine
  variables:
    ulm_card_light_enable_popup: true

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/46450157/157752121-7551aa27-8ef7-46a2-ae8a-18adbe7c3969.PNG)

**Additional context**

**Comment by stevedngo** [comment]
I'm having this issue too but for all popups.  Not sure if I did it incorrectly but I believe I have all the needed cards installed via HACS as well.

**Comment by basbruss** [comment]
Do you guys also have installed browser_mod and enabled it in your configuration.yaml file?

**Comment by stevedngo** [comment]
This fixed it for me.  When I had installed browser_mod, I forgot to enable it in my configuration.yaml file. Thank you!

**Comment by NWalledge** [comment]
Yes that fixed it thanks!
