### ISSUE TITLE
Popups are not working after HA updates 

### ISSUE THREAD

**Issue by inancatil** [UI-Lovelace-Minimalist/UI#540]
Host Operating System | Home Assistant OS 7.5
Update Channel | stable
Supervisor Version | supervisor-2022.03.5
  
**Describe the bug**
After the HA updates long press to show light popups are not working. No warning in the console. 

There is only one warning in log however fixing this did not solve the problem so I reverted back to original.

- Entity media_player.desktop_browser_mod (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) implements device_state_attributes. Please report it to the custom component author.
-Entity light.desktop_browser_mod (<class 'custom_components.browser_mod.light.BrowserModLight'>) implements device_state_attributes. Please report it to the custom component author.
-Entity sensor.desktop_browser_mod (<class 'custom_components.browser_mod.sensor.BrowserModSensor'>) implements device_state_attributes. Please report it to the custom component author.

 
**Additional context**
I dont use HACS. Installed all dependencies manually. It was working 2 or 3 updates before

**Comment by wilbiev** [comment]
Cleaning up issue list
