### ISSUE TITLE
Deprecated wiki https://ui-lovelace-minimalist.netlify.app/ 

### ISSUE THREAD

**Issue by basbruss** [UI-Lovelace-Minimalist/UI#566]
## Due to the limitation in rights for the maintainers there are 2 wiki's online.
The one on netlify(https://ui-lovelace-minimalist.netlify.app/installation/yaml-mode) is deprecated and will give some wrong information about installation methods and usage in UI-mode. Info about cards can be outdated or not existing.

The correct information can be found on: [ui-lovelace-minimalist.github.io/ui/](https://ui-lovelace-minimalist.github.io/UI/)

Please check if you used the correct wiki-site before posting an issue 😄

**Comment by lyricnz** [comment]
Why not delete the old docs?  (and include a redirect).  It's linked from lots of places online, and having docs that have broken links and incorrect instructions is a bad look.

**Comment by basbruss** [comment]
It's in the title. The current maintainers do not have the rights to alter the deprecated wiki 😉
