### ISSUE TITLE
Hide Chips at certain state

### ISSUE THREAD

**Issue by damianeickhoff** [UI-Lovelace-Minimalist/UI#57]
I was trying to create a conditional chip so that, when a sensor has a certain state (ex. there is 1 light or more on) its show the chip, but when there are no lights on, it should hide it. Also, when the chip is showing, it should also show how many lights there are on.

That works, kinda...

When the chip is showing, it gives as state 0. After a browser refresh, it updates to 1. Same goes for 1 to ex. 2 or from ex. 2 to 1.
When it goes from something to 0, it hide the chip, like it should.

So the only problem is that the state of the chip is not live updating.

I'm using the state-switch card.
```

          - type: custom:state-switch
            entity: sensor.lights_on
            states:
              lights on:
                type: 'custom:button-card'
                template: chip_icon_state
                variables:
                  ulm_chip_icon_state_icon: '💡'
                  ulm_chip_icon_state_entity: sensor.current_lights_on
```

**Comment by CM000n** [comment]
This should probably solve that: https://github.com/UI-Lovelace-Minimalist/UI/issues/35

**Comment by damianeickhoff** [comment]
I'm not sure how I should implement that. 

Do I need to change the triggers_update in the chip_icon_state template to `- "all" `instead of 
`- "[[[ variables.ulm_chip_icon_state_entity ]]]"`?

**Comment by CM000n** [comment]
Exactly! :-) With the next release this should be fixed anyway

To be honest I don't know if it is the real solution in your case in the context of the custom:state-switch card. But currently it is definitely wrong and ensures that the states of the button cards / chips are not updated.
So try it ;-)

**Comment by CM000n** [comment]
Yes, I unfortunately encountered the same problem in connection with conditional cards. 😩 
https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/168
But this doesn't seem to be a problem with the minimalist theme in general, but rather with conditionally displayed cards and css. 🙄

**Comment by damianeickhoff** [comment]
Well I found something. When I inspect the chip with the dev tools in Firefox, there is a CSS style `flex: 1 1 0;` for the state-switch.

By turning that off, the buttons aligning nicely.

Just don't know how this could be implemented in the template.

**Comment by CM000n** [comment]
Yes, but it is in the CSS of the condition card, right? So nothing we could do here I think. Maybe you should create an issue for this in the corresponding repo for custom:state-switch card as well.

**Comment by damianeickhoff** [comment]
Yes, will do that. In the mean time, might u find a way to fix this, please let me know! :)

**Comment by CraneJen** [comment]
> Well, that is a step in the right way. The chip updates the state, but... The margin seems to be off. ![afbeelding](https://user-images.githubusercontent.com/12126826/144447899-fc208eb6-42be-47d7-a2e6-28e139b63859.png)
> 
> I guess this has something to do with the state-switch but, can you fix that or?
> 
> EDIT: This has nothing to do with the change of the triggers_update, I didn't noticed it before. So its definitely the state-switch.
> 
> Let me know what to do.

any one sloved  the margin problem?
