### ISSUE TITLE
Tilted interface on Edge based browser (PC and Android)

### ISSUE THREAD

**Issue by StephaneM60** [UI-Lovelace-Minimalist/UI#572]
When applying UI Lovelace Minimalist, I can immediately see that the Home Assistant interface is not rendering as usual. Some elements are slightly tilted.

For instance : the menu bar on the left is tilted from left to right or right to left (it changes if you refresh the page). The cards themselves or the elements of the cards are also tilted (see attached screenshot)

Note : it is happening both on a Windows PC and on android Phone with Edge browser installed.

**To Reproduce**
Install UI Lovelace Minimalist and hit F5.

**Expected behavior**
The same rendering I can see on the same install in the Chrome browser.

**Screenshots**
![Capture d’écran 2022-04-01 163438](https://user-images.githubusercontent.com/48354330/161284930-ab772273-cd17-451d-b063-ceb1fbb304b5.png)

**Comment by basbruss** [comment]
Hi,

This is an April fools joke by card-mod which is installed with minimalist if you checked the box to let minimalist to install all needed dependencies. https://community.home-assistant.io/t/if-your-frontend-looks-weird-today/407225/72

Fix is already released and available through HACS: https://ui-lovelace-minimalist.github.io/UI/ 

Btw it will automatically change back tomorrow as the code for the joke is only active on april the 1st.

**Comment by StephaneM60** [comment]
Indeed, it's gone today. It's strange because I had installed the hotfix. Surely the browser cache retaining the file responsible for it (that's why chrome was not affected : I tested on chrome after installing the latest version).

Jokes on me for trying something new on april 1st.

Thanks.
