### ISSUE TITLE
Language thingy in Dutch / Not really a bug

### ISSUE THREAD

**Issue by Qpernicus** [UI-Lovelace-Minimalist/UI#574]
**Describe the bug**
Not really

**To Reproduce**
The Language.yaml file for dutch has these rules:

    ulm_morning: "Goede morgen"
    ulm_afternoon: "Goede middag"
    ulm_evening: "Goede avond"

I would like to change these persistently to

    ulm_morning: "Goedemorgen"
    ulm_afternoon: "Goedemiddag"
    ulm_evening: "Goedenavond"

**Comment by AndyVRD** [comment]
Done. https://github.com/UI-Lovelace-Minimalist/UI/pull/580
