### ISSUE TITLE
Handle unavailable entities in battery card

### ISSUE THREAD

**Issue by shanedabes** [UI-Lovelace-Minimalist/UI#591]
**Is your feature request related to a problem? Please describe.**
Whenever a battery sensor entity is unavailable, the batter card shows a strange state.

For example, I have some miflora sensors that are unavailable upon startup and only become available once a scan is successful:

![b](https://user-images.githubusercontent.com/1909963/162347447-dc910efa-d37b-4fbd-9d8a-a7244cb3e046.png)

And a sonos roam that doesn't report its battery status when it's powered off.

![b](https://user-images.githubusercontent.com/1909963/162347503-47d5e9c5-6ed1-4b44-b302-53d91b172818.png)

**Describe the solution you'd like**

It would be good to show a more readable unknown state and use the same icon the entities card uses for unavailable battery entities.

Something like this (a bad mock up using the chrome css editor and gimp) would be good:

![b](https://user-images.githubusercontent.com/1909963/162348397-3f43ece5-2719-467a-950b-f32399392753.png)

**Comment by basbruss** [comment]
closed with #756
