### ISSUE TITLE
Dashboard fails to update

### ISSUE THREAD

**Issue by beasthouse-au** [UI-Lovelace-Minimalist/UI#607]
**Describe the bug**
Whenever I make changes to the yaml file of a second or third dashboard (not the original one), to changes do not update in the UI until after a full reboot of Home Assistant. Updating of language file in custom cards such as `custom_card_imswel_person` do not work / update at all.

**To Reproduce**
Steps to reproduce the behaviour:

1. Make any changes to extra dashboard files (including change language etc of a custom card)
2. Refresh of browser, including clearing cache/cookies, does not show any change to the dashboard.

**Expected behaviour**
24 hours ago it was updating fine, now it does not.

In below file structure, if I make changes to `ui-lovelace.yaml`, changes are reflected immediately. If I make changes to `minimalist-mobile.yaml`, changes require at least a restart of Home Assistant.

![image](https://user-images.githubusercontent.com/78465928/163121026-c88583e1-9bbd-4160-affb-982b78e2a58c.png)

**Comment by beasthouse-au** [comment]
@imswel any chance you can look into the bug I am experiencing where the correct language does not display in the `custom_card_imswel_person` card?

**Comment by beasthouse-au** [comment]
Found a workaround where I can get the UI to refresh using the three little dots at the top right of the screen.

**Comment by AndyVRD** [comment]
Not to be rude but that’s not a workaround but the default action to reload your frontend.

**Comment by beasthouse-au** [comment]
All good @AndyVRD  -  should CTRL + F5 not do the same thing though?

**Comment by AndyVRD** [comment]
No ctrl + f5 reloads the browser cache and refresh the page. The 3 dots refresh the frontend cache.

**Comment by beasthouse-au** [comment]
Awesome thanks for that clarification!
