### ISSUE TITLE
Getting config error

### ISSUE THREAD

**Issue by Marcus4Aspern** [UI-Lovelace-Minimalist/UI#61]
Fresh install - getting this error checking the config:
Error loading /config/configuration.yaml: mapping values are not allowed here
in "/config/themes/minimalist-mobile/minimalist-mobile.yaml", line 146, column 65

**Comment by CM000n** [comment]
It would be very helpful if you could share some code with us. What does your `configuration.yaml` look like and what is your folder struture under "_/config/themes/_" ?

**Comment by arjwalker** [comment]
Ive got this same error. 

I have tried the following strutures:

/config/themes/minimalist-desktop/minimalist-desktop.yaml

/config/themes/minimalist-desktop.yaml

But still get the same error when I check config. 

My config file is like this:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

  
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
   themes: !include_dir_merge_named themes


Any help would be greatly appriciated! 
Thanks

**Comment by CM000n** [comment]
The entry in your `configuration.yaml` should look like this:

```
frontend:
  themes: !include_dir_merge_named themes
```
Please note the correct indentation!

And the correct folder structure would be starting from the configuration directory:

```
themes/
├── minimalist-desktop/
│   └── minimalist-desktop.yaml
└── minimalist-mobile/
    └── minimalist-mobile.yaml
```

**Comment by CM000n** [comment]
Hello @Marcus4Aspern and @arjwalker , is there any news on this? 
Otherwise, I would close the issue soon, since your last feedback was over 7 days ago.
