### ISSUE TITLE
MDI Icon picker contrast in Light mode

### ISSUE THREAD

**Issue by tivoo** [UI-Lovelace-Minimalist/UI#613]
**Describe the bug**
Whenever viewed in the Light theme, the MDI Icons picker has a white background and the icons are white as well, making it unviewable.

**To Reproduce**

1. Select minimalist-theme and select Light mode
2. Go to any entity to select an appropriate icon
2. Select the icon dropdown
3. Scroll down and see how unviewable the icons are

**Expected behavior**
Expect the icons or the bg to have the right contrast so that they are viewable (as with the selected icon)

**Screenshots**
![ui-minimalist-icons](https://user-images.githubusercontent.com/48723034/163348709-06e25d9e-1d1e-4437-b4f2-02eb4832cb1b.png)

**Comment by 13robin37** [comment]
@tivoo Does this still happen? Should be fixed
