### ISSUE TITLE
Be able to set show_in_sidebar on the first generated dashboard (ui-lovelace.yaml)

### ISSUE THREAD

**Issue by Intecpsp** [UI-Lovelace-Minimalist/UI#614]
**Is your feature request related to a problem? Please describe.**
I'm trying to hide my first-generation dashboard without losing its content

**Describe the solution you'd like**
Be able to set `show_in_sidebar` to `false` since it's explicitly being set to `true` [here](https://github.com/UI-Lovelace-Minimalist/UI/blob/d1fd5ce774b9ec098d59be47ed5ed198e7333024/custom_components/ui_lovelace_minimalist/load_dashboard.py#L26). Bonus would be to do the same to `require_admin`.

**Describe alternatives you've considered**
Copying all yaml to a new dashbaord and setting it to `false` like documented [here](https://github.com/UI-Lovelace-Minimalist/UI/blob/f4520561de284b6e34a13628e3900e9265c83a1c/docs/setup/customizing.md#add-multiple-dashboards)

**Additional context**
None

**Comment by wilbiev** [comment]
Cleaning up issue list

**Comment by Intecpsp** [comment]
Was this functionality implemented?

**Comment by wilbiev** [comment]
I'm trying to get this project back alive. Therefore cleaning up some very old issues. If you want I can reopen this one.

**Comment by Intecpsp** [comment]
There doesn't appear to be much demand for this, so it can remain closed until a greater need arises.
