### ISSUE TITLE
Button Template - Faulty state template value

### ISSUE THREAD

**Issue by kbrigitta** [UI-Lovelace-Minimalist/UI#63]
In button_card_templates.yaml, on line 195 and 213, templates "vertical_buttons_blue" and "vertical_buttons_green" are defined.

The state template value contains the following: 
**value: "[[[ return states['input_select.localisation_thomas'].state == variables.state ]]]"**

As using the template doesn't work, it does when modifying this line to:
**value: "[[[ return entity.state == variables.state ]]]"**

Afterwards, the button card template seems to work as expected.

I think this needs to be adjusted for the next release, as it will be overwritten each time this theme is updated without changing this part.

**Comment by saxel** [comment]
I have opened a PR https://github.com/UI-Lovelace-Minimalist/UI/pull/66 where this is addressed. I added support to specify the color to use in the template itself since I don't want to duplicate the code for each color variant.

**Comment by CM000n** [comment]
Thank you for pointing this out. Thanks to saxel there should be a fix for this in the next release :-)
