### ISSUE TITLE
Time Input Helper closes keyboard after first key press (minimalist mobile theme)

### ISSUE THREAD

**Issue by LeoLTM** [UI-Lovelace-Minimalist/UI#630]
**Describe the bug**
When clicking on a time input helper lovelace card, the keyboard shows up fine, but after pressing the first key, it closes itself. If you then open up the keyboard again by clicking on the input box, you can do two or more key presses in a row without the keyboard disappearing.

I think this might be an issue with the minimalist-mobile tapbar theme.

Tested this behaviour on 2 different devices.

**To Reproduce**

Android 12, MIUI 13, Google Keyboard (Gboard), Home Assistant Android app

1. Create a time input helper
2. Add a input helper lovelace card (the standard HomeAssistant  one, not UI Minimalist) to your dashboard.
3. Open you dashboard in the Home Assistant Android app
4. Select minimalist-mobile tapbar theme 
5. Return to dashboard and click time input
6. Try to enter "06:55":
7. Press "6"
8. Keyboard closes, so click the input again
9. Enter "5" on the right side, keyboard closes, but we only have "06:05" now
10. Click input
11. Enter "5" , "5" 
12. Result: "06:55"

**Expected behavior**
Click input, enter 2 digit number like "55" without the keyborard closing itself.

**Additional context**
This problem doesn't exist when using other themes.

**Comment by wilbiev** [comment]
Cleaning up issue list
