### ISSUE TITLE
How to Completely Remove UI Minimalist?

### ISSUE THREAD

**Issue by Lokalx** [UI-Lovelace-Minimalist/UI#634]
I never was able to get this theme to run correctly and have since uninstalled it.  However, HACS still keeps asking me to the perform an update, so some code is still lingering somewhere.  I would like to delete what is pointing to the outdated version that is no longer installed on my system...thank you!

**Comment by sjoshua270** [comment]
Check HACS > Integrations and remove the UI Lovelace Minimalist integration
