### ISSUE TITLE
Set currency regardless of language

### ISSUE THREAD

**Issue by alekslyse** [UI-Lovelace-Minimalist/UI#642]
Im not sure if this has been asked before, but even if my HA is set to currency NOK, the energy chirp show euros. If I change the language to Norwegian it becomes NOK, but I absolutely don’t want the text to be Norwegian.

can we get an option to use a custom currency or just use the HA currency?

**Comment by 13robin37** [comment]
Just documenting for future self, you can fetch the currency with 
`return hass.config["currency"];`
I don't have a proper solution yet as the language variable might be used by multiple cards. Maybe we could use a global variable which matches the currency and returns the currency icon. Something like this:
`var hasscurrency = hass.config["currency"];
var currency = {
  "EUR": "€",
  "USD": "$"
}
return currency[hasscurrency];`

Thoughts @basbruss @CM000n?

**Comment by basbruss** [comment]
@13robin37 Just reading this back.
We could add this to the translation engine. So minimalist follows the HA frontend settings.

**Comment by 13robin37** [comment]
@basbruss, sure, but we would need to add short translations, hass only returns the long term format. I can start a PR for that, made some other adjustments regarding translation engine as well.

**Comment by basbruss** [comment]
@13robin37 Just started to add it to this PR #792 as that one already includes changes to default.yaml.
I am now checking which strings HA outputs to set them in an array with (`key`:`value`) as you already did with euro and US dollar

**Comment by 13robin37** [comment]
Maybe this helps:
https://en.wikipedia.org/wiki/ISO_4217#Active_codes
https://www.newbridgefx.com/currency-codes-symbols/

**Comment by basbruss** [comment]
Fixed and added with https://github.com/UI-Lovelace-Minimalist/UI/pull/792/commits/dbc10533445b4df0ce7b59acaac9b1c0f71ad1f5
