### ISSUE TITLE
typo in button_card_templates.yaml:1100 media_player_with_controls

### ISSUE THREAD

**Issue by GaoMax** [UI-Lovelace-Minimalist/UI#65]
Hi,
I'm currently on vacation so I couldn't make a pull request. But I wanted to mention, that there is a typo in media_player_with_controls, which results in the card not loading.
entity_id: '[[[ return entity.ulm_card_media_player_with_controls_entity ]]]' should be
entity_id: '[[[ return variables.ulm_card_media_player_with_controls_entity ]]]'

**Comment by vncnt-dev** [comment]
This has already been solved in https://github.com/UI-Lovelace-Minimalist/UI/pull/62 and just needs to be merged.

**Comment by CM000n** [comment]
Thank you for pointing this out. This should be fixed in the next release
