### ISSUE TITLE
After install with "Include custom card resources it's depending on" is checked when rendering page sometimes dependencies are not found

### ISSUE THREAD

**Issue by TomasMonkevic** [UI-Lovelace-Minimalist/UI#650]
**Describe the bug**
When trying to view the minimalist dashboard I get `Custom element doesn't exist: button-card` errors.

This issue is more noticeable on mobile devices via the Home Assistant app, but sometimes it also appears on desktops. Sometimes force refresh helps to resolve this issue on desktop but there is no such option in the app. In general, the UI is unstable every second time the dashboard doesn't load because of this error and I don't think it should be expected to clear the cache every time

**To Reproduce**

1. Install UI-Lovelace-Minimalist with `Include custom card resources it's depending on.` enabled
2. View default generated dashboard
4. Notice errors

**Expected behavior**
Cards should be loaded without errors

**Screenshots**
![47803](https://user-images.githubusercontent.com/23715482/167272103-0dd97d38-75b6-4d39-8ce1-5f4ae08138cd.jpg)

**Comment by TomasMonkevic** [comment]
Update: This is definitely an issue with the automatic installation of dependencies. I reinstalled minimalist, and manually installed the dependencies and the issue seems to be gone.

**Comment by muppie** [comment]
I have a variant of this issue. If I install the cards manually, some of them cannot be found in the dashboard created by the integration. I also have the issue above.

**Comment by Neekster** [comment]
I had this issue as well, so I unchecked it and installed all dependencies manually. I've had no issues since.

**Comment by muppie** [comment]
Can all cards be installed manually, e.g. the minimalist battery card?
