### ISSUE TITLE
Room card tap actions are triggered when widgets are pressed on Android

### ISSUE THREAD

**Issue by anthonyma94** [UI-Lovelace-Minimalist/UI#653]
**Describe the bug**
When using the room card on Android, tapping either the card itself or any of its widgets triggers both tap actions. Issue does not seem to occur on iOS (checked on iPad). Checked on HA Companion app, Chrome, and Firefox on Galaxy Fold 3 and Galaxy Note 10 Plus, running Android 12.

**To Reproduce**

1. Open page with room card
2. Tap either the card or any of the widgets

**Expected behavior**
Either the card action or widget action triggers

**Screenshots**

**Additional context**

**Comment by KleSecGmbH** [comment]
Same here, clicking the Red is also triggering the green arrow in the Screenshot
![image](https://user-images.githubusercontent.com/91429214/167694326-4eb26852-a162-40dd-af4f-dec2d4b8d111.png)

**Comment by anthonyma94** [comment]
button-card v3.4.2 fixes this issue, closing now.
