### ISSUE TITLE
No cards are showing at all

### ISSUE THREAD

**Issue by HFeenstra** [UI-Lovelace-Minimalist/UI#666]
**Describe the bug**
I have triple checked all the settings, the default card after installing is showing fine, but now the custom card I added is not showing and also another default card which I just copy-paste in the yaml is not showing.

**To Reproduce**

Added all the different HACS parts for this use. All the HACS parts are the latest, no part were download as BETA parts...

**Expected behavior**
Was hoping to see the cards showing.

**Screenshots**
No screenshot, since there is no error to show, so the basics should be working fine??

**Additional context**
Following Every home smart tutorial to get things working, so I checked and checked all the settings. Typo would cause error, right? So why no error and yet nothing to show?

**Comment by Neekster** [comment]
Make sure you haven't both installed the custom cards through HACS and selected the "Include custom card resources it's relying on" checkbox during the UI Minimalist setup.

**Comment by walkerjohnsonofficial** [comment]
Hello! I had the same problem as everyone, added custom_card_esh_welcome.yaml
, and then added cards into home.yaml, but Minimalist can only display a title, and the content is not displayed.
