### ISSUE TITLE
Popup not working in Mobile App

### ISSUE THREAD

**Issue by M3m0rys** [UI-Lovelace-Minimalist/UI#668]
the Light Popup is not working in Mobile App
Working fine in Browser

Mobile App Version 2022.03.0-full
Device s22ultra with Android 12

**Comment by jrspowers** [comment]
I also have this problem on my android tablet from lenovo m10 plus on my iphone does it still work?

**Comment by Eltarius** [comment]
Works like a charm on my Samsung Galaxy A32 with HA app.

Have you add this variable in your lovelace card?
`ulm_card_light_enable_popup: true`

**Comment by M3m0rys** [comment]
> Works like a charm on my Samsung Galaxy A32 with HA app **with Hold-action**.
> 
> Have you add this variable in your lovelace card?
> `ulm_card_light_enable_popup: true`

Yes Code ist formatted correctly and variable is set true

**Comment by wokkeltje13** [comment]
same for the media player popup
Nokia 7.2 (Android 11)

**Comment by M3m0rys** [comment]
Since last core update it seems like popups are working again

**Comment by wokkeltje13** [comment]
For me popups are still not working. 
What version do you mean with latest core version?

**Comment by M3m0rys** [comment]
Supervisor 2022.5.2
Core 2022.05.5
OS 8.1

I also unchecked the "include custom cards and resources" frome the minimalist ui conig

**Comment by wokkeltje13** [comment]
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.1

Also unchecked the "include custom cards and resources" frome the minimalist ui config.

It is not working on Android and also not on MS Edge on my PC.

To be correct, You just need to keep pressing on the light button to get the popup?

**Comment by M3m0rys** [comment]
Wierd enough my pop-ups just stopped working again

**Comment by wokkeltje13** [comment]
It wasn't me :-)
I experience the issue with 

`      - type: "custom:button-card"
        template: card_light
        entity: light.bureaulamp
        variables:
          ulm_card_light_enable_color: true
          ulm_card_light_force_background_color: true
          ulm_card_light_enable_slider: true
          ulm_card_light_enable_collapse: true
          ulm_card_light_enable_popup: true`

and also for

`  - type: "custom:button-card"
    template: card_media_player
    entity: media_player.bureau
    name: Sonos
    variables:
      ulm_card_media_player_enable_art: true
      ulm_card_media_player_enable_controls: true
      ulm_card_media_player_enable_volume_slider: false
      ulm_card_media_player_enable_popup: true
`

**Comment by M3m0rys** [comment]
Our code looks the same 
I don't think the issue is the code

**Comment by PadEstel** [comment]
I had the same issue with pop ups not working. It seems to only work when running through a secure https connection. Once I had a this setup for my local network it started working. If it is working on your phone I'm guessing this is through Nabu Case cloud which is a secure https.

**Comment by wokkeltje13** [comment]
HTTPS has no effect for me.

**Comment by basbruss** [comment]
@wokkeltje13 How have you setup `browser_mod`?

**Comment by wokkeltje13** [comment]
Installed browser_mod using hacs and just added

browser_mod:
  prefix: "browser_"

to my configuration.yaml
still no success

**Comment by AndyVRD** [comment]
Your indentation is wrong, just add browser_mod: or if you want to use the prefix add a tab to your intentation. Can you check Chrome Developer Tools to see what error it trows about browser_mod?

If you want to use the prefix part it's like this:

```
browser_mod:
  prefix: "browser_"
```

**Comment by wokkeltje13** [comment]
strange things, nothing modified (intentation was correct, but github removed the spaces)

currently everything is working, even on http. don(t understand.

**Comment by basbruss** [comment]
Indentation gets lost when not pasted in a code block started with: "```yaml"

It could have been a caching issue that prevented your browser from loading the browser_mod content.

**Comment by damusmf** [comment]
i am also having the issue of pop up cards not working.  They seem to work if i go into HACS, reinstall any frontend thing, and reload.  It will then work until i close out of the companion app and relaunch it.  it will then no longer work.  Haven't had any luck finding any sort of error to help with the troubleshooting but if someone can point me in the direction i can take a look.  

Not sure why reinstalling something in HACS temporarily fixes it, but it does.  at least for me.  simply reloading the UI however, does not make it work.

Example of non working popup (the lamps), but none of them work anywhere.  They do work in a web browser, just not the companion app (android). 

```
  - type: grid
    columns: 2
    square: false
    cards:
      - type: "custom:button-card"
        template: card_light
        entity: light.office
        variables:
          ulm_card_light_name: Ceiling
      - type: "custom:button-card"
        template: card_light
        entity: light.office_lamps
        variables:
          ulm_card_light_enable_popup: true
          ulm_card_light_name: Lamps
```

**Comment by it-guy92** [comment]
I got the same problem.
ulm_card_light_enable_popup works on Chrome on my Android 12 device, but not on Home Assistant companion App on the same device. I deleted the Cache of the App but it is still not working.

**Comment by M3m0rys** [comment]
> I got the same problem.
> ulm_card_light_enable_popup works on Chrome on my Android 12 device, but not on Home Assistant companion App on the same device. I deleted the Cache of the App but it is still not working.

Do you use the New popup feature of the "theme"

**Comment by it-guy92** [comment]
I use this Code in the attached Picture. I'm sorry to post the Code as Picture, but i'm on my Mobile Phone and could not copy the Code from the Editor on Home Assistant.
![Screenshot_20220724-160600_Chrome](https://user-images.githubusercontent.com/18345556/180650871-c9604d5a-9993-487c-a56a-6048614a2dec.jpg)

But i Just found a solution, it wasnt enough to clear the Cache of home Assistant companion Android app, i even needed to delete Data of the App. Now its working and the light popup opens.

**Comment by wterpstra** [comment]
It indeed looks like some very persistent caching on the companion app side. Clearing the data & cache in android settings did the trick. Thanks @it-guy92!
