### ISSUE TITLE
Add windows/ doors to Custom-card "Counter Lights/Cover Card"

### ISSUE THREAD

**Issue by 1liminal1** [UI-Lovelace-Minimalist/UI#671]
**Is your feature request related to a problem? Please describe.**
Add windows and or doors to the Counter Lights/Cover Card card

**Describe the solution you'd like**
Create a new variable that covers doors and windows

**Describe alternatives you've considered**
Im looking into it 

**Additional context**
Pretty much covers it I think :)

**Comment by lucasfr** [comment]
Would it be possible to a custom text option?

**Comment by wilbiev** [comment]
Cleaning up issue list
