### ISSUE TITLE
Navigation wrong for 5th button on welcome card

### ISSUE THREAD

**Issue by jrac86** [UI-Lovelace-Minimalist/UI#674]
**Describe the bug**
In the custom_card_esh_welcome.yaml, the navigation for the 5th button is incorrectly pointing to item 1 

In item 5's second item:                 navigation_path: "[[[ return variables.entity_1.nav; ]]]"

   

>       item5:
      card:
        type: "custom:button-card"
        template: "card_esh_welcome_pill_nav"
        custom_fields:
          item1:
            card:
              type: "custom:button-card"
              tap_action:
                action: "navigate"
                navigation_path: "[[[ return variables.entity_5.nav; ]]]"
              icon: "[[[ return variables.entity_5.icon ]]]"
              styles:
                icon:
                  - color: "[[[ return `rgba(var(--color-${variables.entity_5.color}), 1)`;]]]"
                img_cell:
                  - background-color: "[[[ return `rgba(var(--color-${variables.entity_5.color}), 0.20)`;]]]"
          item2:
            card:
              type: "custom:button-card"
              tap_action:
                action: "navigate"
                navigation_path: "[[[ return variables.entity_1.nav; ]]]"
              name: "[[[ return variables.entity_5.name ]]]"

**To Reproduce**

If you click the area under the image for the 5th button, it will direct to the 1st button's navigation
**Expected behavior**
Should direct to the 5th button's page

**Comment by Eltarius** [comment]
Same like this PR: https://github.com/UI-Lovelace-Minimalist/UI/pull/626
