### ISSUE TITLE
Thermostat Card: Fan Only

### ISSUE THREAD

**Issue by renzoberendsen** [UI-Lovelace-Minimalist/UI#681]
You can not call the service fan only.
This is only with fan only on the HVAC, not with the fan only entity.

Simple fix:
In line 784:
service: "climate.set_hvac_mode"

instead of:
service: "climate.set_hvac_mode**]**"

That "]" caused the error. I was able to solve it myself but I'd like to report this as a bug.

**Comment by schumijo** [comment]
#683

**Comment by finder39** [comment]
This can be closed

**Comment by schumijo** [comment]
Solved in 1.0.1
