### ISSUE TITLE
HA forum thread re-read for new cards

### ISSUE THREAD

**Issue by Paddy0174** [UI-Lovelace-Minimalist/UI#7]
I think it could be a good idea to re-read the HA forum thread and see, what different things could be found to include into the repo.

Eg. tpx01 (I think) made a room_card with a nice background as a navigation card. Should this be implemented? I'd vote for to do so.

**Comment by Paddy0174** [comment]
Went through the thread and found

* Open/closed window or door by clemalex [here](https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/50?u=paddy0174)
* Alarm panel by clemalex [here](https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/52?u=paddy0174)
* 2-line-1-button card by clemalex [here](https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/55?u=paddy0174)
* Smoke detector by clemalex [here](https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/55?u=paddy0174)
* Fan (?) by clemalex [here](https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/69?u=paddy0174)
* 5-number card by clemalex [here](https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/72?u=paddy0174)
* Another fan card by SNoof85 [here](https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/163?u=paddy0174)
* Room card (navigation to room) [here](https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/169?u=paddy0174)
* Map card by clemalex [here](https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/177?u=paddy0174)
* Printer card from clemalex [here](https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/219?u=paddy0174)

Turns out, most of the cards in the thread are from clemalex... 👍

**Comment by cyrilphoenix71** [comment]
Il would be great also to continue to dev all cards present in the original inspiration source : https://www.behance.net/gallery/88433905/Redesign-Smart-Home

**Comment by Paddy0174** [comment]
@cyrilphoenix71 Would you mind giving some explicit example, what would be of interest for you? Some of the things in the original design aren't possible in HA, unfortunately. 

But with some examples, we'll see. If it is feasable, sure!

**Comment by KaherdinTristan** [comment]
For a newbie like me, the implementation of popup cards with Homekit styled light adjustments, is a pain to configure.

If the is some way to install and configure more easily that would be awesome

**Comment by cyrilphoenix71** [comment]
@Paddy0174 :

- Wifi card
- Meteo card
- Scene popup
- Music player card
- Video player card
- Camera card

**Comment by Paddy0174** [comment]
@KaherdinTristan 
Right now there isn't an easy way to add these styled pop-ups, but we'll def. get there. It's not implemented in the "theme" so I can't say how this even works. Schumijo posted his version in the thread, in one of the next releases we will have this iplemented and than I can say something about it. Sorry, but I'll take a closer look, promised!

@cyrilphoenix71 
* Wifi card <= this one will be possible in one of the next releases, but I don't plan to implement it in the main code, but as a `custom-card`. 
* Meteo card <= a weather-card is coming as well, but it will be more in the direction of the original weather card from HA than the one from Behance. But that card looks nice, at least we could write up an example on how to configure a card to show like that. 
* Scene popup <= as I said above, pop-ups aren't on the immediate task list, this will be handled in a future release, but I wouldn't set my money on "next week". ;) But yes, that will be coming as a feature, but with a wider approach, so all pop-ups can be configured and changed. This will depend on `browser-mod` and therefor will need some extra work.
* Music player card  
  Video player card
  <= this will be handled by enhanced media-player-cards. I wanted to start a little project for the re-work of the media-player-cards soon. 
Video player card }
* Camera card <= this was asked in the thread as well, already put it on the to-do-list. :+1:

**Comment by KaherdinTristan** [comment]
@Paddy0174 
🤟 🥲 
This is awesome

**Comment by Dodoooh** [comment]
plant card by schumijo [here](https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/120)

**Comment by max5962** [comment]
You can find awesome work here : https://forum.hacf.fr/t/dashboard-minimalist/5507/282?u=max5962 :)
