### ISSUE TITLE
custom_card_esh_welcome wrong link behind name of entity_5

### ISSUE THREAD

**Issue by Bushbrand17** [UI-Lovelace-Minimalist/UI#716]
**Describe the bug**
When clicking on the name below the icon of my entity_5 (my control page) in the esh_welcome_card I get navigated to my entity_1 (shopping list) page. When clicking on the icon of entity_5 however I get to the correct page. 

**To Reproduce**

1. Go to esh_welcome_card
2. Click on the name below entity_5
3. See page behind entity_1 opening instead of the page behind entity_5

**Expected behavior**
When clicking on the name below entity_5 I should get to the same page as when I click on the icon of entity_5.

**Screenshots**
https://im4.ezgif.com/tmp/ezgif-4-0209610f7f.gif

**Additional context**
Code:
- type: "custom:button-card"
    template: "card_esh_welcome"
    triggers_update: "input_boolean.minimalist_dropdown"
    variables:
      ulm_card_esh_welcome_collapse: input_boolean.minimalist_dropdown
      ulm_weather: "weather.openweathermap"
      entity_1:
        nav: "shopping"
        icon: "mdi:cart"
        name: Kaufen
        color: "blue"
      entity_2:
        nav: "lights"
        icon: "mdi:lightbulb"
        name: "Lights"
        color: "yellow"
      entity_3:
        nav: "music"
        icon: "mdi:music"
        name: Musik
        color: "green"
      entity_4:
        nav: "gilbert"
        icon: "mdi:robot-vacuum"
        name: Gilbert
        color: "purple"
      entity_5:
        nav: "control"
        icon: "mdi:flask"
        name: Control
        color: "red"

**Comment by basbruss** [comment]
@Bushbrand17 This bug is already been fixed with https://github.com/UI-Lovelace-Minimalist/UI/pull/621.
You can update the card code by redownloading the yaml file from here: https://github.com/UI-Lovelace-Minimalist/UI/blob/main/custom_cards/custom_card_esh_welcome/custom_card_esh_welcome.yaml
