### ISSUE TITLE
Can't get pollen card to display

### ISSUE THREAD

**Issue by sjoshua270** [UI-Lovelace-Minimalist/UI#731]
**Describe the bug**
I am having trouble getting the new pollen card to work.
I am getting this error:

```
TypeError: Cannot read properties of undefined (reading 'state') in 
'let pollen_state_label = variables.custom_card_wsly_pollen_none;
  if (entity.state == "very_low")...'
```

**To Reproduce**
This is what I have in my welcome-header.yaml:

    - type: "custom:button-card"
      template: custom_card_wsly_pollen
      variables:
        custom_card_wsly_pollen_tree: sensor.tomorrow_io_home_tree_pollen_index
        custom_card_wsly_pollen_grass: sensor.tomorrow_io_home_grass_pollen_index
        custom_card_wsly_pollen_weed: sensor.tomorrow_io_home_weed_pollen_index
        custom_card_wsly_pollen_tree_icon: mdi:tree
        custom_card_wsly_pollen_grass_icon: mdi:grass
        custom_card_wsly_pollen_weed_icon: mdi:flower-pollen

I was getting errors about missing icons, so I included the icons manually. Now, my error is (same as above):

```
TypeError: Cannot read properties of undefined (reading 'state') in 
'let pollen_state_label = variables.custom_card_wsly_pollen_none;
  if (entity.state == "very_low")...'
```

I copy-pasted the ```custom_card_wsly_pollen``` folder from GitHub, so I am fairly sure I'm not missing any code.

**Expected behavior**
I was really hoping to use this card, as my wife suffers from allergies on a daily basis

**Comment by basbruss** [comment]
Have you enabled the sensors in the tomorrow.io integration? They are disabled as default.

**Comment by sjoshua270** [comment]
What!? Well, that worked. This should definitely be added to the docs...

I appreciate your help
