### ISSUE TITLE
Custom-card "Lock" not working - ulm_custom_card_eraycetinay_lock_language_variables is missing!

### ISSUE THREAD

**Issue by GD-Dal** [UI-Lovelace-Minimalist/UI#734]
I try to use the custom card "Lock", so in the custom_cards folder I have created a folder called custom_card_eraycetinay_lock since that is the name of the template.
Inside that folder I have created a file called custom_card_eraycetinay_lock.yaml and copied all the template code from it's github page here: https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_eraycetinay_lock/

But it gives me the error "ulm_custom_card_eraycetinay_lock_language_variables is missing!"
So what can be wrong?

Thanks

**Comment by basbruss** [comment]
Hi,

You also have to download the corresponding language file to the same folder to let the card work.
See here for the language files: https://github.com/UI-Lovelace-Minimalist/UI/tree/main/custom_cards/custom_card_eraycetinay_lock/languages

It's described on the wiki, but not as clearly as it could be 😉 
<img width="958" alt="image" src="https://user-images.githubusercontent.com/68892092/172318841-316f6a37-9979-460b-9aff-8510d721a6fa.png">

**Comment by GD-Dal** [comment]
It works!
Had to restart HA to see the changes. A YAML configuration reloading wasn't enough.
Thank you for the swift response.

**Comment by Whininie** [comment]
Hi, mine does not work.

But the card is not sending commands to my lock.
I can click on it but nothing happens :*(

**Comment by GD-Dal** [comment]
Hi.
Button press does not work for me either. 
After the fix mentioned above, I can see the card and the state of the lock. But pressing on the card does not change the state of the lock. 
Used the same entity to change the lock state in development tools, and it works fine there

**Comment by TroLoos** [comment]
How about an error like this (sorry for the pic instead of code - it doesn't allow me to copy text):

<img width="491" alt="custom_card_eraycetinay_lock" src="https://user-images.githubusercontent.com/24640072/175126137-cdb0b4f2-ab15-488f-aec9-9949d2358d68.png">

I've copied preferred language file to the custom_card_eraycetinay_lock folder, but this error is not exactly about the translation variables, right?
