### ISSUE TITLE
Person info card. Binary driving sensor

### ISSUE THREAD

**Issue by Qpernicus** [UI-Lovelace-Minimalist/UI#736]
Hi.  On the one hand this is no issue as such but in the custom card person info from @jordandrako : how do you create the driving binary sensor? I can't seem to find that. 

Sorry if this is the wrong spot for such questions.

**Comment by jordandrako** [comment]
You can create a binary sensor that works in your case, but for me I have the home assistant companion app report what Bluetooth devices me and family's phones are connected to. If a phone is conncted to one of the cars' Bluetooth addresses, the binary sensor turns on. I have the Bluetooth addresses in an input text so I can easily update it if we get a new car later. I'm on mobile but I'll update with the sensor code soon.

**Comment by jordandrako** [comment]
Input text helper with both cars' bluetooth address separated by a ",".
![image](https://user-images.githubusercontent.com/7110658/172907707-b63e0ac6-cb11-4db1-8211-616789de1f09.png)

```yaml
template:
  - binary_sensor:
      name: Jordan In Car
      unique_id: 36a69f3a-81dd-47f8-9eb9-0bd94d81814f
      state: >-
        {% set cars = states('input_text.car_bt_mac').split(',') %}
        {% set result = namespace(inCar = false) %}
        {% for car in cars %}
          {% if car in state_attr('sensor.jordans_phone_bluetooth_connection', 'connected_paired_devices') %}
            {% set result.inCar = true %}
          {% endif %}
        {% endfor %}
        {{ result.inCar }}
```

**Comment by Qpernicus** [comment]
Thx for the elaborate answer. I have an iPhone and dont have the BT sensor I believe. So I'll need to figure out another way.

**Comment by 13robin37** [comment]
You could test out the activity sensor which is reported by the Companion app. That one reports something like driving as far as I know.

**Comment by Qpernicus** [comment]
Yeah. That goed to Unknown to often. I used the proximity integration/sensor to make a binary. Seems to work.
