### ISSUE TITLE
Italian language is incorrect

### ISSUE THREAD

**Issue by Nik18111997** [UI-Lovelace-Minimalist/UI#738]
Hi, thanks a lot for work, today i installed the repository, but in language translation it, the traduction is wrong

before :
---
ulm_language_variables:
  variables:
    ulm_on: "Acceso"
    ulm_off: "Spento"
    ulm_open: "Aperto"
    ulm_closed: "Chiuso"
    ulm_unavailable: "Non disponibile"
    ulm_standby: "In pausa"
    ulm_idle: "Inattivo"
    ulm_currency: "€"
    ulm_auto: "Auto"
    ulm_heat: "Calore"
    ulm_cool: "Raffreddare"
    ulm_dry: "Asciugare"
    ulm_fan_only: "Solo ventilatore"
    ulm_heat_cool: "Calore/Raffreddare"
    ulm_heating: "Riscaldamento"
    ulm_cooling: "Raffrescamento"
    ulm_person_state_home: "home"
    ulm_person_state_away: "away"
    ulm_person_state_not_home: "away"
    ulm_device_state_home: "online"
    ulm_device_state_not_home: "offline"
    ulm_popups_back: "Indietro"
    ulm_popups_toggle: "Alzare"
    ulm_popups_statistics: "Statistica"
    ulm_popups_history: "Storia"
    ulm_popups_brightness: "Luminosità"
    ulm_popups_color_temp: "Temperatura"
    ulm_popups_color: "Colore"
    ulm_unknown: "unknown"
    ulm_alarm_armed_home: "Armed home"
    ulm_alarm_armed_away: "Armed away"
    ulm_alarm_armed_night: "Armed night"
    ulm_alarm_disarmed: "Disarmed"
    ulm_alarm_arming: "Arming"
    ulm_alarm_triggered: "TRIGGERED"
    ulm_playing: "Playing"
    ulm_paused: "Paused"
    ulm_updates_available: "Updates available!"
    ulm_no_updates_available: "No updates available"
    ulm_morning: "Buon giorno"
    ulm_afternoon: "Buon pomeriggio"
    ulm_evening: "Buona serata"
    ulm_hello: "Ciao"
    ulm_cleaning: "Cleaning"
    ulm_returning: "Returning"
    ulm_docked: "Docked"
    ulm_mopping: "Mopping"

after:
---
ulm_language_variables:
  variables:
    ulm_on: "Acceso"
    ulm_off: "Spento"
    ulm_open: "Aperto"
    ulm_closed: "Chiuso"
    ulm_unavailable: "Non disponibile"
    ulm_standby: "In pausa"
    ulm_idle: "Inattivo"
    ulm_currency: "€"
    ulm_auto: "Auto"
    ulm_heat: "Calore"
    ulm_cool: "Raffreddare"
    ulm_dry: "Asciugare"
    ulm_fan_only: "Solo ventilatore"
    ulm_heat_cool: "Calore/Raffreddare"
    ulm_heating: "Riscaldamento"
    ulm_cooling: "Raffrescamento"
    ulm_person_state_home: "In Casa"
    ulm_person_state_away: "Non In Casa"
    ulm_person_state_not_home: "Non In Casa"
    ulm_device_state_home: "online"
    ulm_device_state_not_home: "offline"
    ulm_popups_back: "Indietro"
    ulm_popups_toggle: "Schiacciare"
    ulm_popups_statistics: "Statistica"
    ulm_popups_history: "Storia"
    ulm_popups_brightness: "Luminosità"
    ulm_popups_color_temp: "Temperatura"
    ulm_popups_color: "Colore"
    ulm_unknown: "Sconosciuto"
    ulm_alarm_armed_home: "Armato a casa"
    ulm_alarm_armed_away: "Armato non in casa"
    ulm_alarm_armed_night: "Armato notte"
    ulm_alarm_disarmed: "Disarmato"
    ulm_alarm_arming: "Armato"
    ulm_alarm_triggered: "Azionato"
    ulm_playing: "Playing"
    ulm_paused: "Pausa"
    ulm_updates_available: "Aggiornamento Disponibile!"
    ulm_no_updates_available: "Non ci sono aggiornamenti"
    ulm_morning: "Buon giorno"
    ulm_afternoon: "Buon pomeriggio"
    ulm_evening: "Buona serata"
    ulm_hello: "Ciao"
    ulm_cleaning: "Pulizia"
    ulm_returning: "Ritorno"
    ulm_docked: "In base"
    ulm_mopping: "Lavaggio"

**Comment by basbruss** [comment]
It will be solved with the next release and its translation engine #756
