### ISSUE TITLE
saxel_fan - the slider never reaches 100% if percentage step not multiple of 100

### ISSUE THREAD

**Issue by benyaming** [UI-Lovelace-Minimalist/UI#751]
**Describe the bug**
My fan has percentage step 16.6, so this is how my slider looks like:
![image](https://user-images.githubusercontent.com/18378470/174235910-7ebec966-fd4f-4033-8254-05816d1a15c0.png)

Btw, I tried to hide oscillation button since my fan doesn't support this feature, but it didn't work for me, so I would really appreciate if someone could share some instructions.

**Comment by benbur98** [comment]
Solved by PR #1194 as can set custom min/max values for the slider.
