### ISSUE TITLE
Does not find my-cards frontend integration.

### ISSUE THREAD

**Issue by sbeaudoin** [UI-Lovelace-Minimalist/UI#753]
**Describe the bug**
Missing my-cards dependency.

**To Reproduce**
1. Install latest Home Assistant OS 8.2 as a VM on Proxmox.
2. From HACS
    2.1. Into integrations
        2.1.1. Install "browser_mod" v1.5.3
    2.2. Into fontend
        2.2.1. Install "auto-entities" v1.11.0
        2.2.2. Install "button-card" v3.4.2
        2.2.3. Install "mini-graph-card" v0.11.0
        2.2.4. Install "mini media player" v1.16.4
        2.2.5. Install "light entity card" v5.0.0
        2.2.6. Install "card-mod" 3.1.5
        2.2.7. **Try to find "my-cards" and quit trying.**
3. Restart Home Assistant from "Settings/System".
4. Into "Settings/Devices & Services/", 
    4.1. Add "UI Lovelace Minimalist".
    4.2. Configure it and activate the creation of the side menu item.
5. Restart Home Assistant from "Settings/System".
6. Access the side menu item "UI Lovelace Minimalist".

**Expected behavior**
1. The items displayed should use the minimalist theme, they don't.

![Items](https://user-images.githubusercontent.com/3873484/174456965-0ff0afd3-fcfc-462a-837a-01ab44eafe78.png)

2. The log should not display "ERROR (MainThread) [custom_components.ui_lovelace_minimalist.load_plugins] HACS Frontend repo "my-cards" is not installed, See Integration Configuration.".

**Additional informations**
1. It seems "my-cards" as been renamed to "my cards bundle" or something similar.  Can't find it in HACS in the frontend section.
2. Here is the content of "www/community"
![2022-06-18_17-05-00](https://user-images.githubusercontent.com/3873484/174457041-18be083d-bde5-4427-95b6-01536eafccc9.png)

**Comment by sbeaudoin** [comment]
Update.  Setted "minimalist-desktop" as the main theme in the account settings and created a new dashboard based on the theme "minimalist-desktop".  Now, the "UI Lovelace Minimalist" show correctly, except an error for those who use "my-slider".  I think i've seen this is included in the "my-cards" I can't find.

![2022-06-18_17-22-01](https://user-images.githubusercontent.com/3873484/174457407-829dbd9d-b3f8-4cdf-b2ef-e0713fb12a42.png)

**Comment by sbeaudoin** [comment]
Found the problem.  It seems the developper is not considered official by HACS and the repo must be added manually.  I will try it and see if it solves the problem.

**Comment by avancs** [comment]
were you able to find a solution for this? I am exactly getting the same error! Any help is appreciated...
