### ISSUE TITLE
Dashboard gone. Integration Failed to set up after updating to v1.0.0

### ISSUE THREAD

**Issue by antonio1475** [UI-Lovelace-Minimalist/UI#766]
**Describe the bug**
After updating to 1.0.0 minutes ago, Minimalist doesn't load.
Integration Failed to Set up (logs below). Error setting up entry UI Lovelace Minimalist for ui_lovelace_minimalist

**To Reproduce**

1. Update to 1.0.0
2. Restart
3. Go to Settings > Integrations > Minimalist UI

**Expected behavior**
Dashboard to exist and work as before the update

**Screenshots**
![image](https://user-images.githubusercontent.com/63130724/175069089-60bb0060-f876-4fd3-bd0f-03b8c900c3fa.png)
**Additional context**

> Logger: homeassistant.config_entries
> Source: custom_components/ui_lovelace_minimalist/configure.py:91
> Integration: UI Lovelace Minimalist ([documentation](https://ui-lovelace-minimalist.github.io/UI/), [issues](https://github.com/UI-Lovelace-Minimalist/UI/issues))
> First occurred: 17:05:33 (1 occurrences)
> Last logged: 17:05:33
> 
> Error setting up entry UI Lovelace Minimalist for ui_lovelace_minimalist
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 79, in async_setup_entry
>     return await async_initialize_integration(hass=hass, config_entry=config_entry)
>   File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 61, in async_initialize_integration
>     configure_cards(hass=hass, ulm=ulm)
>   File "/config/custom_components/ui_lovelace_minimalist/configure.py", line 91, in configure_cards
>     shutil.copy2(
>   File "/usr/local/lib/python3.9/shutil.py", line 444, in copy2
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "/usr/local/lib/python3.9/shutil.py", line 266, in copyfile
>     with open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: '/config/ui_lovelace_minimalist/custom_actions/custom_actions.yaml'
>

**Comment by antonio1475** [comment]
I see it now. I redownloaded it before reporting it but the hotfix wasn't there yet.
In parallel I manually created the custom_actions.yaml file and 

Anyway, with custom_actions.yaml and/or 1.0.0-hotfix it's working now. Thank you!

**Comment by basbruss** [comment]
@antonio1475 There were 2 fixes, as immediately noticed after the first that the custom_actions.yaml was not copied over to the button_card_templates directory
