### ISSUE TITLE
Thermostat card reports "undefined" for HVAC state "waiting"

### ISSUE THREAD

**Issue by willyp713** [UI-Lovelace-Minimalist/UI#787]
**Describe the bug**
Thermostat card reports `undefined` when HVAC equipment is in state `waiting`.

**To Reproduce**

1. Quickly switch modes of climate system (or switch on/off) and most modern systems will enter a "waiting" period to protect the equipment from sudden restarts. 
2. Climate system reports state `waiting` to `hvac_action`
3. Thermostat card shows `undefined` on the card UI because it does not recognize state `waiting`

**Expected behavior**
Card should print `Waiting` instead of `undefined` for the state `hvac_action`

**Screenshots**

**Additional context**
Certain thermostat systems have a "waiting" mode - like when the device has been turned off and on quickly, they will have a period of waiting before the equipment resumes operation. For normal operation, this would be significant in cases of power outage or adjusting the system to find the right temperature.

Specifically, there is this state: `hvac_action: waiting`

Presumably we need to modify the Thermostat Card to account for this state, and possibly the language translation engine.

**Comment by basbruss** [comment]
I have checked both HA documentation and the Lokalise library. Both sadly do not support `hvac_action: waiting`.
Therefore the engine cannot translate it.
<img width="200" alt="image" src="https://user-images.githubusercontent.com/68892092/175763915-58d9384c-cc45-4244-bc59-523a895bf14f.png"> 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/68892092/175763935-255b64f0-4f0d-439c-970c-248d7fb158b4.png">


But the engine should return to the original state if it's not translatable. So we need to check if the logic is working correctly.

**Comment by willyp713** [comment]
Oh interesting. I added this [Lennox S30 Integration](https://github.com/PeteRager/lennoxs30) so I guess that must be what is passing through the `waiting` state.

This gets outside of my comfort zone to understand what it is doing, but it has quite a few modes and settings that go well beyond the basic Thermostat entity of Home Assistant.

**Comment by basbruss** [comment]
Should be returning the `waiting` state with this PR #792
