### ISSUE TITLE
Cover card "Gate" showing incorrect operational icons

### ISSUE THREAD

**Issue by DevTodd** [UI-Lovelace-Minimalist/UI#800]
**Describe the bug**
When selecting "Gate" as the cover card option the icon changes to reflect a gate however the "open" / "close" icons remain up and down.  I would say 99% of residential gates don't open up or down.  When combining ulm_card_curtain_display_collapse_expand true with ulm_card_cover_gate true the icon is replaced with curtains but the operational icons are correct.  

**To Reproduce**
enable ulm_card_cover_gate true to see the wrong operational buttons
enable ulm_card_cover_gate true and ulm_card_curtain_display_collapse_expand true to see the correct operational icons for a gate but wrong display icon.

**Expected behavior**
Either the combination of the two variables should be a gate icon with expand operational icons or I would suggest that ulm_card_cover_gate use expand operational icons because I'm doubtful many people have gate arms that go up and down.

**Screenshots**
![image](https://user-images.githubusercontent.com/32474971/175971091-72652140-358a-4d93-8855-9e9964c097be.png)
![image](https://user-images.githubusercontent.com/32474971/175971328-bb07a3d6-daa5-49b1-a381-7b53924781cb.png)

**Comment by basbruss** [comment]
Should be fixed with #803
