### ISSUE TITLE
Change sidebar& admin access

### ISSUE THREAD

**Issue by Qpernicus** [UI-Lovelace-Minimalist/UI#806]
I would like to make the follow persistent in the config:

```
    dashboard_url = "ui-lovelace-minimalist"
    dashboard_config = {
        "mode": "yaml",
        "icon": ulm.configuration.sidepanel_icon,
        "title": ulm.configuration.sidepanel_title,
        "filename": "ui_lovelace_minimalist/dashboard/ui-lovelace.yaml",
        "show_in_sidebar": False,
        "require_admin": True,
```

The bottom 2 are switched around.. The first one is probably the one in the config in the 'integrations' tab? Is that correct?

But can i also set the second one from gui? Atm i always change these 2 after an update en reboot.. little annoyance.

**Comment by wilbiev** [comment]
Cleaning up issue list
