### ISSUE TITLE
I made a figma

### ISSUE THREAD

**Issue by sildehoop** [UI-Lovelace-Minimalist/UI#81]
I have made an Figma with almost all the components this way you can make pictures for on the wiki
https://www.figma.com/file/dOQKR8DCP2mvH7zesjU8L6/UI-Lovelace-Minimalist?node-id=0%3A1

**Comment by CM000n** [comment]
That's neat! Thank you very much

**Comment by CM000n** [comment]
Hello @sildehoop. Would you mind posting your post with the Figma again under the discussions:
https://github.com/UI-Lovelace-Minimalist/UI/discussions. 
Because it doesn't quite fit here in the Issues, since it's neither a direct improvement to the code nor a bug report. 😉

**Comment by sildehoop** [comment]
I now didn't think about the discussions 😉
