### ISSUE TITLE
Custom-card "Lock" not working - ButtonCardJSTemplateError: TypeError:

### ISSUE THREAD

**Issue by GD-Dal** [UI-Lovelace-Minimalist/UI#810]
Hi.
I'm getting an error when trying to add this card.
The error looks like this (copy / paste does not work for some reason):
![image](https://user-images.githubusercontent.com/59178483/176367075-6e574fd9-c167-4a3d-9d1a-66ce4b41aece.png)
I have simply copied the template code and usage code from here: [https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_eraycetinay_lock/](url), and changed the entity to my own lock

The folder structure looks like this:
![image](https://user-images.githubusercontent.com/59178483/176367538-4dc96120-692c-49e1-9ca5-49d49d052738.png)

What can be wrong?
This started after the Minimalist UI update that was released a few days ago..
But the card did not work properly before that either. It showed the state of the lock, but it was not possible to click on it to change the state of the lock.

Thanks

**Comment by basbruss** [comment]
@GD-Dal 

Do you have the variables set up with the `ulm_` prefix?

**Comment by GD-Dal** [comment]
Thanks for answering.
I do.
This is how the entry looks like in home.yaml:

`- type: "custom:button-card"
    entity: lock.utedor_las
    template: "custom_card_eraycetinay_lock"
    name: "Dørlås"
    variables:
    ulm_custom_card_eraycetinay_lock_tap_control: true
    ulm_custom_card_eraycetinay_lock_battery_level: sensor.utedor_las_battery
    ulm_custom_card_eraycetinay_lock_door_open: binary_sensor.utedor_sensor_contact
    triggers_update:
      - "sensor.utedor_las_battery"
      - "binary_sensor.utedor_sensor_contact"`

**Comment by basbruss** [comment]
>     entity: lock.utedor_las
>     template: "custom_card_eraycetinay_lock"
>     name: "Dørlås"
>     variables:
>     ulm_custom_card_eraycetinay_lock_tap_control: true
>     ulm_custom_card_eraycetinay_lock_battery_level: sensor.utedor_las_battery
>     ulm_custom_card_eraycetinay_lock_door_open: binary_sensor.utedor_sensor_contact
>     triggers_update:
>       - "sensor.utedor_las_battery"
>       - "binary_sensor.utedor_sensor_contact"```

Is the indentation the same as in this code snippet? As that will not work.
Your config should need to be compatible with the newest version of the card code

**Comment by GD-Dal** [comment]
Ah, so simple.
Fun with YAML. I put in 2 spaces for each variable, and voila!

Thank you so much
