### ISSUE TITLE
Strange behavior with the new Adaptive Dash and Popups

### ISSUE THREAD

**Issue by NdR91** [UI-Lovelace-Minimalist/UI#817]
**Describe the bug**
Popup on the right side are selected by a doble tap and the input select (as per documentation provided).
The popup is showed during the transition, but after that it disappears.

**To Reproduce**

1. Slightly modified the standard `main.yaml` file, adding some simple cards;
2. Modified the `popup.yaml` file, adding the input_select entity and the light and thermostat popups (just uncommented and added the entities);
3. Doble tapping on the cards supposed to activate the popups;

**Expected behavior**
A popup on the right side is expected to be shown.

**Screenshots**
![2022-06-29_12-01-35_170](https://user-images.githubusercontent.com/52299148/176440728-0cbf3758-4775-43d5-a59c-48bbeaab8fe8.gif)

**Additional context**
As you can see from the above gif:

1- The column on the first row seems to be longer then the ther rows;
2- The transition of the popups is appearing. But then, the popup disappears.

**Comment by basbruss** [comment]
Hi @NdR91 

Haven't seen this behavior before. Can you tell which version of state-switch you are using? (should be `1.9.3`)
The weather card looks to like ignore/extend the set grid-areas limits. Maybe try without?

**Comment by NdR91** [comment]
Oh god. I had the 1.9.5 and i already knew the supported version is the 1.9.3. Probably I updated it in the last days...
Sorry for this useless issue.

Regarding the weather card: yes it's ignoring the areas limits. Maybe i'll change the card.

Thank you!
