### ISSUE TITLE
Input select / Option select Card 

### ISSUE THREAD

**Issue by StrandmonYellow** [UI-Lovelace-Minimalist/UI#834]
I Would like a card where i can choose an option from a given selection. In my case so that I can select a preset for my WLED ledstrip. Something like the images below but then for UI Minimalist Dashboard. 

![image](https://user-images.githubusercontent.com/99552124/177058053-efbb1f12-6967-4742-9122-89ecb0ce1663.png)

![image](https://user-images.githubusercontent.com/99552124/177058084-cd1568fd-799d-48b4-92e5-edb55b3bf11f.png)

There are cards currently for: 
- input boolean
- input number
- input date/time

The missing one would be something like: "input select" or "option select". 

An alternative would be to use the scenes card for a selection of some presets, but that is not ideal in my opninion. 

Thanks in advance!

**Comment by Boh1** [comment]
I also would like this to help set some house modes (home, away, vacation, etc.) from the Minimalist interface. 

An example of similar card is the "Select list Card" on HACS.

**Comment by markmghali** [comment]
Looking for this still for my select.harmony_hub_activities entity. Did this card ever get created?

**Comment by wilbiev** [comment]
Cleaning up issue list
