### ISSUE TITLE
light card doesn't show up on Chrome or Android-App

### ISSUE THREAD

**Issue by toni8767** [UI-Lovelace-Minimalist/UI#837]
Hi, I got the problem that the light-card does not show up in Chrome or the HA-App (Android 12 on Pixel 6 Pro). Sometimes a full restart of HA can help for short time, and then the light card disappears again.
In Firefox or Edge everything is shown as it used to be.

The thing is when i connect to HA over the internet and not in my LAN then the HA-App shows the light-card. When I'm back in LAN / WLAN they're gone.

Any ideas how this can be fixed ?

Thx in advance

**Comment by wilbiev** [comment]
Cleaning up issue list
