### ISSUE TITLE
speedtest not working

### ISSUE THREAD

**Issue by piechade** [UI-Lovelace-Minimalist/UI#843]
**Describe the bug**
I copied the newest yaml from https://github.com/UI-Lovelace-Minimalist/UI/blob/main/custom_cards/custom_card_irmajavi_speedtest/custom_card_irmajavi_speedtest.yaml and this is the result.

**Screenshots**
![chrome_j0xTVEnH4z](https://user-images.githubusercontent.com/1434005/177641360-92688871-4859-41c7-80f8-899de03eb0c0.png)

**Comment by basbruss** [comment]
Hi @piechade 

I have updated the code of the card to fix it. Also make sure you have a language file for this card from now on 😉

**Comment by piechade** [comment]
> Hi @piechade
> 
> I have updated the code of the card to fix it. Also make sure you have a language file for this card from now on 😉

de.yaml already created

**Comment by basbruss** [comment]
> > Hi @piechade
> > I have updated the code of the card to fix it. Also make sure you have a language file for this card from now on 😉
> 
> Where I can find the code?

Here: https://github.com/UI-Lovelace-Minimalist/UI/blob/main/custom_cards/custom_card_irmajavi_speedtest/custom_card_irmajavi_speedtest.yaml

**Comment by piechade** [comment]
> > > Hi @piechade
> > > I have updated the code of the card to fix it. Also make sure you have a language file for this card from now on 😉
> > 
> > 
> > Where I can find the code?
> 
> Here: https://github.com/UI-Lovelace-Minimalist/UI/blob/main/custom_cards/custom_card_irmajavi_speedtest/custom_card_irmajavi_speedtest.yaml

Sorry, not working. You have already 2022.07.0?

**Comment by basbruss** [comment]
Yes it’s working on 2022.07.0 
![908199BA-FF26-4669-835E-7F9A97B98486](https://user-images.githubusercontent.com/68892092/177701863-0da30d80-7783-47a1-a675-e9c65ffd09ff.jpeg)

**Comment by basbruss** [comment]
You could always check custom_components/ui_lovelace_minimalist/\_\_ui_lovelace\_\_/custom_cards/custom_card_speedtest/ for multiple language files
