### ISSUE TITLE
card box-shadow animation not see in android app

### ISSUE THREAD

**Issue by Nik18111997** [UI-Lovelace-Minimalist/UI#844]
**Describe the bug**
i make my cutom button card, i make when the entity is on the box shadows turn on with flash color.
in the browser chrome it`s all ok , but in the android application not see the box shadows 

**Screenshots**
![Cattura](https://user-images.githubusercontent.com/81594558/177768418-61c15d7d-3a63-4710-b445-5c2abe2214d9.PNG)

**Comment by basbruss** [comment]
Hi @Nik18111997 

To get a better understanding: you have altered the code to get a box-shadow?

Sometimes you have to reset the cache of the mobile app, especially when it does work in Chrome.

**Comment by Nik18111997** [comment]
Hi thanks for your reply, i try to clear cache to android app but not work,
![Screenshot_20220708-140235](https://user-images.githubusercontent.com/81594558/177988888-64f26ef9-51b2-4110-962c-f1dac0ae7515.jpg)
this is the phone screenshot,
![1](https://user-images.githubusercontent.com/81594558/177988949-7a069a2d-b979-4e81-bd89-e83fe7a7affe.PNG)
this is the code of card

**Comment by Nik18111997** [comment]
I try to see the problem, the problem is when setting the created dashboard as default, if I leave the default dashboard set and go to the created dashboard everything works

**Comment by basbruss** [comment]
I close this issue as it is related to a user build custom card and not to Minimalist itself.
