### ISSUE TITLE
Typos in example Battery card

### ISSUE THREAD

**Issue by HFeenstra** [UI-Lovelace-Minimalist/UI#852]
**Describe the bug**
Not a real bug, just in wiki some typos.

**To Reproduce**

1. Go to ['https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_battery/']
3. Scroll down to 'Usage'

**Expected behavior**
The spacing of the 4 ulm variables is a tab too much. Also the name of the name of the variable in the example is spelled wrong. Between battery and name needs to be '_'

**Screenshots**
<img width="638" alt="Schermafbeelding 2022-07-10 om 13 43 31" src="https://user-images.githubusercontent.com/25987376/178143479-d1bd1ecc-9c12-4a84-920f-a318fddcb68c.png">

**Additional context**

**Comment by mdb17** [comment]
created a pull request to correct the issues you pointed out.
