### ISSUE TITLE
custom_card_eraycetinay_lock - ulm_translation_engine is missing error

### ISSUE THREAD

**Issue by TroLoos** [UI-Lovelace-Minimalist/UI#855]
How about an error like this (sorry for the pic instead of code - it doesn't allow me to copy text):

<img width="491" alt="custom_card_eraycetinay_lock" src="https://user-images.githubusercontent.com/24640072/175126137-cdb0b4f2-ab15-488f-aec9-9949d2358d68.png">

I've copied preferred language file to the custom_card_eraycetinay_lock folder, but this error is not exactly about the translation variables, right?

**Comment by basbruss** [comment]
Hi @TroLoos 

Which version of minimalist have you installed? The ulm_translation_engine should be a part of it since `v1.0.0`.

**Comment by TroLoos** [comment]
Great hint @basbruss,

I didn't realise that development of this code is so rapid and I might have an "old" installation :-) - I installed it from newest source just recently. I updated to the most recent version and it works from the box.

Thanks a lot!
