### ISSUE TITLE
Custom Actions per button instance

### ISSUE THREAD

**Issue by TroLoos** [UI-Lovelace-Minimalist/UI#856]
Hi, I've noticed that there's a newly implemented idea to customize different actions:

`ulm_custom_actions:
  variables:
    ulm_card_tap_action: "toggle"
    ulm_card_hold_action: "popup"
    ulm_card_double_tap_action: "more-info"
    ulm_icon_tap_action: "popup"
    ulm_icon_hold_action: "none"
    ulm_icon_double_tap_action: "none"
    ulm_name_tap_action: "more-info"
    ulm_name_hold_action: "toggle"
    ulm_name_double_tap_action: "popup"`

That's a great thing... what I'm wondering is if it's possible to define custom actions differently for any card instance (like Input_boolean card)?

What I'm trying to do - is to have a button on one of the dashboards to open my garage door but only when the button is being hold, not clicked (to avoid unintended click on a button by accident).

Any change I can achieve this with current version?

**Comment by basbruss** [comment]
This is already possible and pre-published documentation can be found here: https://github.com/UI-Lovelace-Minimalist/UI/blob/release/docs/setup/custom_actions.md#overwrite-custom-actions

**Comment by TroLoos** [comment]
Got you... indeed it almost works, I didn't check it thoroughly.

Here's my code:

      - type: 'custom:button-card'
        template: card_input_boolean
        entity: input_boolean.combo_door
        variables:
          ulm_card_input_boolean_name: Combo Door Test
          ulm_card_tap_action: "more-info"
          ulm_card_hold_action: "more-info"
          ulm_card_double_tap_action: "more-info"
          ulm_icon_tap_action: "more-info"
          ulm_icon_hold_action: "more-info"
          ulm_icon_double_tap_action: "more-info"
          ulm_name_tap_action: "more-info"
          ulm_name_hold_action: "more-info"
          ulm_name_double_tap_action: "more-info"

And it works for all event except the most important: ulm_card_tap_action: "more-info" - it just toggles the entity (default action). Seems like a bug, right? When it works, it is exactly what I'm looking for :-).
