### ISSUE TITLE
Custom Card "Room" text overflow

### ISSUE THREAD

**Issue by mdb17** [UI-Lovelace-Minimalist/UI#861]
If you apply a label it over flows into the climate button. 

I would expect the text to truncate if the climate button is present. 

<img width="404" alt="image" src="https://user-images.githubusercontent.com/20051857/179831304-534bb854-93e2-40ce-a89d-b78f10dd553e.png">

**Comment by mdb17** [comment]
@mpeterson found that you made the 2.0.0 commit

**Comment by mpeterson** [comment]
I'll try to fix it as soon as I can.

**Comment by mpeterson** [comment]
@mdb17 would you test this code and see if it fixes your issue?

**Comment by mpeterson** [comment]
Forcing a label like the one in your screenshot I get now proper handling:

<img width="268" alt="image" src="https://user-images.githubusercontent.com/11870/180615151-b25685aa-2dc9-4466-8de0-e7711ab44332.png">

**Comment by mdb17** [comment]
It's working here on my end now

![57CCE2BD-FA12-4805-8EDB-009B238DE864](https://user-images.githubusercontent.com/20051857/180615280-54b9c936-713f-4601-a2e9-aad49d96170b.jpeg)
