### ISSUE TITLE
Custom Card "Room" emhancements

### ISSUE THREAD

**Issue by mdb17** [UI-Lovelace-Minimalist/UI#862]
A couple of suggestions I have about the new 2.0.0 update:
Allow the name to spill into the climate area if climate isn't being used
Add the hold_action that opens the thermostat popup when holding on the climate button.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/20051857/179834097-433d7a58-e259-414e-a76c-8fd40c5bf340.png">

@mpeterson

**Comment by mpeterson** [comment]
I'll try to get to it as soon as I have some free time I can dedicate to this. Sounds like good ideas.

**Comment by mpeterson** [comment]
@mdb17 addressed these here: https://github.com/UI-Lovelace-Minimalist/UI/pull/881

Let me know what you think!

**Comment by mpeterson** [comment]
Example of how it looks
<img width="501" alt="image" src="https://user-images.githubusercontent.com/11870/180617316-22dae5bb-4695-45e3-a886-71b9c79e9b87.png">

**Comment by mdb17** [comment]
Looks good! I will give it a try this evening hopefully.

**Comment by mdb17** [comment]
Works well on my end.
