### ISSUE TITLE
Deafult Dashboard, Custom Element Doesn't exist

### ISSUE THREAD

**Issue by derp90** [UI-Lovelace-Minimalist/UI#868]
**Describe the bug**
A default installation, button Card and auto-entitles are claimed to be missing

**To Reproduce**

1. Install Minimalis UI using HACS
2. Install dependencies using HACS
3. Add integration (Do not include custom cards) [was tried with this option as well, no effect]
4. Set theme to minimalist-desktop 
5. Reboot HASS, reload configuration, ctrl+f5 browser and reload minimalist UI

**Expected behavior**
The default example dashboard should function

**Screenshots**
![installed 1](https://user-images.githubusercontent.com/32005229/180114437-3e85f03d-5a06-41ff-9fb1-87836c76b7a7.png)
![installed 2](https://user-images.githubusercontent.com/32005229/180114438-2565adf9-5ce8-4123-b2d7-53d3cfcb8aea.png)
![Missing](https://user-images.githubusercontent.com/32005229/180114440-82862652-3a03-4341-b96d-ad92d94c38ea.png)

**Comment by basbruss** [comment]
@derp90 

Most likely HACS has not added the resource paths to your resources list. You can confirm this by checking `https://yourhaurl//config/lovelace/resources`. And add them manually if needed.

**Comment by derp90** [comment]
That page is completely blank for me. What is supposed to be here?  I couldn't find any information in the documentation.

**Comment by basbruss** [comment]
You should add all resources manually. Or set HA in storage mode so HACS can handle it. 
By reading carefully when installing a custom_component HACS prompts you with the correct lines to add, see example:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/68892092/180320237-bea66d83-45f1-4b1d-bffa-a59cce4c7ac8.png">

**Comment by derp90** [comment]
After adding all the missing resources, the default dashboard is still full of errors
![resour](https://user-images.githubusercontent.com/32005229/180338533-dbd451a0-d490-4571-bc16-71d6addfe4f4.png)

**Comment by derp90** [comment]
After adding all the resource links, and fixing a mistake in my ui-lovelace.yaml that was made when trying to troubleshoot the first issue, it now works! Thank you for you help
