### ISSUE TITLE
Custom Card "Room" entity not showing

### ISSUE THREAD

**Issue by Yasp0** [UI-Lovelace-Minimalist/UI#871]
I used the Custom Card "Room" example code with a light entity but the light button is not showing.

Any ideas on how to fix this? The entity ID is correct as stated in the developer tools.

**Comment by mdb17** [comment]
Are you using the 2.0.0 version?

**Comment by Yasp0** [comment]
I am using the 1.0.2 version.

**Comment by EverythingSmartHome** [comment]
> I am using the 1.0.2 version.

There was breaking changes added to the room card, check here for the latest docs on how to use it:
https://github.com/UI-Lovelace-Minimalist/UI/tree/main/custom_cards/custom_card_esh_room

**Comment by Yasp0** [comment]
Thanks, I updated to 1.0.3 and implemented the new example code. Now working fine.

**Comment by mpeterson** [comment]
Awesome. Would you be so kind to close this issue, @Yasp0 ? Thanks
