### ISSUE TITLE
custom_card_esh_welcome.md

### ISSUE THREAD

**Issue by laurens362** [UI-Lovelace-Minimalist/UI#882]
**Describe the solution you'd like**
Id love to have the custom_card_esh_welcome card to be adjusted that the "welcome part" is optional.
I kinda like this card for navigation but the welcome part isnt really handy for me.

**Comment by basbruss** [comment]
@laurens362 take a look at https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_scenes/
This is a card with only the pills 😉
