### ISSUE TITLE
Thermostat Card default HVAC Mode

### ISSUE THREAD

**Issue by Orishas** [UI-Lovelace-Minimalist/UI#895]
I use Thermostat Card with ulm_card_thermostat_enable_hvac_modes and ulm_card_thermostat_enable_collapse options.
If i click on the card by default the HVAC Heat is the default mode and heating is starting with full power.
Is there any chance you can change the default HVAC Mode to Auto?

**Comment by eddydordt** [comment]
Is there a solution for this problem?

**Comment by wilbiev** [comment]
Cleaning up issue list
