### ISSUE TITLE
Custom-card "Waste collection" - Alert is displayed behind the text

### ISSUE THREAD

**Issue by idominiki** [UI-Lovelace-Minimalist/UI#897]
**Describe the bug**
The Alert icon at the Custom-card "Waste collection" from @Paddy0174 is displayed behind the text.

**Screenshots**
<img width="493" alt="image" src="https://user-images.githubusercontent.com/62521486/181184556-3d52172a-f474-40b6-8be2-4d97f7badbb7.png">

**Comment by DavidRosseljong** [comment]
I have the same issue on some cards, especially when it's unavailable.

![image](https://user-images.githubusercontent.com/39567696/181815175-e2194486-f5d6-4bf2-99a9-c61cf4bd98dd.png)

![image](https://user-images.githubusercontent.com/39567696/181815224-abb30331-6bcc-4ca7-94b4-b327c7385a39.png)

**Comment by basbruss** [comment]
See #892

**Comment by idominiki** [comment]
I understand this fix, but it isn't really a fix. I want these notification 1 day before waste collection.

**Comment by basbruss** [comment]
Oh sorry that fix was more related to the comment of @DavidRosseljong . Which problem is slightly different.

**Comment by LaurentMouchart** [comment]
Is there any update?

**Comment by stefa168** [comment]
Having a similar issue with the notification not appearing at all. Any suggestion?

**Comment by photomoose** [comment]
@stefa168 to get the notification visible, you need to add the `add_days_to` property to your *sensor* configuration. For example:

```
sensor:
  - platform: waste_collection_schedule
    name: Waste Collection
    add_days_to: true # this line is important
```

However, as discussed above, the notification appears behind the icon. Also, it doesn't seem to be visible at all if you have a custom `value_template` property.
