### ISSUE TITLE
custom_card_esh_welcome not work

### ISSUE THREAD

**Issue by SamueleBrunini** [UI-Lovelace-Minimalist/UI#901]
I tried to install the custom component custom_card_esh_welcome not work but nothing appears on the screen,
either by installing the dependencies manually or automatically during configuration

![image](https://user-images.githubusercontent.com/64777341/181289605-d9515fd4-b3e2-4c84-9ba6-27947881de21.png)

**Comment by Kaysera** [comment]
I had the same error by following the Everything Smart Home Youtube tutorial. There is a typo in the video, so in `ui-lovelace.yaml` he writes
```YAML
views:
  !include views/home.yaml
```
and it should be:
```YAML
views:
  - !include views/home.yaml
```
That solved it for me. Cheers!
