### ISSUE TITLE
Documentation issue on the wiki

### ISSUE THREAD

**Issue by snigehere** [UI-Lovelace-Minimalist/UI#905]
Incorrect hyperlink on wiki page

**To Reproduce**

1. On the wiki page https://ui-lovelace-minimalist.netlify.app/installation
2. Page down to the section "A little technical insight"
3. two hyperlinks are shown in this bit:
Whatever way you choose, here are the instructions:
For yaml-mode here
For UI-mode here

Neither work - the sub directory /installation/ is missing from the url
eg - link is 
https://ui-lovelace-minimalist.netlify.app/yaml-mode
but should be
https://ui-lovelace-minimalist.netlify.app/installation/yaml-mode

**Comment by basbruss** [comment]
You are referring to the outdated wiki. See the pinned issue to find the right one #566

**Comment by snigehere** [comment]
Thanks - I got there via a link from a YouTube video recommending your dashboard - I have written to the video owner asking them to update the link.  I see the pinned bug but the title didn't immediately jump out at me to say the old wiki was no longer maintained.
