### ISSUE TITLE
Card custom_card_eraycetinay_lock do not work, missing language variable

### ISSUE THREAD

**Issue by Nicxe** [UI-Lovelace-Minimalist/UI#936]
The card custom_card_eraycetinay_lock do not work, get error that language variable are missing. Cant fins any information in the docs for that attribute. 

![image](https://user-images.githubusercontent.com/27124316/183903897-56741ad2-5f8c-4a05-8053-e5e25cc060cf.png)
```

  - type: "custom:button-card"
    entity: lock.ytterdorren
    template: "custom_card_eraycetinay_lock"
    name: "Door Lock"
```

**Comment by 1337Reaper** [comment]
Same error with custom_card_damix48_power_details

**Comment by basbruss** [comment]
@Nicxe @1337Reaper 

Language files must still be manually added from the Github to your system. The best place is `config/ui_lovelace_minimalist/custom_cards/`.
Documentation is available here: https://ui-lovelace-minimalist.github.io/UI/setup/custom_cards/#custom-cards

**Comment by ericlamoureux285** [comment]
@basbruss

I got the same thing with Custom-card "Speedtest". I look at the link you posted. 

config
└── ui_lovelace_minimalist
    ├── custom_cards
    |   ├── custom_card_irmajavi_speedtest
    |   |   ├── custom_card_irmajavi_speedtest.yaml
    |   |   └── EN.yaml
    └── dashboard

Where do I find all the variables I need for this custom card?
