### ISSUE TITLE
Bug with my-slider required card

### ISSUE THREAD

**Issue by fabiorcosta** [UI-Lovelace-Minimalist/UI#952]
**Describe the bug**
I have made a clear install of Minimalist Ui.
All the required buttons are installed:
![image](https://user-images.githubusercontent.com/82267134/185711826-2f3f8ffc-bc20-4258-904e-e23bcc47963c.png)

All extra modules are listed:
![image](https://user-images.githubusercontent.com/82267134/185712059-d57cfcac-20ab-42d2-a500-23f912f93ea5.png)

Using the light card with slider = true:
![image](https://user-images.githubusercontent.com/82267134/185712254-c73a0fdf-5783-4aac-b453-9aaa3c8068d1.png)

I am getting an error:
![image](https://user-images.githubusercontent.com/82267134/185712304-77400442-47a7-4e32-9e46-421df9d5acca.png)

**Comment by tamet83** [comment]
I have the same problem as you. I don't know what happened, it worked yesterday.

**Comment by Tosko4** [comment]
@fabiorcosta can you confirm if the resources are there? Could be as simple as that.

**Comment by Tosko4** [comment]
> @Tosko4 I did not vahe resources area on my configuration.yaml. Should I put anywhere?

@fabiorcosta you can go to settings > dashboards > three dots at the top > choose resources and add the lines there

**Comment by crivera8602** [comment]
> I have the same problem as you. I don't know what happened, it worked yesterday.
> 
> EDIT: I found the solution for my problem. I added this info to my resources:
> 
> ```
> - url: /hacsfiles/my-cards/my-cards.js 
>   type: module
> ```

This worked for me! Thanks
