### ISSUE TITLE
Custom-card "Person" mising code

### ISSUE THREAD

**Issue by ericlamoureux285** [UI-Lovelace-Minimalist/UI#967]
On the page of the Custom-card "Person" (https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_imswel_person/), I don't see the template code to add to my yaml. Where can i find it?

**Comment by shogun160** [comment]
[https://github.com/UI-Lovelace-Minimalist/UI/blob/main/custom_cards/custom_card_imswel_person/custom_card_imswel_person.yaml](url)
But you can also select the desired custom cards in the integration menu to be downloaded automatically.
