### ISSUE TITLE
No slider tumb color temp popup

### ISSUE THREAD

**Issue by K0ne28** [UI-Lovelace-Minimalist/UI#982]
**Describe the bug**
Since the last update, there is no longer a slider thumb in the popup for lights with color temperature.

**To Reproduce**

1. Create light card with a light entity with color temperature and activate popup.
2. Open popup of this light.
3. Observe that color temperature slider has no thumb.

**Expected behavior**
color temperature slider has a thumb.

**Screenshots**
![Screenshot 2022-09-09 165958](https://user-images.githubusercontent.com/80079958/189380728-c3f55d9c-8ada-4db5-8cdf-5fcd5356056f.png)
![WhatsApp Image 2022-09-09 at 17 04 44](https://user-images.githubusercontent.com/80079958/189382224-19de8894-edf3-4606-808f-76b186d73f28.jpeg)

**Additional context**
the slider works, but only if you click on it.

**Comment by schumijo** [comment]
Should be related to this issue since we move to my-slider-v2 https://github.com/AnthonMS/my-cards/issues/33

**Comment by AndyVRD** [comment]
I have updated the slider to v2 and send it over to @basbruss. That issue is not related to the one @schumijo linked, I don’t have set a thumb for the color temperature. I will fix it today with a pr.

**Comment by schumijo** [comment]
Hi @AndyVRD 
Hum... But you set allowTapping so it shouldn't be a problem.

**Comment by basbruss** [comment]
As I understand it's only a visual  thing. It functions as it is supposed to. We can always at the visual back in an upcoming release.

**Comment by AndyVRD** [comment]
Like bas mentioned it’s only a visual thing. But I think the OP ask for a thumb slider to get the visual feeling of sliding. The effect of the color slider will be impossible because we have set a fixed linear gradient color.

**Comment by pollev** [comment]
Hi all,

For me this is not a visual thing. The slider for the brightness and the color picker both work.
The slider for the temperature does nothing anymore (used to work).

**Comment by AndyVRD** [comment]
Ok how you now describe it is indeed related to the bug @schumijo linked. This is a issue related to my-slider-v2 so we have to wait until this gets fixed.
