### ISSUE TITLE
custom_card_imswel_person: map not visible on first click

### ISSUE THREAD

**Issue by wokkeltje13** [UI-Lovelace-Minimalist/UI#986]
The first time you open the popup of the "custom_card_imswel_person" card, the map is not visible, when you close the popup, the next time you open the popup, the map is visible as expected. This can be reproduced every time you reopen the HA app.

**Comment by AndyVRD** [comment]
This is not related to UI-Lovelace-Minimalist or browser_mod but to the map card itself. Thomas (created of browser_mod...) have mentioned this many times that the map card had always this behavior, so i'm afraid this "bug" will never be fixed...
