### ISSUE TITLE
Thermostat Card quick temperature adjustment

### ISSUE THREAD

**Issue by roschi02** [UI-Lovelace-Minimalist/UI#992]
I use the Thermostat Card to control a Hama thermostat. Unfortunately, the thermostat is very slow when updating the temperature. So if I try to change the temperature, I have to wait several seconds between button presses because the card is using the current temperature minus the step.
My request is that the card is changed, so it controls a variable that is set after a few seconds with no further input.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/19667033/189688992-8b18d7ef-3e4c-46f0-b0a0-135b1200bfb8.gif)

**Comment by tamet83** [comment]
I confirm that the card is not responsive and it’s not the only one. Also custo esh room card is not responsive when lights get off

**Comment by wilbiev** [comment]
Cleaning up issue list
