### ISSUE TITLE
How to supply additional/custom button_card_templates? 

### ISSUE THREAD

**Issue by laimoncijus** [UI-Lovelace-Minimalist/UI#997]
Is there a way to supply additional `button_card_templates` to the ones, which are provided by UI Minimalist? 

I've configured the templates location as described by the documentation:

```
# Button cards location
button_card_templates: !include_dir_merge_named "custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"
```

But to already existing ones, which depend on the state value (like `green_on` or `green_off`), I would like to append my own ones, having other state values like `open` or `closed` (for a cover type component in this case - I would like to create my own templates `green_open` and `green_closed`).

Or maybe there is an easier way to archive this?

**Comment by basbruss** [comment]
Hi @laimoncijus 

You can put all your custom button card templates within the `/config/ui_lovelace_minimalist/custom_cards/` directory.

**Comment by laimoncijus** [comment]
Hi @basbruss,

Thanks a lot, it worked out well!
